export const copy = {
  brand: {
    name: "NEXHIBIT",
    displayName: "Nexhibit",
    tagline: "Where students get seen",
    description:
      "The reverse career fair platform for international students at Zhejiang University of Technology.",
  },

  navigation: {
    marketing: {
      howItWorks: "How it works",
      students: "For students",
      employers: "For employers",
      about: "About",
      pricing: "Pricing",
      backHome: "Back to home",
    },
    primary: {
      home: "Home",
      howItWorks: "How it works",
      students: "Student profiles",
      employers: "Employers",
      events: "Events",
      pricing: "Access",
      faq: "FAQ",
    },
    student: {
      overview: "Your overview",
      profile: "Profile",
      portfolio: "Your portfolio",
      events: "Events",
      messages: "Messages",
      matches: "Employer interest",
      settings: "Privacy settings",
      eventDay: "Event Day",
      dashboard: "Dashboard",
      billing: "Billing",
    },
    employer: {
      overview: "Your hiring dashboard",
      dashboard: "Dashboard",
      browse: "Browse students",
      scanner: "Scanner",
      shortlist: "Shortlist",
      events: "Book event slots",
      messages: "Messages",
      team: "Team access",
      billing: "Billing",
    },
    admin: {
      overview: "Platform overview",
      verification: "Verification queue",
      events: "Event management",
      employers: "Employer accounts",
      students: "Student records",
      reports: "Outcome reports",
      billing: "Billing",
    },
  },

  buttons: {
    primary: {
      signUp: "Get started",
      signUpStudent: "Create your student profile",
      signUpEmployer: "Open employer demo",
      logIn: "Log in",
      verifyStudent: "Start verification demo",
      saveProfile: "Save profile",
      publishProfile: "Publish profile",
      bookBooth: "Reserve your booth",
      sendMessage: "Send message",
      requestIntro: "Request an introduction",
      addToShortlist: "Save to shortlist",
    },
    secondary: {
      previewProfile: "Preview your profile",
      editProfile: "Edit profile",
      viewPortfolio: "View portfolio",
      compareStudents: "Compare students",
      downloadBadge: "Download QR badge",
      exportShortlist: "Export shortlist",
      managePrivacy: "Manage visibility",
      viewEventMap: "View floor plan",
    },
    cta: {
      studentHero: "Show employers your work",
      employerHero: "Discover portfolio-ready international talent",
      finalStudent: "Build your profile",
      finalEmployer: "Browse the next cohort",
      scheduleDemo: "Talk with the NEXHIBIT team",
    },
    utility: {
      uploadFile: "Upload file",
      replaceFile: "Replace file",
      removeFile: "Remove file",
      copyLink: "Copy profile link",
      scanQr: "Scan QR code",
      filterResults: "Filter results",
      clearFilters: "Clear filters",
      inviteTeammate: "Invite teammate",
      markAsRead: "Mark as read",
    },
  },

  emptyStates: {
    noConversations:
      "Your conversations with employers will appear here. Start one from any student profile or event shortlist.",
    noShortlist:
      "Save students from Browse to build a focused shortlist before the next NEXHIBIT event.",
    noEvents:
      "The next event schedule is being finalized. You can still complete your profile and get ready.",
    noNotifications:
      "You are caught up. We will only notify you when something needs your attention.",
    noPortfolio:
      "Add projects, demos, or writing samples so employers can understand how you think and build.",
    noSearchResults:
      "No profiles match these filters yet. Try widening the category, language, or availability filters.",
    noMatches:
      "Employer interest will appear here after your profile is published and visible for matching.",
  },

  helperText: {
    zjutVerification:
      "This prototype simulates a ZJUT verification step with mock student records.",
    privacyDefault:
      "You control what employers can see. Turn off any field you do not want shown on your public profile.",
    portfolioUpload:
      "Show your work with projects, demos, portfolios, reports, or case studies. Files can be up to 25MB.",
    studentId:
      "Use the student ID printed in your ZJUT international student record.",
    passportNumber:
      "Passport fields are shown only to demonstrate a future verification flow and are not processed in this prototype.",
    hskLevel:
      "Add your current HSK level so employers can understand your Mandarin working ability.",
    availability:
      "Tell employers when you can start. Clear availability helps them move faster.",
    preferredLocations:
      "Choose the cities where you can realistically interview, intern, or work.",
    boothBooking:
      "Your booth is where employers find you during the event. You can update your profile before check-in.",
    qrBadge:
      "Print or save this demo badge. Employers can use it to open the prototype student profile during the presentation.",
    shortlist:
      "Shortlisted students stay private to your employer team until you send a message.",
    employerVerification:
      "This prototype demonstrates how employer review could work before messaging students or booking event slots.",
    messageEtiquette:
      "Keep your first message specific. Mention the project, skill, or role that made you reach out.",
  },

  toasts: {
    profileSaved: "Profile updated.",
    profilePublished: "Your profile is live. Employers can now discover your work.",
    profileUnpublished: "Your profile is hidden from employer search.",
    slotBooked: "Your booth is reserved. We will send a reminder 24 hours before the event.",
    slotCancelled: "Your booth reservation has been cancelled.",
    messageSent: "Message sent.",
    studentShortlisted: "Student saved to your shortlist.",
    studentRemoved: "Student removed from your shortlist.",
    fileUploaded: "File uploaded and added to your portfolio.",
    fileRemoved: "File removed from your portfolio.",
    qrCopied: "Profile QR link copied.",
    settingsSaved: "Your settings are saved.",
    teammateInvited: "Invitation sent to your teammate.",
    loginSuccess: "Demo login accepted. Opening your portal.",
  },

  errors: {
    invalidCredentials:
      "Those demo credentials did not match this prototype flow. Check the sample student ID and try again.",
    sessionExpired: "Your session timed out. Please log in again to keep your account secure.",
    profileIncomplete:
      "Add your headline, availability, and at least two projects before publishing your profile.",
    uploadTooLarge: "That file is over 25MB. Compress it or upload a smaller version.",
    unsupportedFile:
      "That file type is not supported yet. Upload a PDF, image, slide deck, or document.",
    network:
      "The connection dropped before we could save your changes. Keep this page open and try again.",
    messageBlocked:
      "A future deployment would require employer review before messaging students. This prototype does not perform that review.",
    boothUnavailable:
      "That booth was just reserved by someone else. Choose another open booth on the floor plan.",
    duplicateAccount:
      "A demo account already exists for those sample details. Log in or ask the presentation team for help.",
    permissionDenied:
      "You do not have access to this page. Switch accounts or contact the NEXHIBIT team.",
    requiredField: "Complete this field so we can show accurate information.",
    invalidUrl: "Enter a full link that starts with http:// or https://.",
    invalidEmail: "Enter a school or work email address you can access.",
  },

  status: {
    upcoming: "Upcoming",
    ongoing: "Live now",
    past: "Completed",
    verified: "ZJUT verification demo",
    pendingVerification: "Pending verification",
    rejectedVerification: "Needs updated details",
    profileLive: "Profile live",
    profileDraft: "Draft profile",
    boothReserved: "Booth reserved",
    boothOpen: "Booth open",
    shortlisted: "Shortlisted",
    invited: "Invited",
    replied: "Replied",
    waiting: "Waiting for reply",
    offerReported: "Offer reported",
    hidden: "Hidden from employers",
  },

  marketing: {
    hero: {
      caption: "ZJUT career services concept",
      headline: "Where international students get seen",
      subheadline:
        "A high-fidelity reverse career fair prototype for Zhejiang University of Technology. Employers come to student booths with project, language, and availability context.",
      ctaPrimary: "I am a student",
      ctaSecondary: "I am an employer",
      trustLine: "Prototype dataset · 30 demo profiles · 8 mock employer accounts",
      trustStats: [
        { value: 100, suffix: "%", label: "verification demo" },
        { value: 38, suffix: "+", label: "nationalities" },
        { value: 2, suffix: "", label: "focused events per year" },
      ],
      profileCardCta: "Verification demo",
    },
    employerShowcase: {
      caption: "Employer discovery feed",
      heading: "Companies keep moving through the talent floor",
      body:
      "A live-style employer showcase turns the landing page into the event itself: mock company accounts, hiring focus areas, and cross-border roles always in motion.",
      statOne: "8 mock employers",
      statTwo: "30 demo students",
      statThree: "Portfolio evidence",
      stats: [
        { value: 8, label: "mock employers" },
        { value: 30, label: "demo students" },
        { value: 100, suffix: "%", label: "portfolio evidence" },
      ],
      cta: "Browse employer view",
      cardLabel: "Now reviewing",
      skillsLabel: "Hiring signals",
      liveBadge: "Live — Companies actively reviewing",
    },
    liveActivity: [
      "Nattapong S. opened the verification demo",
      "BYD International saved 3 profiles to their shortlist",
      "Booth slots opened for Spring Fair 2026",
      "Geek+ Robotics messaged a robotics finalist",
      "Alibaba Cloud reviewed portfolio evidence before the fair",
      "Siemens China shortlisted multilingual automation talent",
    ],
    logoCloud: {
      heading: "Mock employer set for the prototype",
    },
    motionStats: {
      heading: "A prototype talent floor with transparent signal",
      students: "demo students",
      employers: "mock employers",
      events: "focused events per year",
      verified: "verification demo",
    },
    testimonialCarousel: {
      caption: "Student outcomes",
      heading: "Proof that the room changed",
      quotes: [
        {
          name: "Nattapong Saetang",
          program: "Software Engineering",
          flag: "🇹🇭",
          quote:
            "Three employers walked into my booth in twenty minutes. I did not have to repeat my pitch once.",
        },
        {
          name: "Nguyen Thi Minh Linh",
          program: "Data Science",
          flag: "🇻🇳",
          quote:
            "The conversation started from my dashboard project, not my visa status. That changed the whole tone.",
        },
        {
          name: "Ayesha Khan",
          program: "Mechatronics Engineering",
          flag: "🇵🇰",
          quote:
            "My QR badge made the event feel structured. Employers arrived already knowing what I could build.",
        },
        {
          name: "P4",
          program: "Year 3 Business",
          flag: "🇮🇩",
          quote:
            "Now I can show my work before explaining my accent.",
        },
      ],
    },
    faq: {
      caption: "Questions students ask first",
      heading: "Clear rules before the event begins",
      items: [
        {
          question: "How does ZJUT verification work?",
          answer:
            "Students use a simulated ZJUT record step, then NEXHIBIT labels academic fields as part of a verification concept.",
        },
        {
          question: "Who can become a NEXHIBIT employer?",
          answer:
            "Reviewed employer accounts in this prototype can browse profiles, book event slots, scan QR badges, and message students in the demo workspace.",
        },
        {
          question: "Are interpreters really provided?",
          answer:
            "The event model supports interpreter availability for selected booths and clearer language signals inside every student profile.",
        },
        {
          question: "Can I attend without a booth?",
          answer:
            "Students can still build a portfolio-ready demo profile and browse event information, but booth slots create the strongest employer discovery signal.",
        },
        {
          question: "What happens to my data after the event?",
          answer:
            "Profile visibility and contact permissions stay under student control. Students can pause visibility, export their data, or request deletion.",
        },
        {
          question: "Is NEXHIBIT only for ZJUT students?",
          answer:
            "This prototype is scoped to Zhejiang University of Technology so the verification, event layout, and demo story stay focused.",
        },
      ],
    },
    finalMotionCta: {
      heading: "Ready to be seen?",
      body:
        "Build a portfolio-ready profile that moves before you enter the hall, then let employers arrive with context.",
      liveCounterLabel: "students joined this week",
    },
    howItWorks: {
      caption: "For students",
      heading: "How NEXHIBIT works",
      steps: [
        {
          title: "Complete the verification concept",
          description:
            "Use the demo student ID flow to show how university verification could prefill academic fields, then choose what employers can see.",
        },
        {
          title: "Build a profile worth stopping for",
          description:
            "Add projects, languages, skills, awards, and availability so employers see evidence before they see a resume.",
        },
        {
          title: "Let employers come to you",
          description:
            "At each reverse career fair, employers scan your QR badge, review your work, and start focused conversations.",
        },
      ],
    },
    employerValue: {
      caption: "For employers",
      heading: "Meet portfolio-ready international talent without cold-searching.",
      body:
        "Browse student profiles by field, language ability, location preference, and availability before the event starts.",
      bullets: [
        "Find students who already match your regional markets.",
        "Review project evidence before booking conversations.",
        "Build a shortlist your whole hiring team can use.",
      ],
    },
    comparison: {
      traditionalTitle: "Traditional fair",
      traditionalCaption: "Students chase booths, wait in lines, and repeat the same introduction.",
      reverseTitle: "NEXHIBIT fair",
      reverseCaption: "Students exhibit their work. Employers walk in with context and intent.",
      studentChases: "Student chases employers",
      employersCome: "Employers come to you",
    },
    stats: {
      heading: "Built for a campus with global talent",
      studentsRegistered: "demo student profiles",
      employersOnboarded: "mock employer accounts",
      successfulMatches: "sample student-employer matches",
      countriesRepresented: "countries represented",
    },
    testimonials: {
      heading: "What students told us",
      intro:
        "The platform started with a simple problem: international students had strong work to show, but too few rooms where employers expected to see it.",
      caption: "Class research context",
      note: "Quotes are anonymized presentation material from the May 2026 class prototype research process.",
    },
    finalCta: {
      heading: "Ready to be discovered before the handshake?",
      body:
        "Create your prototype profile, then arrive at the next NEXHIBIT event demo with your work already visible.",
      studentButton: "Create your profile",
      employerButton: "Browse demo talent",
    },
    comparisonDetails: {
      heading: "Traditional vs Reverse Career Fair",
      traditionalItems: [
        "Students chase employers booth to booth",
        "Resume gets 6 seconds of attention",
        "Language confidence determines outcome",
        "International students get overlooked",
      ],
      reverseItems: [
        "Employers come to student booths",
        "Live demos, portfolios, focused conversations",
        "Verification concept and language signals available",
        "Built specifically for international students",
      ],
    },
    statsLabels: {
      students: "Students",
      employers: "Employers",
      countries: "Countries",
      verified: "Verification demo",
    },
    demo: {
      eyebrow: "Prototype access",
      subheading: "Navigate directly to any portal to see the full experience.",
      student: {
        label: "Student Portal",
        description: "Profile editing, event booking, event-day live view, and employer messaging.",
        cta: "Open student portal",
      },
      employer: {
        label: "Employer Portal",
        description: "Browse 30 demo student profiles, shortlist, scan QR badges, and message students.",
        cta: "Open employer portal",
      },
      admin: {
        label: "Admin Console",
        description: "Platform analytics, employer accounts, and event management.",
        cta: "Open admin console",
      },
    },
  },

  layout: {
    footer: {
      groups: [
        {
          title: "Product",
          links: ["Features", "How it works", "Pricing", "For Employers"],
        },
        {
          title: "Company",
          links: ["About", "Team", "Contact", "Careers"],
        },
        {
          title: "Resources",
          links: ["Help Center", "Success Stories", "Blog", "Press"],
        },
        {
          title: "Legal",
          links: ["Privacy Policy", "Terms", "PIPL considerations", "Cookie Policy"],
        },
      ],
      copyright: "© 2026 NEXHIBIT · Zhejiang University of Technology career services concept",
    },
  },

  pages: {
    student: {
      portal: "Student Portal",
      onboarding: {
        heading: "ZJUT verification demo",
        subheading: "This prototype preloads mock academic fields. Choose what employers would see.",
        stepVerify: "Verify",
        stepCustomize: "Customize",
        stepDone: "Done",
        section1Title: "Personal Information",
        section1Caption: "Required for matching",
        section1AlwaysVisible: "Always visible",
        section2Title: "Academic Data",
        gpaLabel: "GPA",
        gpaHelper: "Shown to employers who filter by academic performance",
        coursesLabel: "Major courses completed",
        coursesHelper: "Helps employers see your specialization",
        awardsLabel: "Academic awards",
        awardsHelper: "Showcases recognition",
        rankingLabel: "Class ranking",
        rankingHelper: "Optional — shown only if you enable",
        disciplinaryLabel: "Disciplinary record",
        disciplinaryHelper: "Off by default — most students keep this private",
        section3Title: "Behavioral Data",
        activitiesLabel: "Activities & clubs",
        activitiesHelper: "Shows you are engaged beyond academics",
        volunteerLabel: "Volunteer experience",
        volunteerHelper: "Demonstrates commitment",
        attendanceLabel: "Attendance rate",
        attendanceHelper: "Off by default",
        privacyNote: "You can change these anytime in Settings → Privacy.",
        saveButton: "Save preferences",
        skipButton: "Customize later",
      },
      profile: {
        heading: "Your Profile",
        sidebarStrengthLabel: "Profile strength",
        tabPersonal: "Personal",
        tabAcademic: "Academic",
        tabPortfolio: "Portfolio",
        tabPreview: "Preview as employer",
        previewBanner: "Preview mode — this is what employers see",
        backToEdit: "Back to edit",
        uploadAreaHint: "Drag & drop or click to upload",
        addProject: "Add project",
        addLink: "Add link",
        uploadFile: "Upload file",
        addLanguage: "Add language",
        syncedLabel: "Demo academic field",
        contactPreferenceLabel: "Contact preference",
        contactInApp: "In-app messaging only",
        contactInAppEmail: "In-app + Email",
        contactAll: "All channels",
        saveSection: "Save changes",
        headlineCounter: "characters remaining",
        bioCounter: "characters remaining",
      },
      events: {
        heading: "Career Events",
        subheading: "Two events per year. Each event has 80–100 booth slots split across categories.",
        tabUpcoming: "Upcoming",
        tabPast: "Past",
        tabAll: "All",
        viewAndBook: "View & Book",
        enterEvent: "Enter event",
        viewResults: "View results",
        slotsLabel: "slots booked",
        employersLabel: "employers registered",
      },
      booking: {
        widgetHeading: "Book your booth slot",
        alreadyBookedHeading: "Your slot is confirmed",
        categoryLabel: "Category",
        confirmButton: "Confirm slot",
        boothNote: "Booth assignment will be confirmed after booking.",
        dialogHeading: "You're booked!",
        dialogEventLabel: "Event",
        dialogDateLabel: "Date",
        dialogSlotLabel: "Slot",
        dialogBoothLabel: "Booth",
        dialogNote: "We'll send a reminder 24 hours before. You can prepare your booth materials in your Profile.",
        viewProfile: "View my profile",
        done: "Done",
        changeSlot: "Change slot",
      },
      eventDay: {
        liveLabel: "Live · Career Fair 2026 — Spring Edition",
        slotEndsLabel: "Your slot ends in",
        boothCardTitle: "Booth information",
        locationLabel: "Business Section · Building 8, Hall A",
        quickActionsTitle: "Quick actions",
        showQrLabel: "Show your QR badge",
        openPortfolioLabel: "Open my portfolio",
        requestBreakLabel: "Request a 5-min break",
        visitorStreamTitle: "Visitor stream — live",
        sessionStatsTitle: "This session",
        visitorsLabel: "visitors so far",
        shortlistedLabel: "saved to shortlist",
        feedbackLabel: "feedback received",
        qrInstruction: "Show this to visiting employers",
        qrDialogTitle: "Your QR badge",
        breakDialogTitle: "Break request noted",
        breakDialogBody:
          "Prototype mode: in a live fair, this would notify event staff and temporarily pause employer walk-ups for your booth.",
        breakDialogButton: "Back to event day",
      },
      dashboard: {
        welcomePrefix: "Hey",
        welcomeSuffix: "here's what happened since your last booth session.",
        profileViewsLabel: "Profile views",
        savedLabel: "Saved by employers",
        messagesLabel: "Messages",
        feedbackReceivedLabel: "Feedback received",
        viewersTitle: "Who viewed your profile",
        applicationTitle: "Application status",
        feedbackTitle: "Employer Feedback Summary",
        feedbackSubtitle:
          "Structured feedback from recruiters who viewed your booth, profile, or portfolio during recent prototype events.",
        feedbackPrototypeNote: "Prototype feedback based on mock recruiter evaluations.",
        feedbackEmpty: "No feedback matches this filter. Try viewing all recruiter comments.",
        filterAll: "All",
        filterThisWeek: "This week",
        filterThisMonth: "This month",
        viewCompany: "View company",
        sendMessage: "Send message",
        thisWeekTrend: "+12 this week",
      },
      messages: {
        heading: "Messages",
        searchPlaceholder: "Search conversations...",
        tabAll: "All",
        tabUnread: "Unread",
        tabArchived: "Archived",
        viewCompanyProfile: "View company profile",
        messagePlaceholder: "Type a message...",
        emptyHeading: "No conversations yet",
        emptyBody: "Your conversations with employers will appear here. Start one from any employer's profile.",
      },
      eventDetail: {
        tabOverview: "Overview",
        tabEmployers: "Registered Employers",
        tabLayout: "Booth Layout",
      },
      settings: {
        heading: "Settings",
        sectionAccount: "Account",
        sectionPrivacy: "Privacy",
        sectionNotifications: "Notifications",
        sectionVisibility: "Visibility",
        sectionData: "Data & Export",
        emailNote: "Demo school email field — locked in this prototype.",
        passwordSection: "Change password",
        offEventPrivacy: "Allow employers to view my profile when I am NOT at an event",
        searchResultsPrivacy: "Show me in recommended talent search results",
        researchPrivacy: "Allow university to share my outcome data anonymously for research",
        downloadData: "Download all my data",
        deleteAccount: "Delete my account",
        visibilityPublic: "Visible to reviewed demo employers",
        pauseVisibility: "Pause visibility",
        pauseHelper: "When paused, your profile is hidden from search and browse until you re-enable it.",
        piplNote: "Future production work would require a PIPL compliance review, consent logging, secure export, and deletion workflows.",
        exportPDF: "Export as PDF",
        exportJSON: "Export as JSON (developer)",
      },
    },
    employer: {
      portal: "Employer Portal",
      dashboard: {
        heading: "Dashboard",
        welcomePrefix: "Good to see you,",
        welcomeSuffix: "Your shortlist is ready when the event opens.",
        browsedLabel: "Students browsed",
        shortlistedLabel: "Shortlisted",
        messagesLabel: "Active conversations",
        recommendedTitle: "Recommended for you",
        recentActivityTitle: "Recent activity",
        viewAllStudents: "Browse all students",
        viewShortlist: "View shortlist",
        matchLabel: "match",
      },
      browse: {
        heading: "Browse Students",
        subheading: "Demo international talent profiles for the ZJUT prototype",
        commandEyebrow: "Talent pool",
        commandTitle: "30 prototype profiles ready for employer review",
        commandBody: "A broader mock student sample makes the reverse fair feel closer to a live recruiting environment while staying presentation-safe.",
        totalProfilesLabel: "Demo profiles",
        countriesLabel: "Countries",
        strongMatchesLabel: "Strong matches",
        activeRecentlyLabel: "Active recently",
        searchPanelTitle: "Find candidates",
        searchPlaceholder: "Search by name, skill, or major…",
        filterCategory: "Category",
        filterYear: "Year",
        filterEnglish: "English",
        filterHSK: "HSK",
        filterLookingFor: "Looking for",
        sortLabel: "Sort",
        clearFilters: "Clear filters",
        noResults: "No students match your filters.",
        noResultsHint: "Try widening your search or removing a filter.",
        viewProfile: "View profile",
        shortlist: "Shortlist",
        shortlisted: "Shortlisted",
        matchLabel: "match",
        studentsFound: "students",
        showingPrefix: "Showing",
        showingConnector: "of",
        verifiedProfilesLabel: "demo profiles",
        verifiedBadge: "Verification concept",
        gpaLabel: "GPA",
        hskLabel: "HSK",
        hskNone: "No HSK",
        yearLabel: "Year",
        availableLabel: "Available",
        responseLabel: "Response",
        activeLabel: "Active",
        countryLabel: "Country",
        addToShortlistLabel: "Add to shortlist",
        removeFromShortlistLabel: "Remove from shortlist",
      },
      studentDetail: {
        backToBrowse: "← Back to browse",
        sendMessage: "Send message",
        addToShortlist: "Add to shortlist",
        removeFromShortlist: "Remove from shortlist",
        shortlisted: "Shortlisted",
        matchScore: "Match score",
        matchExplanationTitle: "Why this match",
        tabOverview: "Overview",
        tabPortfolio: "Portfolio",
        tabAcademic: "Academic",
        availableFrom: "Available from",
        lookingFor: "Looking for",
        responseTime: "Typical response",
        lastActive: "Last active",
        preferredLocations: "Preferred locations",
      },
      scanner: {
        heading: "Scan Student QR",
        subheading: "Point the scanner at a student's event badge to open their profile.",
        orEnterManually: "Or enter student ID manually",
        studentIdPlaceholder: "e.g., stu-001",
        lookupButton: "Look up",
        scannedHeading: "Student found",
        notFound: "No student found with that ID.",
        viewProfile: "View profile",
        shortlist: "Shortlist",
        scanAnother: "Scan another",
      },
      shortlist: {
        heading: "Shortlist",
        subheading: "Students saved for follow-up",
        emptyHeading: "Your shortlist is empty",
        emptyBody: "Shortlisted students stay private to your team until you send a message.",
        remove: "Remove",
        sendMessage: "Message",
        viewProfile: "View profile",
        matchLabel: "match",
        exportList: "Export list",
        studentsCount: "students shortlisted",
      },
      messages: {
        heading: "Messages",
        searchPlaceholder: "Search students…",
        tabAll: "All",
        tabUnread: "Unread",
        tabArchived: "Archived",
        viewStudentProfile: "View student profile",
        messagePlaceholder: "Type a message…",
        emptyHeading: "No conversations yet",
        emptyBody: "Your conversations with students will appear here. Start one from any student profile.",
      },
    },
    admin: {
      portal: "Admin Portal",
      serviceLabel: "ZJUT Career Services",
      dashboard: {
        heading: "Platform Overview",
        summary: "Mock student growth, employer activation, and event outcomes for the June 2026 prototype dataset.",
        studentsLabel: "Students registered",
        employersLabel: "Employers onboarded",
        matchesLabel: "Successful matches",
        eventsLabel: "Events run",
        verificationQueueLabel: "Awaiting verification",
        registrationsTitle: "Student registrations over time",
        categoryTitle: "Students by category",
        nationalityTitle: "Top nationalities",
        employerGrowthTitle: "Employer growth over time",
        matchSuccessTitle: "Match success by category",
        avgSatisfactionLabel: "avg satisfaction",
        matchesGeneratedLabel: "matches generated",
        attendanceLabel: "attendance rate",
      },
      employers: {
        heading: "Employer Accounts",
        searchPlaceholder: "Search employers…",
        tabAll: "All",
        tabVerified: "Reviewed demo",
        tabPending: "Pending",
        verifyAction: "Verify",
        suspendAction: "Suspend",
        viewAction: "View",
        industryLabel: "Industry",
        sizeLabel: "Size",
        typeLabel: "Type",
        activeSinceLabel: "Active since",
        hiringLabel: "Hiring for",
      },
      events: {
        heading: "Event Management",
        createButton: "Create event",
        statusLabel: "Status",
        registrationsLabel: "Registrations",
        employersLabel: "Employers",
        dateLabel: "Date",
        slotsLabel: "Slot fill",
        viewAction: "Details",
        manageAction: "Manage",
        satisfactionLabel: "Satisfaction",
        matchesLabel: "Matches",
      },
    },
    successStories: {
      heading: "Success Stories",
      subheading: "Illustrative demo outcomes showing how NEXHIBIT could support international students at ZJUT.",
      storyLabel: "Their story",
      roleAtLabel: "Hired as",
      ctaHeading: "Ready to show the story in the prototype?",
      ctaBody: "Open the demo student profile flow and see how employers could come to you.",
      ctaButton: "Create your booth profile",
    },
    notFound: {
      heading: "Page not found",
      body: "The page you are looking for may have moved or never existed.",
      backHome: "Go back home",
    },
    login: {
      heading: "Welcome back",
      motionPill: "Where students get seen",
      motionHeadline: "Open the demo. Get discovered throughout the event cycle",
      keyboardHint: "Press ⌘ + Enter to submit",
      studentTab: "Student",
      employerTab: "Employer",
      studentIdPlaceholder: "e.g., 202210xxxxx",
      passportPlaceholder: "Passport number used at registration",
      employerEmailPlaceholder: "name@company.com",
      passwordPlaceholder: "Enter your password",
      studentButton: "Log in to your booth",
      employerButton: "Log in to employer portal",
      footerPrefix: "Do not have an account?",
      footerLink: "Sign up",
    },
    signup: {
      heading: "Join NEXHIBIT",
      studentTab: "I am a student",
      employerTab: "I am an employer",
      demoNoticeTitle: "Prototype preview",
      demoNoticeBody:
        "No personal data is needed for this demo. These fields stay visible to show the real workflow, but they are locked for the presentation.",
      demoFieldBadge: "Demo field locked",
      emailPlaceholder: "student@example.com",
      companyNamePlaceholder: "Company or organization name",
      companyWebsitePlaceholder: "https://company.com",
      studentButton: "Continue to verification",
      employerButton: "Submit for verification",
      studentDemoButton: "Open student demo flow",
      employerDemoButton: "Open employer demo portal",
      employerHelper:
        "Employer account review is simulated in this prototype. A future deployment would require a real Career Services verification workflow.",
      footerPrefix: "Already have an account?",
      footerLink: "Log in",
    },
    about: {
      heroCaption: "Our story",
      heroHeading: "International students deserve to be seen",
      heroBody:
        "NEXHIBIT grew from class research with international students who had strong projects, multilingual ability, and ambition, but few moments where employers expected to notice them. We built a reverse career fair concept so the first signal is the student's work, not their confidence in a crowded line.",
      problemHeading: "The gap is not talent. It is visibility",
      problemBody:
        "Traditional career fairs reward speed, local networks, and fluent self-pitching under pressure. International students often navigate language barriers, resume-only screening, and limited channels designed for their cross-border strengths.",
      problemStats: [
        "Research context: international students at ZJUT need clearer visibility channels",
        "Class interviews surfaced repeated frustration around crowded career fairs",
        "Prototype opportunity: a dedicated visibility layer for international talent",
      ],
      solutionHeading: "A fair built around discovery",
      solutionBody:
        "Students prepare profile booths with projects, languages, and availability. Employers arrive with context, scan the demo profile badge, and begin a conversation around evidence instead of guessing from a resume.",
      traditionalFlow: "Traditional flow",
      reverseFlow: "NEXHIBIT flow",
      resumeDrop: "resume drop",
      discoveryConversation: "discovery and conversation",
      teamHeading: "Team",
      teamMembers: [
        { name: "Product Research", role: "Student interviews, employer needs, and reverse-fair workflow", initials: "PR" },
        { name: "Experience Design", role: "Portal flows, visual system, and presentation-ready interaction polish", initials: "XD" },
        { name: "Data Validation", role: "Mock cohort quality, matching logic, and acceptance criteria", initials: "DV" },
        { name: "Demo Storytelling", role: "June 5 narrative, live demo path, and stakeholder handoff", initials: "DS" },
      ],
      builtWithHeading: "Built with",
      builtWithBody:
        "NEXHIBIT is a polished student prototype for Zhejiang University of Technology's international career development context, designed for a June 2026 reverse career fair demo.",
      facultyAdvisor: "ZJUT International College · Career Services concept",
      zjutLogo: "ZJUT",
    },
  },

  pricing: {
    hero: {
      eyebrow: "PRICING",
      headline: "Plans that scale with you.",
      subheadline:
        "Free for students who need it most. Paid tiers add extra reach, sharper signals, and smoother event-day hiring.",
    },
    toggle: {
      monthly: "Monthly",
      yearly: "Yearly",
      savings: "Save with annual billing",
      students: "Students",
      employers: "Employers",
      university: "Universities",
    },
    studentDiscount: {
      badge: "Student discount demo",
      description: "The prototype shows how a future ZJUT eligibility check could apply a 20% student discount.",
    },
    faq: [
      {
        question: "Can students use NEXHIBIT for free?",
        answer:
          "Yes. The Free plan keeps the core profile, event browsing, and a limited monthly application allowance available.",
      },
      {
        question: "Do payments really process in this demo?",
        answer:
          "No. This billing system is a simulation for product demonstration. It never charges money or calls a payment provider.",
      },
      {
        question: "Which China payment methods are supported?",
        answer:
          "The simulated checkout includes Alipay, WeChat Pay, UnionPay, cards, Apple Pay, and bank transfer for B2B accounts.",
      },
      {
        question: "How does the student discount work?",
        answer:
          "A real version would apply the discount after university verification. In this prototype, the UI shows the automatic discount rule.",
      },
      {
        question: "What is the difference between Pro and Max?",
        answer:
          "Pro focuses on priority booking and visibility. Max demonstrates coaching, portfolio review, priority review workflows, and expanded employer access.",
      },
      {
        question: "Can a subscription be canceled?",
        answer:
          "Yes. The demo cancellation flow shows retention, cancellation reasons, and period-end cancellation behavior.",
      },
    ],
    comparison: {
      title: "Compare student visibility tiers",
      subtitle: "Profile, visibility, communication, events, and support features side by side.",
    },
    ctaSection: {
      headline: "Still have questions? Talk to our team.",
      button: "Contact NEXHIBIT",
    },
  },

  billing: {
    sidebar: {
      overview: "Overview",
      history: "History",
      paymentMethods: "Payment Methods",
      invoices: "Invoices",
      cancel: "Cancel",
    },
    overview: {
      currentPlan: "Current plan",
      nextBilling: "Next billing",
      usageThisMonth: "Usage this month",
      manageSubscription: "Manage subscription",
    },
    history: {
      title: "Billing history",
      empty: "No transactions yet.",
      downloadReceipt: "Download receipt",
    },
    paymentMethods: {
      title: "Payment methods",
      addNew: "Add new method",
      default: "Default",
      remove: "Remove",
      expires: "Expires",
    },
    invoices: {
      title: "Invoices",
      requestFapiao: "Request Fapiao",
      downloadPdf: "Download PDF",
    },
    cancel: {
      title: "Cancel subscription",
      retentionOffer: "Keep your plan with 50% off the next 3 months.",
      confirmCancel: "Cancel anyway",
      keepSubscription: "Keep subscription",
      reasons: ["Too expensive", "Not using it", "Found an alternative", "Other"],
    },
    usage: {
      applications: "Applications",
      messages: "Messages",
      profileViews: "Profile views",
      boosts: "Profile boosts",
      unlimited: "Unlimited",
    },
  },

  payment: {
    checkout: {
      title: "Checkout",
      summary: "Order summary",
      total: "Total",
      securityNote: "Demo mode - no real charges. Payment states are simulated in the browser.",
      terms: "By continuing, you agree to the simulated billing terms for this prototype.",
    },
    methods: {
      choosePayment: "Choose payment method",
      scanQr: "Scan QR code",
      qrExpires: "Code expires in",
      enterCardDetails: "Enter card details",
      bankDetails: "Bank transfer details",
      recommended: "Recommended",
    },
    states: {
      processing: "Processing simulated payment",
      success: "Payment complete",
      failed: "Payment failed",
      retryPrompt: "Try another method or retry this simulated payment.",
    },
    alipay: {
      instructions: "Open Alipay and scan this code to complete the simulated payment.",
      openApp: "Open Alipay App",
      qrPrompt: "Waiting for Alipay scan...",
    },
    wechat: {
      instructions: "Open WeChat and scan this code to complete the simulated payment.",
      openApp: "Open WeChat App",
      qrPrompt: "Waiting for WeChat scan...",
    },
    card: {
      number: "Card number",
      expiry: "Expiry",
      cvv: "CVV",
      cardholderName: "Cardholder name",
      saveCard: "Save card for future billing",
    },
    bankTransfer: {
      instructions: "Use the details below for a simulated bank transfer. No money should be sent.",
      accountName: "NEXHIBIT Technology (Hangzhou) Co., Ltd.",
      accountNumber: "6225 XXXX XXXX 1234",
      bankName: "China Merchants Bank",
      swiftCode: "CMBCCNBS",
      reference: "Reference",
      markAsPaid: "I've sent the transfer",
    },
    applePay: {
      instructions: "Confirm with the simulated Apple Pay sheet.",
      useTouchId: "Use Touch ID",
      useFaceId: "Authenticate with Face ID...",
    },
    receipt: {
      thankYou: "Thank you for upgrading.",
      viewReceipt: "View receipt",
      accessNow: "Access now",
      emailedTo: "A simulated receipt has been prepared for your account email.",
    },
  },

  forms: {
    labels: {
      fullName: "Full name",
      studentId: "ZJUT student ID",
      passportNumber: "Passport number",
      email: "Email address",
      password: "Password",
      nationality: "Nationality",
      major: "Major",
      year: "Year of study",
      gpa: "GPA",
      hsk: "HSK level",
      englishLevel: "English level",
      headline: "Professional headline",
      bio: "Short bio",
      skills: "Skills",
      projectTitle: "Project title",
      projectDescription: "Project description",
      availability: "Available from",
      preferredLocations: "Preferred locations",
      companyName: "Company name",
      companyWebsite: "Company website",
      hiringCategories: "Hiring categories",
      message: "Message",
    },
    placeholders: {
      fullName: "Your name as employers should see it",
      headline: "Data analyst focused on China-Southeast Asia commerce",
      bio: "Share what you build, what you care about, and where you want to grow.",
      skills: "Python, market research, Mandarin HSK 4",
      projectTitle: "Campus Navigator for International Students",
      projectDescription: "Describe the problem, your role, and the result in two clear sentences.",
      availability: "June 2026",
      preferredLocations: "Hangzhou, Shanghai, Remote",
      companySearch: "Search by company, industry, or hiring skill",
      studentSearch: "Search students by skill, major, language, or country",
      messageStudent: "Tell the student what caught your attention and what role you have in mind.",
      messageEmployer: "Reply with your availability, questions, and any project link they should review.",
    },
    validationMessages: {
      fullName: "Enter the name you want employers to use.",
      studentId: "Enter your ZJUT student ID.",
      passportNumber: "Enter the passport number shown in the demo verification scenario.",
      headline: "Write a one-line headline so employers can place you quickly.",
      bio: "Write one or two sentences in your own voice.",
      skills: "Add at least four skills that match your current work.",
      projects: "Add at least two projects before publishing.",
      companyName: "Enter your registered company or organization name.",
      website: "Enter a valid company website so students can verify you too.",
      message: "Write a short, specific message before sending.",
    },
  },

  auth: {
    studentWelcome: "Open the demo flow. Get discovered throughout the event cycle",
    employerWelcome: "Create a demo employer account to browse prototype ZJUT international talent.",
    forgotPassword: "Reset your password",
    passwordResetSent: "Demo reset action noted. No email is sent from this prototype.",
    newToNexhibit: "New to NEXHIBIT?",
    alreadyRegistered: "Already have an account?",
  },

  dashboard: {
    student: {
      greeting: "Your profile is your booth before the fair opens.",
      nextSteps: "Recommended next steps",
      profileStrength: "Profile strength",
      employerViews: "Employer profile views",
      unreadMessages: "Unread employer messages",
      upcomingBooth: "Upcoming booth",
    },
    employer: {
      greeting: "Your shortlist is ready when the event doors open.",
      recommendedStudents: "Recommended students",
      savedProfiles: "Saved profiles",
      bookedSlots: "Booked event slots",
      teamActivity: "Team activity",
    },
  },

  events: {
    card: {
      slotsBooked: "slots booked",
      employersRegistered: "employers registered",
      satisfaction: "student satisfaction",
      matchesGenerated: "matches generated",
    },
    details: {
      checkIn: "Bring your student ID and QR badge for check-in.",
      boothSetup: "Arrive 30 minutes early to set up your booth materials.",
      employerAccess: "Employer teams can browse published profiles before the event.",
      followUp: "After the event, message students while the conversation is still fresh.",
    },
  },

  messaging: {
    composerHint: "Specific messages get better replies. Mention the project or role you want to discuss.",
    studentReplyHint: "Share your availability and link the project that best answers their question.",
    employerReplyHint: "Give the student a clear next step, timeline, or interview window.",
    unreadLabel: "Unread",
  },

  legal: {
    privacyShort:
      "This prototype demonstrates student-controlled visibility. A real deployment would need formal PIPL review and consent records.",
    verificationUse:
      "ZJUT verification details are represented as mock fields here. Passport numbers are never processed in this prototype.",
    employerCode:
      "Employers agree to use NEXHIBIT for legitimate hiring, internships, and career conversations only.",
    studentConsent:
      "Publishing your prototype profile makes selected fields visible to reviewed demo employer accounts.",
    dataRetention:
      "Event and message records are mock data in this prototype. A real deployment would require retention rules and audit logs.",
  },

  accessibility: {
    openMenu: "Open navigation menu",
    closeMenu: "Close navigation menu",
    previousSlide: "Show previous slide",
    nextSlide: "Show next slide",
    scanQr: "Scan profile QR code",
    removeFilter: "Remove filter",
    expandSection: "Expand section",
    collapseSection: "Collapse section",
  },
} as const;

export type Copy = typeof copy;
