import type { Employer } from "./types";

export const employers: Employer[] = [
  {
    id: "emp-001",
    name: "Alibaba Cloud",
    logoLetter: "AC",
    logoColor: "#FF6A00",
    industry: "Cloud Computing and AI Infrastructure",
    size: "Enterprise (5000+)",
    location: "Hangzhou",
    description: "Alibaba Cloud supports enterprise cloud, data intelligence, and AI services across global markets. Its international teams often need technical talent who can work across languages and customer contexts.",
    hiringCategories: ["Engineering", "Business", "Language"],
    hiringSkills: ["Cloud Computing", "Python", "Data Analytics", "Solution Consulting", "Mandarin", "Localization"],
    verified: true,
    type: "Chinese",
    yearFounded: 2009,
    website: "https://www.alibabacloud.com",
    activeSince: "March 2025",
  },
  {
    id: "emp-002",
    name: "BYD International",
    logoLetter: "BY",
    logoColor: "#D71920",
    industry: "Electric Vehicles and New Energy",
    size: "Enterprise (5000+)",
    location: "Shenzhen",
    description: "BYD International works on electric vehicle, battery, and mobility expansion in overseas markets. The company values multilingual graduates who understand both engineering details and local market expectations.",
    hiringCategories: ["Engineering", "Business", "Language"],
    hiringSkills: ["Electrical Engineering", "Market Research", "Supply Chain", "Technical Documentation", "English", "Regional Localization"],
    verified: true,
    type: "Chinese",
    yearFounded: 1995,
    website: "https://www.bydglobal.com",
    activeSince: "April 2025",
  },
  {
    id: "emp-003",
    name: "SHEIN Global",
    logoLetter: "S",
    logoColor: "#111827",
    industry: "Fashion E-commerce",
    size: "Enterprise (5000+)",
    location: "Guangzhou",
    description: "SHEIN Global operates cross-border fashion e-commerce across fast-moving consumer markets. Teams look for students who understand social commerce, localization, product content, and regional customer behavior.",
    hiringCategories: ["Business", "Language", "Other"],
    hiringSkills: ["E-commerce Operations", "Content Localization", "Consumer Research", "Excel", "Social Commerce", "Copywriting"],
    verified: true,
    type: "Chinese",
    yearFounded: 2008,
    website: "https://www.sheingroup.com",
    activeSince: "May 2025",
  },
  {
    id: "emp-004",
    name: "Bosch China",
    logoLetter: "B",
    logoColor: "#E20015",
    industry: "Mobility Technology and Industrial Solutions",
    size: "Enterprise (5000+)",
    location: "Suzhou",
    description: "Bosch China develops mobility, manufacturing, and smart technology solutions with teams across several Chinese cities. International students can support engineering, operations, and customer-facing technical roles.",
    hiringCategories: ["Engineering", "Business"],
    hiringSkills: ["Mechatronics", "Automation", "Process Improvement", "Quality Analysis", "Technical English", "Supplier Coordination"],
    verified: true,
    type: "Multinational",
    yearFounded: 1909,
    website: "https://www.bosch.com.cn",
    activeSince: "June 2025",
  },
  {
    id: "emp-005",
    name: "Siemens China",
    logoLetter: "S",
    logoColor: "#009999",
    industry: "Industrial Automation and Smart Infrastructure",
    size: "Enterprise (5000+)",
    location: "Shanghai",
    description: "Siemens China focuses on industrial automation, digital industries, smart infrastructure, and healthcare technology. Its campus hiring emphasizes structured problem solving and strong communication across technical teams.",
    hiringCategories: ["Engineering", "Health", "Business"],
    hiringSkills: ["Industrial Automation", "Data Analysis", "Technical Presentations", "Project Coordination", "Regulatory Research", "Mandarin"],
    verified: true,
    type: "Multinational",
    yearFounded: 1872,
    website: "https://www.siemens.com/cn",
    activeSince: "February 2025",
  },
  {
    id: "emp-006",
    name: "Lingxi AI",
    logoLetter: "LX",
    logoColor: "#6D5DFB",
    industry: "AI Customer Support Tools",
    size: "Startup (1-50)",
    location: "Hangzhou",
    description: "Lingxi AI builds multilingual customer support assistants for exporters and cross-border sellers. The startup needs students who can test language quality, annotate conversations, and explain product issues clearly.",
    hiringCategories: ["Engineering", "Language", "Business"],
    hiringSkills: ["NLP", "Prompt Testing", "Python", "Localization QA", "Customer Research", "Mandarin"],
    verified: true,
    type: "Startup",
    yearFounded: 2023,
    website: "https://lingxi-ai.example.com",
    activeSince: "September 2025",
  },
  {
    id: "emp-007",
    name: "Cathay Robotics",
    logoLetter: "CR",
    logoColor: "#2563EB",
    industry: "Warehouse Robotics",
    size: "Mid-size (51-500)",
    location: "Ningbo",
    description: "Cathay Robotics designs warehouse automation systems for manufacturers and exporters in the Yangtze River Delta. The company recruits hands-on engineering students with documentation and field testing discipline.",
    hiringCategories: ["Engineering", "Business"],
    hiringSkills: ["Robotics", "PLC Basics", "SolidWorks", "Operations Research", "Technical Documentation", "Supplier Coordination"],
    verified: true,
    type: "Startup",
    yearFounded: 2021,
    website: "https://cathayrobotics.example.com",
    activeSince: "October 2025",
  },
  {
    id: "emp-008",
    name: "Tencent Global",
    logoLetter: "TG",
    logoColor: "#1E88E5",
    industry: "Internet Services and Digital Entertainment",
    size: "Enterprise (5000+)",
    location: "Shenzhen",
    description: "Tencent Global supports international products in gaming, cloud, fintech, and social platforms. Teams value international students who can combine product thinking with regional language and user insight.",
    hiringCategories: ["Engineering", "Business", "Language", "Other"],
    hiringSkills: ["Product Research", "TypeScript", "Data Analysis", "UX Writing", "Localization", "Community Operations"],
    verified: true,
    type: "Chinese",
    yearFounded: 1998,
    website: "https://www.tencent.com",
    activeSince: "January 2025",
  },
];
