import type { Event } from "./types";

export const events: Event[] = [
  {
    id: "evt-001",
    slug: "spring-career-fair-2026-june-15",
    title: "Spring Career Fair 2026",
    cycle: "Spring",
    year: 2026,
    date: "June 15, 2026",
    isoDate: "2026-06-15",
    status: "upcoming",
    location: "ZJUT International College Hall, Hangzhou",
    description: "A reverse career fair where verified international students present project portfolios and employers browse by category, language ability, and availability.",
    categories: [
      { name: "Engineering", slotsTotal: 24, slotsBooked: 18 },
      { name: "Business", slotsTotal: 20, slotsBooked: 14 },
      { name: "Health", slotsTotal: 12, slotsBooked: 7 },
      { name: "Language", slotsTotal: 14, slotsBooked: 10 },
      { name: "Other", slotsTotal: 10, slotsBooked: 6 },
    ],
    totalSlots: 80,
    bookedSlots: 55,
    registeredEmployers: 22,
  },
  {
    id: "evt-002",
    slug: "fall-career-fair-2026-october-20",
    title: "Fall Career Fair 2026",
    cycle: "Fall",
    year: 2026,
    date: "October 20, 2026",
    isoDate: "2026-10-20",
    status: "upcoming",
    location: "ZJUT Pingfeng Campus Innovation Center, Hangzhou",
    description: "The fall showcase focuses on final-year hiring, internship conversion, and cross-border roles connected to Zhejiang companies expanding internationally.",
    categories: [
      { name: "Engineering", slotsTotal: 24, slotsBooked: 9 },
      { name: "Business", slotsTotal: 20, slotsBooked: 8 },
      { name: "Health", slotsTotal: 12, slotsBooked: 4 },
      { name: "Language", slotsTotal: 14, slotsBooked: 6 },
      { name: "Other", slotsTotal: 10, slotsBooked: 3 },
    ],
    totalSlots: 80,
    bookedSlots: 30,
    registeredEmployers: 16,
  },
  {
    id: "evt-003",
    slug: "spring-career-fair-2026-april-18",
    title: "Spring Career Fair 2026 — Session I",
    cycle: "Spring",
    year: 2026,
    date: "April 18, 2026",
    isoDate: "2026-04-18",
    status: "past",
    location: "ZJUT International College Hall, Hangzhou",
    description: "The first 2026 spring session tested portfolio-first matching, scheduled employer walks, and short student presentation blocks.",
    categories: [
      { name: "Engineering", slotsTotal: 24, slotsBooked: 24 },
      { name: "Business", slotsTotal: 20, slotsBooked: 19 },
      { name: "Health", slotsTotal: 12, slotsBooked: 10 },
      { name: "Language", slotsTotal: 14, slotsBooked: 13 },
      { name: "Other", slotsTotal: 10, slotsBooked: 8 },
    ],
    totalSlots: 80,
    bookedSlots: 74,
    registeredEmployers: 29,
    satisfactionScore: 4.6,
    matchesGenerated: 38,
  },
  {
    id: "evt-004",
    slug: "fall-career-fair-2025-november-12",
    title: "Fall Career Fair 2025",
    cycle: "Fall",
    year: 2025,
    date: "November 12, 2025",
    isoDate: "2025-11-12",
    status: "past",
    location: "ZJUT Pingfeng Campus Library Forum Space, Hangzhou",
    description: "A pilot reverse fair that introduced verified student profiles, category zones, and employer follow-up cards after each portfolio conversation.",
    categories: [
      { name: "Engineering", slotsTotal: 24, slotsBooked: 22 },
      { name: "Business", slotsTotal: 20, slotsBooked: 18 },
      { name: "Health", slotsTotal: 12, slotsBooked: 9 },
      { name: "Language", slotsTotal: 14, slotsBooked: 12 },
      { name: "Other", slotsTotal: 10, slotsBooked: 7 },
    ],
    totalSlots: 80,
    bookedSlots: 68,
    registeredEmployers: 24,
    satisfactionScore: 4.4,
    matchesGenerated: 31,
  },
];
