import type {
  AlumniMentor,
  CompanyInsight,
  CommunityQuestion,
  ResumeReviewRequest,
} from "@/types/network";

export const networkMentors: AlumniMentor[] = [
  {
    id: "mentor-1",
    firstName: "Arjun",
    initials: "AS",
    nationality: "Indian",
    nationalityFlag: "🇮🇳",
    graduationYear: 2022,
    major: "Computer Science and Technology",
    currentCompany: "ByteDance",
    currentPosition: "Software Engineer",
    location: "Beijing, China",
    languages: ["English", "Hindi", "Mandarin (HSK 4)"],
    specialties: ["Backend Development", "Data Pipelines", "Chinese Tech Culture"],
    industry: "Technology",
    companyType: "Chinese firm",
    availability: "Available",
    sessionFormat: "Both",
    responseTime: "Usually responds within 1-2 days",
    bio: [
      "I graduated from ZJUT in 2022 with a degree in Computer Science. Moving from Pune to Hangzhou was a cultural leap, but ZJUT gave me the technical foundation and the network to land a role at ByteDance.",
      "At ByteDance I work on backend data infrastructure. The Chinese tech environment moves fast — I can help you understand what that really means for your day-to-day life and career.",
      "I am happy to review resumes, do mock interviews in English or Hindi, and share honest advice about life as an international hire at a Chinese firm.",
    ],
    careerTimeline: [
      { year: 2022, role: "Junior Software Engineer", company: "NetEase (Internship)" },
      { year: 2022, role: "Software Engineer", company: "ByteDance" },
      { year: 2024, role: "Senior Software Engineer", company: "ByteDance" },
    ],
    helpAreas: [
      "Resume review for Chinese tech firms",
      "Technical interview preparation",
      "Relocating to Beijing",
      "Work visa and permit process",
      "Mandarin in the workplace",
    ],
    reviews: [
      {
        quote: "Arjun gave me a thorough resume review and pointed out two sections that Chinese HR would skip. I got an interview within a week of making changes.",
        menteeLabel: "Indian CS student, Class of 2024",
      },
      {
        quote: "Very honest about what working at ByteDance is really like. No sugarcoating.",
        menteeLabel: "Pakistani student, Class of 2023",
      },
    ],
  },
  {
    id: "mentor-2",
    firstName: "Nadia",
    initials: "NK",
    nationality: "Russian",
    nationalityFlag: "🇷🇺",
    graduationYear: 2021,
    major: "International Economics and Trade",
    currentCompany: "Huawei",
    currentPosition: "Business Development Manager",
    location: "Shenzhen, China",
    languages: ["Russian", "English", "Mandarin (HSK 5)"],
    specialties: ["B2B Sales", "Cross-border Trade", "Russian Market Entry"],
    industry: "Telecommunications",
    companyType: "Chinese firm",
    availability: "Limited",
    sessionFormat: "Async messages",
    responseTime: "Usually responds within 3-4 days",
    bio: [
      "I came to ZJUT from Moscow in 2017 and stayed in China after graduating — something I never expected. The job market for international graduates in China is real, but you have to know how to navigate it.",
      "At Huawei I bridge the China-Russia business corridor. My role is rare, and it happened because I was intentional about combining my Russian background with fluent Mandarin.",
      "I can help students from Eurasia think about how to position their home-country advantage in the Chinese job market.",
    ],
    careerTimeline: [
      { year: 2020, role: "Trade Analyst Intern", company: "Alibaba International" },
      { year: 2021, role: "Account Manager", company: "Huawei" },
      { year: 2023, role: "Business Development Manager", company: "Huawei" },
    ],
    helpAreas: [
      "Positioning European background in China",
      "Mandarin business communication",
      "Huawei application process",
      "Work-life balance at Chinese firms",
      "Long-term visa strategy",
    ],
    reviews: [
      {
        quote: "She told me exactly which Huawei teams hire internationals and what they look for. Invaluable.",
        menteeLabel: "Uzbek student, Class of 2023",
      },
    ],
  },
  {
    id: "mentor-3",
    firstName: "Amara",
    initials: "AO",
    nationality: "Nigerian",
    nationalityFlag: "🇳🇬",
    graduationYear: 2020,
    major: "Mechanical Engineering",
    currentCompany: "Bosch",
    currentPosition: "Product Engineer",
    location: "Shanghai, China",
    languages: ["English", "Yoruba", "Mandarin (HSK 3)"],
    specialties: ["Manufacturing", "Product Development", "MNC Culture"],
    industry: "Manufacturing & Engineering",
    companyType: "MNC",
    availability: "Available",
    sessionFormat: "Video call",
    responseTime: "Usually responds within 2 days",
    bio: [
      "Engineering at ZJUT was intense but prepared me well. I joined Bosch Shanghai after a competitive internship — one of two international hires in my cohort.",
      "Working at an MNC in China is different from a Chinese firm. The culture, expectations, and career paths are distinct. I can help you understand which suits you.",
      "I am passionate about helping African students navigate the China job market, where we are underrepresented but very welcome.",
    ],
    careerTimeline: [
      { year: 2020, role: "Manufacturing Intern", company: "Siemens Hangzhou" },
      { year: 2020, role: "Junior Product Engineer", company: "Bosch Shanghai" },
      { year: 2023, role: "Product Engineer", company: "Bosch Shanghai" },
    ],
    helpAreas: [
      "Engineering roles in China",
      "MNC vs Chinese firm decision",
      "African student networking in China",
      "Shanghai cost of living and logistics",
      "Technical interview prep in English",
    ],
    reviews: [
      {
        quote: "Amara walked me through the entire Bosch interview process. I knew exactly what to expect.",
        menteeLabel: "Kenyan student, Class of 2024",
      },
      {
        quote: "Genuine and encouraging. She helped me see my ZJUT degree as a strength, not a question mark.",
        menteeLabel: "Nigerian student, Class of 2023",
      },
    ],
  },
  {
    id: "mentor-4",
    firstName: "Thanh",
    initials: "TN",
    nationality: "Vietnamese",
    nationalityFlag: "🇻🇳",
    graduationYear: 2023,
    major: "Software Engineering",
    currentCompany: "Meituan",
    currentPosition: "Frontend Engineer",
    location: "Beijing, China",
    languages: ["Vietnamese", "English", "Mandarin (HSK 4)"],
    specialties: ["Frontend Development", "React", "Chinese Product Culture"],
    industry: "Technology",
    companyType: "Chinese firm",
    availability: "Available",
    sessionFormat: "Both",
    responseTime: "Usually responds within 1-2 days",
    bio: [
      "I graduated last year so the ZJUT experience is fresh. I went straight from graduation to Meituan's frontend team — it was a fast and competitive process.",
      "Chinese product companies move extremely fast and expect you to ship quickly. I can prepare you for that pace and culture.",
      "I am especially able to help students from Southeast Asia who share similar cultural backgrounds and language learning challenges.",
    ],
    careerTimeline: [
      { year: 2022, role: "Frontend Intern", company: "Meituan" },
      { year: 2023, role: "Frontend Engineer", company: "Meituan" },
    ],
    helpAreas: [
      "Frontend technical interview prep",
      "Chinese product company culture",
      "SE Asia students in China tech",
      "Staying in China post-graduation",
      "Mandarin for tech roles",
    ],
    reviews: [
      {
        quote: "He reviewed my portfolio and helped me reframe projects for Chinese HR. Very practical advice.",
        menteeLabel: "Indonesian student, Class of 2024",
      },
    ],
  },
  {
    id: "mentor-5",
    firstName: "Fatima",
    initials: "FR",
    nationality: "Pakistani",
    nationalityFlag: "🇵🇰",
    graduationYear: 2021,
    major: "Business Administration",
    currentCompany: "HSBC China",
    currentPosition: "Relationship Manager",
    location: "Shanghai, China",
    languages: ["Urdu", "English", "Mandarin (HSK 5)", "Arabic"],
    specialties: ["Banking", "Client Management", "Cross-cultural Communication"],
    industry: "Finance",
    companyType: "MNC",
    availability: "Limited",
    sessionFormat: "Video call",
    responseTime: "Usually responds within 2-3 days",
    bio: [
      "I chose ZJUT for its proximity to China's business ecosystem. That bet paid off — I now work in one of Shanghai's most international banking teams.",
      "Finance in China has unique dynamics, especially for internationals. Knowing how to present yourself to both Chinese and Western stakeholders is a skill I developed over years.",
      "I especially enjoy mentoring female students from South Asia who face additional barriers and need someone who understands both the culture and the bias.",
    ],
    careerTimeline: [
      { year: 2020, role: "Banking Intern", company: "Bank of China (International)" },
      { year: 2021, role: "Graduate Associate", company: "HSBC China" },
      { year: 2023, role: "Relationship Manager", company: "HSBC China" },
    ],
    helpAreas: [
      "Finance career in China",
      "Banking interview preparation",
      "Female international student support",
      "Shanghai life and community",
      "Balancing cultural identity at work",
    ],
    reviews: [
      {
        quote: "Fatima understood my situation immediately and gave me advice I could not have found online.",
        menteeLabel: "Pakistani female student, Class of 2023",
      },
      {
        quote: "She helped me prepare for HSBC competency interviews. Got the offer.",
        menteeLabel: "Bangladeshi student, Class of 2022",
      },
    ],
  },
  {
    id: "mentor-6",
    firstName: "Dmitri",
    initials: "DV",
    nationality: "Russian",
    nationalityFlag: "🇷🇺",
    graduationYear: 2019,
    major: "Electrical Engineering",
    currentCompany: "CATL",
    currentPosition: "Battery Systems Engineer",
    location: "Ningbo, China",
    languages: ["Russian", "English", "Mandarin (HSK 5)"],
    specialties: ["EV Technology", "Battery Engineering", "Chinese Manufacturing"],
    industry: "Energy & EV",
    companyType: "Chinese firm",
    availability: "Busy",
    sessionFormat: "Async messages",
    responseTime: "Usually responds within 5-7 days",
    bio: [
      "I have been in China since 2015 and at CATL since 2019. The EV boom happened around me and it is an exciting time to be in this industry.",
      "CATL is one of the best places to work in China if you are an engineer. The technical level is world-class and the international team is growing.",
      "I respond slowly due to project schedules, but my answers are thorough. Best for async questions about engineering careers, CATL culture, and Ningbo life.",
    ],
    careerTimeline: [
      { year: 2019, role: "R&D Engineer", company: "CATL" },
      { year: 2021, role: "Senior Engineer", company: "CATL" },
      { year: 2023, role: "Battery Systems Engineer", company: "CATL" },
    ],
    helpAreas: [
      "EV and energy sector careers",
      "CATL application process",
      "Engineering Mandarin vocabulary",
      "Long-term life in smaller Chinese cities",
      "Russian-Chinese professional community",
    ],
    reviews: [
      {
        quote: "Even with his busy schedule, his written advice was the most detailed I received from any mentor.",
        menteeLabel: "Russian student, Class of 2022",
      },
    ],
  },
  {
    id: "mentor-7",
    firstName: "Siti",
    initials: "SA",
    nationality: "Indonesian",
    nationalityFlag: "🇮🇩",
    graduationYear: 2022,
    major: "Chemical Engineering",
    currentCompany: "Sinopec",
    currentPosition: "Process Engineer",
    location: "Hangzhou, China",
    languages: ["Indonesian", "English", "Mandarin (HSK 4)", "Malay"],
    specialties: ["Chemical Process", "Environmental Compliance", "SOE Culture"],
    industry: "Energy & Chemicals",
    companyType: "Chinese firm",
    availability: "Available",
    sessionFormat: "Both",
    responseTime: "Usually responds within 2 days",
    bio: [
      "As an Indonesian Muslim student in Hangzhou, I navigated both the academic and cultural challenges that many of you are facing. I stayed and joined Sinopec.",
      "Working at a State-Owned Enterprise is a very specific experience — stable, structured, and slower-paced than private firms. It suits me well and I can help you decide if it suits you.",
      "I am also happy to connect international students with the Hangzhou Muslim community and give practical tips on daily life here.",
    ],
    careerTimeline: [
      { year: 2021, role: "Engineering Intern", company: "Sinopec Zhejiang" },
      { year: 2022, role: "Process Engineer", company: "Sinopec" },
    ],
    helpAreas: [
      "State-owned enterprise culture",
      "Chemical engineering careers",
      "Muslim life in Hangzhou",
      "Indonesian student community",
      "Work permit for SOE roles",
    ],
    reviews: [
      {
        quote: "Siti gave me an honest picture of SOE life. I decided it was right for me and she helped me prepare.",
        menteeLabel: "Indonesian student, Class of 2024",
      },
    ],
  },
  {
    id: "mentor-8",
    firstName: "Kwame",
    initials: "KB",
    nationality: "Kenyan",
    nationalityFlag: "🇰🇪",
    graduationYear: 2020,
    major: "Information Management",
    currentCompany: "Ant Group",
    currentPosition: "Data Analyst",
    location: "Hangzhou, China",
    languages: ["English", "Swahili", "Mandarin (HSK 4)"],
    specialties: ["Data Analysis", "Fintech", "SQL", "Python"],
    industry: "Fintech",
    companyType: "Chinese firm",
    availability: "Available",
    sessionFormat: "Video call",
    responseTime: "Usually responds within 2 days",
    bio: [
      "I grew up in Nairobi dreaming of working in tech. Ant Group in Hangzhou was not in that dream, but here I am and it has been an incredible ride.",
      "Fintech in China is years ahead of much of the world. If you want to be at the frontier of financial technology, China is genuinely the right place.",
      "I love helping African students especially. We are few in number but our perspective is valuable here and companies are increasingly aware of that.",
    ],
    careerTimeline: [
      { year: 2019, role: "Data Intern", company: "Alibaba" },
      { year: 2020, role: "Junior Data Analyst", company: "Ant Group" },
      { year: 2023, role: "Data Analyst", company: "Ant Group" },
    ],
    helpAreas: [
      "Data roles at Chinese tech firms",
      "SQL and Python interview prep",
      "African students in China tech",
      "Hangzhou expat life",
      "Fintech industry overview",
    ],
    reviews: [
      {
        quote: "Kwame did a mock technical interview with me over video call. His feedback was detailed and accurate — I passed the real one.",
        menteeLabel: "Nigerian student, Class of 2024",
      },
    ],
  },
  {
    id: "mentor-9",
    firstName: "Lucas",
    initials: "LC",
    nationality: "Brazilian",
    nationalityFlag: "🇧🇷",
    graduationYear: 2021,
    major: "Industrial Design",
    currentCompany: "DJI",
    currentPosition: "Product Designer",
    location: "Shenzhen, China",
    languages: ["Portuguese", "English", "Spanish", "Mandarin (HSK 3)"],
    specialties: ["Industrial Design", "Consumer Electronics", "Design Process"],
    industry: "Consumer Electronics",
    companyType: "Chinese firm",
    availability: "Limited",
    sessionFormat: "Both",
    responseTime: "Usually responds within 3-4 days",
    bio: [
      "Brazil to Shenzhen — probably not a path anyone expected. But Shenzhen is the hardware capital of the world and DJI is at the top of it.",
      "Design at a Chinese hardware company is intense and collaborative. Your portfolio needs to tell a specific story to get noticed here.",
      "I can help designers understand the China hardware ecosystem and how to position creative work for Chinese-market roles.",
    ],
    careerTimeline: [
      { year: 2021, role: "Design Intern", company: "DJI" },
      { year: 2021, role: "Product Designer", company: "DJI" },
      { year: 2024, role: "Senior Product Designer", company: "DJI" },
    ],
    helpAreas: [
      "Design portfolio review",
      "Hardware company culture",
      "Shenzhen maker ecosystem",
      "Latin American students in China",
      "Creative career paths in China",
    ],
    reviews: [
      {
        quote: "Lucas reviewed my portfolio and completely reframed how I presented it. Got interviews at two hardware companies.",
        menteeLabel: "Brazilian student, Class of 2023",
      },
    ],
  },
  {
    id: "mentor-10",
    firstName: "Zulfiya",
    initials: "ZK",
    nationality: "Uzbek",
    nationalityFlag: "🇺🇿",
    graduationYear: 2023,
    major: "Finance",
    currentCompany: "Ctrip (Trip.com)",
    currentPosition: "Financial Analyst",
    location: "Shanghai, China",
    languages: ["Uzbek", "Russian", "English", "Mandarin (HSK 4)"],
    specialties: ["Financial Modeling", "Travel Industry", "Excel", "CPA prep"],
    industry: "Travel & E-commerce",
    companyType: "Chinese firm",
    availability: "Available",
    sessionFormat: "Async messages",
    responseTime: "Usually responds within 2-3 days",
    bio: [
      "I came to ZJUT on a CSC scholarship and turned it into a career in Shanghai. The transition from Tashkent to China was smoother than expected, thanks to the cultural proximity.",
      "Finance roles in Chinese internet companies are different from banking. Faster, more data-driven, and closer to product decisions.",
      "I am particularly helpful for Central Asian students navigating the Chinese job market and understanding post-graduation visa options.",
    ],
    careerTimeline: [
      { year: 2022, role: "Finance Intern", company: "Ctrip" },
      { year: 2023, role: "Financial Analyst", company: "Ctrip" },
    ],
    helpAreas: [
      "Finance roles in Chinese internet firms",
      "CSC scholarship to career path",
      "Central Asian students in China",
      "Shanghai finance community",
      "Post-graduation work visa",
    ],
    reviews: [
      {
        quote: "She explained the Ctrip interview process step by step. Very detailed and warm.",
        menteeLabel: "Uzbek student, Class of 2024",
      },
    ],
  },
  {
    id: "mentor-11",
    firstName: "Priya",
    initials: "PM",
    nationality: "Indian",
    nationalityFlag: "🇮🇳",
    graduationYear: 2020,
    major: "Biomedical Engineering",
    currentCompany: "Mindray",
    currentPosition: "Application Specialist",
    location: "Shenzhen, China",
    languages: ["Tamil", "English", "Hindi", "Mandarin (HSK 4)"],
    specialties: ["Medical Devices", "Clinical Applications", "Technical Sales"],
    industry: "Medical Devices & Healthcare",
    companyType: "Chinese firm",
    availability: "Available",
    sessionFormat: "Video call",
    responseTime: "Usually responds within 2 days",
    bio: [
      "Biomedical Engineering from ZJUT opened doors I did not expect. China is a world leader in medical device manufacturing and companies like Mindray are global players.",
      "I help clients across Asia understand how to use our devices clinically. It is a technical and communicative role that suits my background perfectly.",
      "I mentor students interested in healthcare and medtech — a path not many internationals consider but genuinely rewarding.",
    ],
    careerTimeline: [
      { year: 2020, role: "R&D Intern", company: "Mindray" },
      { year: 2020, role: "Application Engineer", company: "Mindray" },
      { year: 2023, role: "Application Specialist", company: "Mindray" },
    ],
    helpAreas: [
      "Medical device industry careers",
      "Technical-commercial hybrid roles",
      "South Indian students in China",
      "Shenzhen expat community",
      "English-language roles at Chinese firms",
    ],
    reviews: [
      {
        quote: "Priya helped me understand that medtech is a real career option here. Changed my job search entirely.",
        menteeLabel: "Indian student, Class of 2024",
      },
    ],
  },
  {
    id: "mentor-12",
    firstName: "Enkhjargal",
    initials: "EB",
    nationality: "Mongolian",
    nationalityFlag: "🇲🇳",
    graduationYear: 2019,
    major: "Civil Engineering",
    currentCompany: "CCCC (China Communications Construction)",
    currentPosition: "Site Project Manager",
    location: "Chengdu, China",
    languages: ["Mongolian", "Russian", "English", "Mandarin (HSK 5)"],
    specialties: ["Infrastructure Projects", "Project Management", "BRI Projects"],
    industry: "Construction & Infrastructure",
    companyType: "Chinese firm",
    availability: "Limited",
    sessionFormat: "Async messages",
    responseTime: "Usually responds within 3-5 days",
    bio: [
      "I have been in the Chinese construction sector since graduation. CCCC is one of the largest infrastructure companies in the world and I have worked on projects in three countries.",
      "Civil engineering graduates from ZJUT are well-regarded at Chinese SOEs and construction firms. The path is structured and the compensation is competitive.",
      "I can help students understand infrastructure and BRI-related careers — one of the most international-friendly sectors in China.",
    ],
    careerTimeline: [
      { year: 2019, role: "Site Engineer", company: "CCCC" },
      { year: 2021, role: "Project Engineer", company: "CCCC" },
      { year: 2023, role: "Site Project Manager", company: "CCCC" },
    ],
    helpAreas: [
      "Civil and infrastructure careers",
      "BRI project opportunities",
      "Working at large Chinese SOEs",
      "Mongolian student community in China",
      "Long-term career planning in construction",
    ],
    reviews: [
      {
        quote: "He knew exactly what CCCC recruiters want to see and helped me tailor my resume accordingly.",
        menteeLabel: "Mongolian student, Class of 2023",
      },
    ],
  },
];

export const companyInsights: CompanyInsight[] = [
  {
    id: "company-bytedance",
    name: "ByteDance",
    logoLetter: "B",
    logoColor: "bg-aurora-blue/10 text-aurora-blue",
    industry: "Technology",
    locations: ["Beijing", "Shanghai", "Shenzhen"],
    alumniCount: 4,
    ratings: {
      internationalFriendliness: 4,
      workLifeBalance: 2,
      careerGrowth: 5,
      compensationTransparency: 4,
    },
    testimonials: [
      {
        quote: "The pace is relentless but the learning curve is steep in a good way. My Mandarin improved faster here than anywhere.",
        authorLabel: "Indian software engineer",
        context: "Joined 2022",
      },
      {
        quote: "International teams exist but you need Mandarin for most real collaboration. Invest in language first.",
        authorLabel: "Vietnamese frontend engineer",
        context: "Joined 2023",
      },
    ],
    applicationTips: [
      "Apply via the ByteDance campus recruitment portal in September-October for the following year.",
      "Technical rounds are algorithmic — LeetCode medium to hard difficulty.",
      "Prepare a brief self-introduction in Mandarin even for English-track roles.",
      "Referrals from current employees significantly increase your callback rate.",
    ],
    interviewQuestions: [
      "Describe a time you resolved a conflict with a colleague from a different cultural background.",
      "Walk me through your most complex technical project from start to deployment.",
      "How do you stay productive under strict deadlines?",
      "What do you know about ByteDance's global product strategy?",
    ],
    languageExpectation: "English-track roles exist in international product teams, but Mandarin (HSK 4+) greatly expands options and career mobility.",
    visaSponsorshipHistory: "Has sponsored work permits for qualified international graduates. Process takes 3-4 months after offer.",
    salaryRange: "¥18,000 – ¥28,000/month for fresh graduates in tech roles (2023 data from alumni)",
    type: "Chinese firm",
  },
  {
    id: "company-alibaba",
    name: "Alibaba Group",
    logoLetter: "A",
    logoColor: "bg-gold-50 text-gold-700",
    industry: "E-commerce & Technology",
    locations: ["Hangzhou", "Shanghai", "Beijing"],
    alumniCount: 6,
    ratings: {
      internationalFriendliness: 4,
      workLifeBalance: 3,
      careerGrowth: 4,
      compensationTransparency: 3,
    },
    testimonials: [
      {
        quote: "Hangzhou is great for ZJUT graduates because the commute is easy and the alumni network is dense here.",
        authorLabel: "Bangladeshi data analyst",
        context: "Joined 2021",
      },
    ],
    applicationTips: [
      "Alibaba's intern-to-hire pipeline is strong — intern in your final year if possible.",
      "The written test covers data structures, SQL, and logical reasoning.",
      "Research which BU (business unit) you are applying to — they vary significantly.",
    ],
    interviewQuestions: [
      "Why Alibaba and not ByteDance or Tencent?",
      "How would you improve a specific Alibaba product you use?",
      "Describe a data-driven decision you made.",
    ],
    languageExpectation: "Mandarin required for most domestic roles. International commerce and cloud divisions have English-track positions.",
    visaSponsorshipHistory: "Sponsors work permits. ZJUT graduates have been successfully sponsored via Alibaba's international talent program.",
    salaryRange: "¥15,000 – ¥25,000/month for fresh graduates (2023 data)",
    type: "Chinese firm",
  },
  {
    id: "company-huawei",
    name: "Huawei",
    logoLetter: "H",
    logoColor: "bg-ink-50 text-ink-900",
    industry: "Telecommunications & Technology",
    locations: ["Shenzhen", "Beijing", "Chengdu", "Xi'an"],
    alumniCount: 5,
    ratings: {
      internationalFriendliness: 3,
      workLifeBalance: 2,
      careerGrowth: 4,
      compensationTransparency: 3,
    },
    testimonials: [
      {
        quote: "The technical depth at Huawei is unmatched. It is demanding but you become a very strong engineer.",
        authorLabel: "Russian engineer",
        context: "Joined 2021",
      },
    ],
    applicationTips: [
      "Huawei's aptitude test is known to be very difficult — practice numerical reasoning under time pressure.",
      "The culture is hierarchical and process-driven. Show discipline and attention to detail.",
      "Huawei values loyalty signals — research the company deeply before interviews.",
    ],
    interviewQuestions: [
      "How do you handle high-pressure environments with unclear requirements?",
      "What is your understanding of telecom protocols?",
      "Where do you see yourself in five years at Huawei?",
    ],
    languageExpectation: "Strong Mandarin preferred. Some international divisions use English but advancement is tied to language ability.",
    visaSponsorshipHistory: "Has sponsored international graduates. Process is bureaucratic but reliable for full-time hires.",
    salaryRange: "¥16,000 – ¥24,000/month for engineers, higher for R&D tracks (2023 data)",
    type: "Chinese firm",
  },
  {
    id: "company-bosch",
    name: "Bosch China",
    logoLetter: "B",
    logoColor: "bg-ink-50 text-ink-600",
    industry: "Manufacturing & Engineering",
    locations: ["Shanghai", "Suzhou", "Wuhan"],
    alumniCount: 3,
    ratings: {
      internationalFriendliness: 5,
      workLifeBalance: 4,
      careerGrowth: 3,
      compensationTransparency: 4,
    },
    testimonials: [
      {
        quote: "Bosch feels like a German company that happens to be in China. Professional, fair, and good on work-life balance.",
        authorLabel: "Nigerian mechanical engineer",
        context: "Joined 2020",
      },
    ],
    applicationTips: [
      "Apply to Bosch's graduate trainee program — it is competitive but ideal for internationals.",
      "English is the working language in most teams. Mandarin is a plus, not a requirement.",
      "Highlight any experience with German-style quality or manufacturing standards.",
    ],
    interviewQuestions: [
      "Tell me about a quality or safety issue you identified and resolved.",
      "How do you work with cross-functional teams in different time zones?",
      "What motivates you to work in manufacturing rather than software?",
    ],
    languageExpectation: "English primary in international teams. Mandarin useful for supplier and factory floor interactions.",
    visaSponsorshipHistory: "Strong track record of work permit sponsorship for qualified engineers. HR team is experienced with the process.",
    salaryRange: "¥14,000 – ¥20,000/month for fresh engineers (2023 data)",
    type: "MNC",
  },
  {
    id: "company-hsbc",
    name: "HSBC China",
    logoLetter: "H",
    logoColor: "bg-gold-50 text-gold-700",
    industry: "Banking & Finance",
    locations: ["Shanghai", "Beijing", "Guangzhou"],
    alumniCount: 2,
    ratings: {
      internationalFriendliness: 5,
      workLifeBalance: 3,
      careerGrowth: 4,
      compensationTransparency: 4,
    },
    testimonials: [
      {
        quote: "HSBC is the best of both worlds — global brand, Chinese market. My multilingual background was a genuine asset.",
        authorLabel: "Pakistani relationship manager",
        context: "Joined 2021",
      },
    ],
    applicationTips: [
      "Apply to the Graduate Management Trainee program for the best career trajectory.",
      "Competency-based interviews — prepare STAR-format answers for all standard competencies.",
      "Mandarin and a second language combination is highly valued.",
    ],
    interviewQuestions: [
      "Give an example of a time you built trust with a difficult client.",
      "How do you balance compliance requirements with client expectations?",
      "Why HSBC and not a domestic Chinese bank?",
    ],
    languageExpectation: "English is the corporate language. Mandarin is expected for client-facing roles in China.",
    visaSponsorshipHistory: "Sponsors work permits for graduate hires. Process handled by dedicated HR team.",
    salaryRange: "¥15,000 – ¥22,000/month for graduate management trainees (2023 data)",
    type: "MNC",
  },
  {
    id: "company-dji",
    name: "DJI",
    logoLetter: "D",
    logoColor: "bg-ink-900 text-surface-0",
    industry: "Consumer Electronics & Robotics",
    locations: ["Shenzhen"],
    alumniCount: 2,
    ratings: {
      internationalFriendliness: 4,
      workLifeBalance: 3,
      careerGrowth: 5,
      compensationTransparency: 3,
    },
    testimonials: [
      {
        quote: "If you are a designer or engineer, DJI is like working at Apple but in Shenzhen. Products you are genuinely proud of.",
        authorLabel: "Brazilian product designer",
        context: "Joined 2021",
      },
    ],
    applicationTips: [
      "Portfolio is everything for design roles — make sure every project shows your process, not just outcomes.",
      "Engineers should be prepared for multi-stage technical tests including hardware knowledge.",
      "DJI culture values excellence over speed. Show depth, not just speed.",
    ],
    interviewQuestions: [
      "Walk me through the design process behind your strongest portfolio piece.",
      "How would you redesign a DJI product you own?",
      "Describe a time you pushed back on a design brief and why.",
    ],
    languageExpectation: "English sufficient for international product teams. Mandarin opens doors to core product teams.",
    visaSponsorshipHistory: "Sponsors for exceptional candidates. Less systematic than large SOEs — advocate for yourself.",
    salaryRange: "¥16,000 – ¥26,000/month for engineers and designers (2023 data)",
    type: "Chinese firm",
  },
  {
    id: "company-siemens",
    name: "Siemens China",
    logoLetter: "S",
    logoColor: "bg-aurora-blue/10 text-aurora-blue",
    industry: "Industrial Technology",
    locations: ["Beijing", "Shanghai", "Chengdu"],
    alumniCount: 2,
    ratings: {
      internationalFriendliness: 5,
      workLifeBalance: 4,
      careerGrowth: 3,
      compensationTransparency: 4,
    },
    testimonials: [
      {
        quote: "Very structured, very German. Great for engineers who value process and stability.",
        authorLabel: "Russian electrical engineer",
        context: "Joined 2020",
      },
    ],
    applicationTips: [
      "Siemens' graduate program recruits a year in advance — plan early.",
      "Emphasize any automation or digitalization experience.",
      "The culture rewards methodical, precise candidates.",
    ],
    interviewQuestions: [
      "How do you approach a complex engineering problem with multiple possible solutions?",
      "Describe your experience with automation or industrial control systems.",
      "Why industrial technology rather than consumer tech?",
    ],
    languageExpectation: "English or German primary. Mandarin helpful for local collaboration.",
    visaSponsorshipHistory: "Reliable work permit sponsorship. Siemens has a large compliance and HR infrastructure.",
    salaryRange: "¥13,000 – ¥19,000/month for graduate engineers (2023 data)",
    type: "MNC",
  },
  {
    id: "company-meituan",
    name: "Meituan",
    logoLetter: "M",
    logoColor: "bg-gold-50 text-gold-700",
    industry: "Technology & Local Services",
    locations: ["Beijing", "Shanghai"],
    alumniCount: 2,
    ratings: {
      internationalFriendliness: 3,
      workLifeBalance: 2,
      careerGrowth: 5,
      compensationTransparency: 4,
    },
    testimonials: [
      {
        quote: "Meituan is all-in Mandarin. If your Chinese is strong, the growth is fast. If not, it is very hard.",
        authorLabel: "Vietnamese frontend engineer",
        context: "Joined 2023",
      },
    ],
    applicationTips: [
      "Mandarin proficiency is critical — nearly all internal communication is Chinese.",
      "Algorithm interviews are rigorous. Practice daily for at least two months.",
      "Show familiarity with Meituan's super-app ecosystem in your interviews.",
    ],
    interviewQuestions: [
      "How would you optimize a delivery routing algorithm?",
      "Describe a product improvement you would make to Meituan's core app.",
      "How do you handle a codebase review with 1000+ comments?",
    ],
    languageExpectation: "Mandarin required. Minimal English usage in day-to-day work.",
    visaSponsorshipHistory: "Has sponsored international hires but less frequently than larger firms. Verify before accepting.",
    salaryRange: "¥17,000 – ¥26,000/month for tech graduates (2023 data)",
    type: "Chinese firm",
  },
  {
    id: "company-ant",
    name: "Ant Group",
    logoLetter: "A",
    logoColor: "bg-aurora-blue/10 text-aurora-blue",
    industry: "Fintech",
    locations: ["Hangzhou", "Shanghai"],
    alumniCount: 2,
    ratings: {
      internationalFriendliness: 4,
      workLifeBalance: 3,
      careerGrowth: 5,
      compensationTransparency: 4,
    },
    testimonials: [
      {
        quote: "Working at the center of China's payment infrastructure is a privilege. The scale of impact is hard to describe.",
        authorLabel: "Kenyan data analyst",
        context: "Joined 2020",
      },
    ],
    applicationTips: [
      "Ant Group values both technical depth and business understanding — show both.",
      "The fintech domain requires you to demonstrate knowledge of payments and financial services.",
      "Hangzhou location is convenient for ZJUT graduates.",
    ],
    interviewQuestions: [
      "How does Alipay differ from Western payment systems and why does that matter?",
      "Describe a time you worked with large-scale data under privacy constraints.",
      "Where do you see global fintech in five years?",
    ],
    languageExpectation: "English sufficient for international team roles. Mandarin required for most data and product roles.",
    visaSponsorshipHistory: "Actively sponsors international talent in data and technical roles. Strong HR support.",
    salaryRange: "¥16,000 – ¥25,000/month for tech/data graduates (2023 data)",
    type: "Chinese firm",
  },
  {
    id: "company-sinopec",
    name: "Sinopec",
    logoLetter: "S",
    logoColor: "bg-ink-50 text-ink-900",
    industry: "Energy & Chemicals",
    locations: ["Hangzhou", "Beijing", "Guangzhou", "Chongqing"],
    alumniCount: 2,
    ratings: {
      internationalFriendliness: 3,
      workLifeBalance: 4,
      careerGrowth: 3,
      compensationTransparency: 3,
    },
    testimonials: [
      {
        quote: "Stable, professional, and well-paying for a SOE. The international friendliness depends heavily on your team.",
        authorLabel: "Indonesian chemical engineer",
        context: "Joined 2022",
      },
    ],
    applicationTips: [
      "SOE applications require extensive paperwork — start early and check every document.",
      "Political neutrality and professional reliability are strongly valued.",
      "Engineering competency tests are technical and detailed.",
    ],
    interviewQuestions: [
      "Describe your understanding of environmental compliance in the petrochemical sector.",
      "How do you manage safety protocols in a high-risk environment?",
      "Why a state-owned enterprise rather than a private firm?",
    ],
    languageExpectation: "Mandarin required. English used in some international compliance and technical documentation.",
    visaSponsorshipHistory: "SOE sponsorship is reliable but slow. Allow 4-6 months for permit processing.",
    salaryRange: "¥10,000 – ¥15,000/month plus housing allowance (2023 data)",
    type: "Chinese firm",
  },
  {
    id: "company-catl",
    name: "CATL",
    logoLetter: "C",
    logoColor: "bg-aurora-violet/10 text-aurora-violet",
    industry: "Energy & EV",
    locations: ["Ningde", "Ningbo", "Shanghai", "Chengdu"],
    alumniCount: 2,
    ratings: {
      internationalFriendliness: 3,
      workLifeBalance: 2,
      careerGrowth: 5,
      compensationTransparency: 3,
    },
    testimonials: [
      {
        quote: "If you want to be at the center of the global energy transition, CATL is the best company in the world for that.",
        authorLabel: "Russian battery systems engineer",
        context: "Joined 2019",
      },
    ],
    applicationTips: [
      "Electrical engineering and chemistry backgrounds are most valued.",
      "CATL is expanding internationally — highlight any global mindset.",
      "Be prepared for long working hours and high technical expectations.",
    ],
    interviewQuestions: [
      "What do you know about lithium-ion vs solid-state battery technology?",
      "Describe an engineering challenge you solved under time pressure.",
      "Why energy storage rather than other sectors?",
    ],
    languageExpectation: "Mandarin essential. English used in international research partnerships.",
    visaSponsorshipHistory: "Sponsors international technical talent. Ningbo and Chengdu are less competitive locations.",
    salaryRange: "¥15,000 – ¥22,000/month for engineers (2023 data)",
    type: "Chinese firm",
  },
  {
    id: "company-ctrip",
    name: "Ctrip (Trip.com)",
    logoLetter: "T",
    logoColor: "bg-aurora-blue/10 text-aurora-blue",
    industry: "Travel & E-commerce",
    locations: ["Shanghai"],
    alumniCount: 2,
    ratings: {
      internationalFriendliness: 4,
      workLifeBalance: 4,
      careerGrowth: 4,
      compensationTransparency: 4,
    },
    testimonials: [
      {
        quote: "Ctrip has a genuinely international culture because the product is travel. They understand global perspectives.",
        authorLabel: "Uzbek financial analyst",
        context: "Joined 2023",
      },
    ],
    applicationTips: [
      "Finance and data roles are accessible for English-speaking internationals.",
      "Trip.com's global brand is a talking point — mention international experience.",
      "Shanghai office culture is more relaxed than Beijing tech firms.",
    ],
    interviewQuestions: [
      "How would you improve the Trip.com booking experience for international travelers?",
      "Walk me through a financial model you have built.",
      "How do you communicate financial analysis to non-finance stakeholders?",
    ],
    languageExpectation: "English-friendly compared to most Chinese internet firms. Mandarin still opens more doors.",
    visaSponsorshipHistory: "Regularly sponsors international finance and tech graduates.",
    salaryRange: "¥13,000 – ¥20,000/month for finance and tech graduates (2023 data)",
    type: "Chinese firm",
  },
  {
    id: "company-mindray",
    name: "Mindray",
    logoLetter: "M",
    logoColor: "bg-success/10 text-success",
    industry: "Medical Devices & Healthcare",
    locations: ["Shenzhen", "Shanghai", "Beijing"],
    alumniCount: 2,
    ratings: {
      internationalFriendliness: 4,
      workLifeBalance: 4,
      careerGrowth: 4,
      compensationTransparency: 4,
    },
    testimonials: [
      {
        quote: "A hidden gem for biomedical engineers. Internationally recognized brand, great career path.",
        authorLabel: "Indian application specialist",
        context: "Joined 2020",
      },
    ],
    applicationTips: [
      "Clinical application roles value communication skills as much as technical knowledge.",
      "Travel readiness is important — roles often involve customer site visits across Asia.",
      "English is common in international sales teams.",
    ],
    interviewQuestions: [
      "Describe how you would explain a technical device feature to a non-technical physician.",
      "How do you stay updated on developments in medical device regulation?",
      "Tell me about your experience in a clinical or laboratory environment.",
    ],
    languageExpectation: "English used for international client teams. Mandarin needed for internal collaboration.",
    visaSponsorshipHistory: "Sponsors work permits for technical and clinical roles. Process is straightforward.",
    salaryRange: "¥12,000 – ¥18,000/month for application and engineering roles (2023 data)",
    type: "Chinese firm",
  },
  {
    id: "company-cccc",
    name: "CCCC",
    logoLetter: "C",
    logoColor: "bg-ink-50 text-ink-900",
    industry: "Construction & Infrastructure",
    locations: ["Beijing", "Chengdu", "Various project sites"],
    alumniCount: 2,
    ratings: {
      internationalFriendliness: 3,
      workLifeBalance: 3,
      careerGrowth: 4,
      compensationTransparency: 3,
    },
    testimonials: [
      {
        quote: "BRI projects are a real career option. If you are willing to travel, CCCC gives you global infrastructure experience.",
        authorLabel: "Mongolian project manager",
        context: "Joined 2019",
      },
    ],
    applicationTips: [
      "Civil and structural engineering degrees are directly relevant.",
      "Willingness to work on-site outside China is a major asset.",
      "SOE application process — allow significant time for paperwork.",
    ],
    interviewQuestions: [
      "Are you willing to be posted to overseas project sites?",
      "Describe your experience with site management or construction supervision.",
      "What do you know about BRI project requirements and compliance?",
    ],
    languageExpectation: "Mandarin required for internal operations. English used on international project sites.",
    visaSponsorshipHistory: "Standard SOE sponsorship process. Reliable for civil engineering graduates.",
    salaryRange: "¥10,000 – ¥16,000/month base plus site allowances (2023 data)",
    type: "Chinese firm",
  },
  {
    id: "company-xiaomi",
    name: "Xiaomi",
    logoLetter: "X",
    logoColor: "bg-ink-900 text-surface-0",
    industry: "Consumer Electronics",
    locations: ["Beijing", "Shenzhen", "Shanghai"],
    alumniCount: 1,
    ratings: {
      internationalFriendliness: 4,
      workLifeBalance: 3,
      careerGrowth: 4,
      compensationTransparency: 4,
    },
    testimonials: [
      {
        quote: "Xiaomi has global ambition baked in. International employees are valued because the market strategy is international.",
        authorLabel: "Indian product manager",
        context: "Joined 2022",
      },
    ],
    applicationTips: [
      "Xiaomi moves fast — show agility and comfort with ambiguity.",
      "Knowledge of consumer electronics markets outside China is a differentiator.",
      "The stock compensation can be meaningful — understand the vesting terms.",
    ],
    interviewQuestions: [
      "How would you adapt a Xiaomi product for the Southeast Asian market?",
      "Describe your experience analyzing consumer behavior data.",
      "What is your view on Xiaomi vs Samsung in global smartphone competition?",
    ],
    languageExpectation: "International teams use English. Core product and engineering teams use Mandarin.",
    visaSponsorshipHistory: "Sponsors international talent especially in global expansion roles.",
    salaryRange: "¥15,000 – ¥24,000/month for product and engineering graduates (2023 data)",
    type: "Chinese firm",
  },
  {
    id: "company-tencent",
    name: "Tencent",
    logoLetter: "T",
    logoColor: "bg-aurora-blue/10 text-aurora-blue",
    industry: "Technology & Media",
    locations: ["Shenzhen", "Beijing", "Shanghai"],
    alumniCount: 2,
    ratings: {
      internationalFriendliness: 3,
      workLifeBalance: 2,
      careerGrowth: 5,
      compensationTransparency: 3,
    },
    testimonials: [
      {
        quote: "Tencent is every bit as demanding as its reputation. But the compensation and the experience are elite.",
        authorLabel: "Bangladeshi software engineer",
        context: "Joined 2022",
      },
    ],
    applicationTips: [
      "Tencent is competitive — prepare to compete with top Chinese graduates.",
      "Networking with Tencent employees before applying significantly helps.",
      "Technical tests for engineers are among the hardest in China.",
    ],
    interviewQuestions: [
      "How would you scale a system to handle 100 million concurrent users?",
      "Describe the most technically challenging bug you have debugged.",
      "What Tencent product do you use and how would you improve it?",
    ],
    languageExpectation: "Mandarin strongly required. International roles exist but are competitive.",
    visaSponsorshipHistory: "Sponsors selectively. Strong candidates from target universities succeed.",
    salaryRange: "¥20,000 – ¥32,000/month for tech graduates (2023 data, top of market)",
    type: "Chinese firm",
  },
  {
    id: "company-jll",
    name: "JLL China",
    logoLetter: "J",
    logoColor: "bg-ink-50 text-ink-900",
    industry: "Real Estate & Consulting",
    locations: ["Shanghai", "Beijing", "Guangzhou"],
    alumniCount: 1,
    ratings: {
      internationalFriendliness: 5,
      workLifeBalance: 4,
      careerGrowth: 3,
      compensationTransparency: 4,
    },
    testimonials: [
      {
        quote: "JLL is genuinely international. My non-Chinese background was seen as an asset from day one.",
        authorLabel: "Brazilian business analyst",
        context: "Joined 2022",
      },
    ],
    applicationTips: [
      "Finance, business, and economics backgrounds are directly relevant.",
      "English is sufficient for many teams — strongest English environment among the companies listed.",
      "JLL's graduate program includes structured rotations.",
    ],
    interviewQuestions: [
      "Walk me through how you would value a commercial real estate asset.",
      "How do macro-economic conditions in China affect office demand?",
      "Why real estate services over banking or consulting?",
    ],
    languageExpectation: "English primary. Mandarin very helpful for client interactions in China.",
    visaSponsorshipHistory: "Consistent track record of work permit sponsorship.",
    salaryRange: "¥12,000 – ¥18,000/month for graduate analysts (2023 data)",
    type: "MNC",
  },
  {
    id: "company-dhl",
    name: "DHL China",
    logoLetter: "D",
    logoColor: "bg-gold-50 text-gold-700",
    industry: "Logistics & Supply Chain",
    locations: ["Shanghai", "Guangzhou", "Chengdu"],
    alumniCount: 1,
    ratings: {
      internationalFriendliness: 5,
      workLifeBalance: 4,
      careerGrowth: 3,
      compensationTransparency: 4,
    },
    testimonials: [
      {
        quote: "DHL is underrated for international graduates. The global brand means genuine international mobility later.",
        authorLabel: "Pakistani logistics analyst",
        context: "Joined 2022",
      },
    ],
    applicationTips: [
      "Operations, supply chain, and IE backgrounds fit naturally.",
      "DHL's Graduate Leadership Program is a strong entry point.",
      "International background is valued for client-facing cross-border logistics roles.",
    ],
    interviewQuestions: [
      "How would you reduce last-mile delivery cost in a dense urban area?",
      "Describe a time you improved a process in a team or organization.",
      "What do you know about China's role in global supply chains?",
    ],
    languageExpectation: "English primary in the international division. Mandarin helpful for domestic operations.",
    visaSponsorshipHistory: "Sponsors for graduate program participants. Reliable process.",
    salaryRange: "¥11,000 – ¥17,000/month for graduate program participants (2023 data)",
    type: "MNC",
  },
  {
    id: "company-startup-welo",
    name: "Welo Tech",
    logoLetter: "W",
    logoColor: "bg-aurora-violet/10 text-aurora-violet",
    industry: "HR Tech & SaaS",
    locations: ["Hangzhou"],
    alumniCount: 1,
    ratings: {
      internationalFriendliness: 5,
      workLifeBalance: 4,
      careerGrowth: 4,
      compensationTransparency: 3,
    },
    testimonials: [
      {
        quote: "A startup in Hangzhou that genuinely values diverse perspectives. My international background was a selling point.",
        authorLabel: "Kenyan product manager",
        context: "Joined 2023",
      },
    ],
    applicationTips: [
      "Startup culture — be ready to wear multiple hats.",
      "Show genuine interest in the product, not just the company size.",
      "Equity compensation may be offered — ask about vesting schedule.",
    ],
    interviewQuestions: [
      "What is broken about hiring and onboarding and how would you fix it?",
      "Tell me about a time you built something from scratch with limited resources.",
      "How do you prioritize when everything is urgent?",
    ],
    languageExpectation: "English-friendly startup. Product teams use mixed English and Mandarin.",
    visaSponsorshipHistory: "Small startup — sponsorship is possible but requires negotiation. Less reliable than larger companies.",
    salaryRange: "¥12,000 – ¥18,000/month plus equity (2023 data, smaller total)",
    type: "Startup",
  },
  {
    id: "company-startup-greenlabs",
    name: "GreenLabs China",
    logoLetter: "G",
    logoColor: "bg-success/10 text-success",
    industry: "CleanTech & Agriculture",
    locations: ["Chengdu", "Hangzhou"],
    alumniCount: 1,
    ratings: {
      internationalFriendliness: 5,
      workLifeBalance: 5,
      careerGrowth: 3,
      compensationTransparency: 4,
    },
    testimonials: [
      {
        quote: "Small team, big mission. The best work-life balance I have heard of at any company in this list.",
        authorLabel: "Vietnamese environmental engineer",
        context: "Joined 2023",
      },
    ],
    applicationTips: [
      "Environmental science and chemical engineering backgrounds fit best.",
      "Sustainability mission is genuine — research it and show authentic interest.",
      "Smaller teams mean direct mentorship from senior engineers.",
    ],
    interviewQuestions: [
      "How do you measure the environmental impact of a product?",
      "Describe a sustainable engineering solution you designed or studied.",
      "Why a startup rather than an established energy company?",
    ],
    languageExpectation: "English-first startup. Mandarin used with local partners.",
    visaSponsorshipHistory: "Has sponsored two international hires. Process is ad hoc — plan for uncertainty.",
    salaryRange: "¥10,000 – ¥15,000/month (lower cash, mission-driven compensation) (2023 data)",
    type: "Startup",
  },
];

export const communityQuestions: CommunityQuestion[] = [
  {
    id: "qa-1",
    title: "How do I get a Z visa sponsored as an international ZJUT graduate?",
    body: "I am graduating in June and I have a job offer from a Chinese private company. They say they can help with the work permit but I have no idea what documents I need to prepare on my side. My home country is Indonesia. Has anyone gone through this recently? What is the full document checklist?",
    askerHandle: "ID_student_2024",
    category: "Visa & Legal",
    language: "English",
    tags: ["work permit", "Z visa", "Indonesia", "graduation"],
    upvotes: 23,
    postedAt: "2024-11-15",
    answers: [
      {
        id: "ans-1-1",
        questionId: "qa-1",
        body: "I went through this in 2023 for a Beijing role. From your side you need: original degree certificate (notarized and apostilled), academic transcripts (same process), a non-criminal record from your home country (also notarized), your passport, health certificate from a recognized clinic, and passport photos. The company will handle the business license, tax registration, and the application to the local human resources bureau. Start the notarization in your home country 3 months before you need the permit — it takes longer than you think.",
        authorHandle: "Arjun_S_ZJUT22",
        upvotes: 18,
        postedAt: "2024-11-16",
      },
      {
        id: "ans-1-2",
        questionId: "qa-1",
        body: "The health certificate is important — it must be done at a specific clinic approved by the Chinese embassy in your country OR at the International Travel Healthcare Center in China. I did mine in China after arriving on a tourist visa, then converted. Ask your HR which route they prefer.",
        authorHandle: "Siti_ZJUT22",
        upvotes: 12,
        postedAt: "2024-11-17",
      },
      {
        id: "ans-1-3",
        questionId: "qa-1",
        body: "One thing people miss: the degree certificate notarization must be done by the Ministry of Foreign Affairs in your home country first, THEN apostilled or authenticated for China. If your country is part of the Hague Apostille Convention (Indonesia is), apostille is enough. If not, you need Chinese embassy legalization.",
        authorHandle: "Nadia_K_ZJUT21",
        upvotes: 9,
        postedAt: "2024-11-18",
      },
    ],
  },
  {
    id: "qa-2",
    title: "What is it really like to negotiate salary as a non-Chinese candidate?",
    body: "I have an offer from a Chinese internet company. The base they offered is 18k CNY/month. I know Chinese candidates with similar backgrounds negotiate. Is it normal for international candidates to negotiate too? And if so, how? I do not want to come across as disrespectful of the offer.",
    askerHandle: "BD_finance_student",
    category: "Salary Negotiation",
    language: "English",
    tags: ["salary", "negotiation", "offer", "Chinese firm"],
    upvotes: 31,
    postedAt: "2024-10-22",
    answers: [
      {
        id: "ans-2-1",
        questionId: "qa-2",
        body: "Yes, international candidates absolutely negotiate — in fact, companies often expect it. The key is to do it politely and with a specific counter rather than a vague ask. Something like: 'Thank you very much for the offer. Based on my research and the cost of living in [city], I was hoping we could discuss 21,000 CNY. Is there flexibility?' A 10-20% counter is standard. They will either meet it, split the difference, or say the offer is firm. None of those responses is disrespectful.",
        authorHandle: "Fatima_R_ZJUT21",
        upvotes: 22,
        postedAt: "2024-10-23",
      },
      {
        id: "ans-2-2",
        questionId: "qa-2",
        body: "Also ask about non-salary components: housing allowance, flight ticket home (one per year is standard at some firms), bonus structure, stock or equity if applicable, and annual leave days. Sometimes these are negotiable even when base salary is not.",
        authorHandle: "Zulfiya_K_ZJUT23",
        upvotes: 15,
        postedAt: "2024-10-24",
      },
    ],
  },
  {
    id: "qa-3",
    title: "Chinese-style resume vs Western-style resume — which to use for MNC roles in China?",
    body: "I am applying to both Chinese firms and MNCs (Bosch, Siemens, HSBC) in China. Should I send the same resume format to both? I have heard Chinese resumes include a photo and personal details that are unusual in Western ones. What do MNCs in China actually expect?",
    askerHandle: "NG_engineer_2024",
    category: "Application Process",
    language: "English",
    tags: ["resume", "format", "MNC", "Chinese style"],
    upvotes: 27,
    postedAt: "2024-09-10",
    answers: [
      {
        id: "ans-3-1",
        questionId: "qa-3",
        body: "Short answer: use a Chinese-style resume for Chinese firms (with photo, DOB, nationality, marital status) and a clean Western-style resume for MNCs (no photo, no personal details). MNCs with Western HR practices actively avoid seeing photos to reduce bias claims — so sending a photo can actually hurt you in some European-branded companies.",
        authorHandle: "Amara_O_ZJUT20",
        upvotes: 24,
        postedAt: "2024-09-11",
      },
      {
        id: "ans-3-2",
        questionId: "qa-3",
        body: "For MNCs in China specifically: English resume is expected, but have a Chinese version ready. Some HR teams prefer to share the Chinese version with local hiring managers even in international firms. Keep both versions in sync.",
        authorHandle: "Nadia_K_ZJUT21",
        upvotes: 11,
        postedAt: "2024-09-12",
      },
    ],
  },
  {
    id: "qa-4",
    title: "How do Chinese coworkers react to Muslim dietary restrictions and prayer time?",
    body: "I am a practicing Muslim from Pakistan. I have a job offer in Shenzhen at a private tech company. I am worried about how to handle halal food (Shenzhen has some options I think), and also about finding time and space for prayers during the workday. Has anyone navigated this?",
    askerHandle: "PK_tech_student",
    category: "Cultural Adaptation",
    language: "English",
    tags: ["Muslim", "halal", "prayer", "workplace", "Shenzhen"],
    upvotes: 19,
    postedAt: "2024-08-20",
    answers: [
      {
        id: "ans-4-1",
        questionId: "qa-4",
        body: "Shenzhen has a decent halal scene — look for restaurants marked with the halal logo (清真). There are also a few Muslim communities and mosques; the Shenzhen South Mosque is the most accessible. For prayers: most modern tech offices have unused meeting rooms or quiet areas you can use. I recommend having a brief, matter-of-fact conversation with your manager early — most Chinese managers have no problem with it once they understand what you need. Framing it as 'I need 5-10 minutes at these times' rather than a religious accommodation request tends to go smoother.",
        authorHandle: "Fatima_R_ZJUT21",
        upvotes: 17,
        postedAt: "2024-08-21",
      },
      {
        id: "ans-4-2",
        questionId: "qa-4",
        body: "Hangzhou is different from Shenzhen for this — Hangzhou has a historically significant Muslim population and better halal infrastructure in certain neighborhoods. If your job location is flexible, worth factoring in.",
        authorHandle: "Siti_ZJUT22",
        upvotes: 8,
        postedAt: "2024-08-22",
      },
    ],
  },
  {
    id: "qa-5",
    title: "Technical interview preparation for Chinese tech companies — where to start?",
    body: "I have a first-round technical interview at Meituan next week. I have been coding for three years but I am not familiar with the Chinese tech interview style. I hear it is very algorithm-heavy. Is LeetCode enough? Are there specific patterns I should focus on?",
    askerHandle: "VN_cs_student",
    category: "Interview Prep",
    language: "English",
    tags: ["technical interview", "algorithms", "LeetCode", "Meituan", "coding"],
    upvotes: 35,
    postedAt: "2024-11-01",
    answers: [
      {
        id: "ans-5-1",
        questionId: "qa-5",
        body: "LeetCode is the core preparation — specifically: arrays/strings, linked lists, trees (especially binary trees and BST), dynamic programming, graph traversal (BFS/DFS), and sliding window. Meituan in particular tests dynamic programming heavily. Do at least 50 medium-level questions before the interview. Also important: verbalize your thinking as you code — Chinese tech interviewers want to hear your reasoning, not just see working code.",
        authorHandle: "Thanh_N_ZJUT23",
        upvotes: 29,
        postedAt: "2024-11-02",
      },
      {
        id: "ans-5-2",
        questionId: "qa-5",
        body: "One specific thing for Meituan: they often ask system design questions even for junior roles related to food delivery logistics. Think about how you would design a routing system or a real-time order matching system. Does not need to be perfect — shows you can think at scale.",
        authorHandle: "Arjun_S_ZJUT22",
        upvotes: 14,
        postedAt: "2024-11-03",
      },
    ],
  },
  {
    id: "qa-6",
    title: "Can I stay in China on a tourist visa while waiting for work permit processing?",
    body: "My employer submitted my work permit application but the processing is taking longer than expected. My current student visa (X2) expires in one month. Can I switch to a tourist visa in the meantime, or do I need to leave China? My company HR is not very clear on this.",
    askerHandle: "UZ_grad_2023",
    category: "Visa & Legal",
    language: "English",
    tags: ["visa", "work permit", "student visa", "tourist visa", "overstay"],
    upvotes: 28,
    postedAt: "2024-07-14",
    answers: [
      {
        id: "ans-6-1",
        questionId: "qa-6",
        body: "Do NOT overstay your visa under any circumstances — the fines and blacklist risk are serious. You have a few options: (1) Apply for a visa extension at your local Exit-Entry Administration Bureau — some allow a short extension while work permit is pending with documentation from your employer. (2) Do a visa run to Hong Kong or Macau and re-enter on an L (tourist) visa while waiting. (3) Ask your employer to expedite or apply for a temporary work authorization letter. Option 1 or 3 is better than 2 if your employer is cooperative.",
        authorHandle: "Nadia_K_ZJUT21",
        upvotes: 21,
        postedAt: "2024-07-15",
      },
      {
        id: "ans-6-2",
        questionId: "qa-6",
        body: "I did a Hong Kong border run in exactly this situation. It worked but was stressful — the L visa has conditions and if your situation seems like you are living and working in China on a tourist visa, immigration can ask questions. Have your employer's work permit documentation ready to show good faith.",
        authorHandle: "Zulfiya_K_ZJUT23",
        upvotes: 13,
        postedAt: "2024-07-16",
      },
    ],
  },
  {
    id: "qa-7",
    title: "How hard is it to actually use English day-to-day at a Chinese company?",
    body: "I have an offer from a Chinese tech company. They said in the interview that the team uses English. But I have heard that in practice everything switches to Mandarin in meetings. My Mandarin is HSK 3 level. Should I be worried?",
    askerHandle: "KE_data_student",
    category: "Cultural Adaptation",
    language: "English",
    tags: ["language", "Mandarin", "English", "Chinese firm", "workplace"],
    upvotes: 44,
    postedAt: "2024-10-05",
    answers: [
      {
        id: "ans-7-1",
        questionId: "qa-7",
        body: "Honest answer: it depends heavily on the team, but your worry is valid. 'We use English' at a Chinese company usually means: English is acceptable, meetings can be in English if you ask, documentation may be bilingual. But the informal conversation — lunch, hallway chat, quick Slack messages — will almost always default to Mandarin. HSK 3 is survival level; you will understand the gist but miss nuance. Plan to reach HSK 4 within your first year. Take evening classes or use an app daily. It makes a massive difference to your actual integration.",
        authorHandle: "Kwame_B_ZJUT20",
        upvotes: 38,
        postedAt: "2024-10-06",
      },
      {
        id: "ans-7-2",
        questionId: "qa-7",
        body: "One practical tip: ask your manager at the start to briefly recap meeting decisions in English after Mandarin discussions. Most managers are happy to do this once you ask. It also signals to the team that you are engaged and learning.",
        authorHandle: "Thanh_N_ZJUT23",
        upvotes: 20,
        postedAt: "2024-10-07",
      },
    ],
  },
  {
    id: "qa-8",
    title: "Does ZJUT degree have good recognition in job applications in China?",
    body: "I am worried that employers will see my ZJUT degree as less prestigious than top Chinese universities like Zhejiang University or Fudan. Is this a real disadvantage? How do other international ZJUT graduates handle this in applications?",
    askerHandle: "IN_mba_applicant",
    category: "Application Process",
    language: "English",
    tags: ["ZJUT", "degree recognition", "prestige", "university ranking"],
    upvotes: 22,
    postedAt: "2024-09-28",
    answers: [
      {
        id: "ans-8-1",
        questionId: "qa-8",
        body: "For international graduates, the bar is different from Chinese graduates. Chinese employers know that top international students who come to China often choose 211/985 universities or study in Hangzhou at ZJUT or nearby — and ZJUT is a reputable 211 engineering institution. The degree matters less than your Chinese language ability, relevant internship experience, and how you perform in interviews. I have never had an employer dismiss my ZJUT background.",
        authorHandle: "Arjun_S_ZJUT22",
        upvotes: 19,
        postedAt: "2024-09-29",
      },
      {
        id: "ans-8-2",
        questionId: "qa-8",
        body: "For MNCs especially, a Chinese university degree of any rank is seen as strong proof of cultural adaptability and language skills. The ZJUT diploma combined with Chinese language proficiency is a real differentiator compared to someone who studied engineering abroad.",
        authorHandle: "Amara_O_ZJUT20",
        upvotes: 14,
        postedAt: "2024-09-30",
      },
    ],
  },
  {
    id: "qa-9",
    title: "What is the 996 culture really like and can you avoid it as an international hire?",
    body: "I have heard a lot about 996 (9am to 9pm, 6 days a week) at Chinese tech companies. Is this standard everywhere? I want to work in China but I also have family and health considerations. Are there companies where this is not the norm?",
    askerHandle: "RU_engineer_24",
    category: "Cultural Adaptation",
    language: "English",
    tags: ["996", "work-life balance", "overwork", "Chinese tech culture"],
    upvotes: 38,
    postedAt: "2024-08-10",
    answers: [
      {
        id: "ans-9-1",
        questionId: "qa-9",
        body: "996 is real but varies a lot. ByteDance and Meituan are known for intense hours. Alibaba has improved slightly post-Jack Ma comments on work culture. MNCs like Bosch, HSBC, Siemens are generally closer to 9-6 with occasional overtime — much more aligned with Western norms. SOEs like Sinopec or CCCC are often 8-5 with predictable schedules. If work-life balance is a priority, target MNCs or SOEs first. Startups vary enormously — ask directly in the interview.",
        authorHandle: "Nadia_K_ZJUT21",
        upvotes: 32,
        postedAt: "2024-08-11",
      },
      {
        id: "ans-9-2",
        questionId: "qa-9",
        body: "As an international hire you do have slightly more leverage to set boundaries than a fresh Chinese graduate who feels cultural pressure. Be direct but respectful: 'I am committed to delivering excellent work within sustainable hours.' Some managers respect this more than you expect. Document your output clearly so no one can question your productivity.",
        authorHandle: "Kwame_B_ZJUT20",
        upvotes: 18,
        postedAt: "2024-08-12",
      },
    ],
  },
  {
    id: "qa-10",
    title: "How do I find an apartment in Hangzhou as a foreign graduate?",
    body: "My student dormitory access ends one month after graduation. I need to find an apartment in Hangzhou. I have heard that some landlords refuse to rent to foreigners or that the registration process with police is complicated. Any practical tips?",
    askerHandle: "ID_chem_grad",
    category: "General",
    language: "English",
    tags: ["housing", "apartment", "Hangzhou", "registration", "foreigner"],
    upvotes: 16,
    postedAt: "2024-06-30",
    answers: [
      {
        id: "ans-10-1",
        questionId: "qa-10",
        body: "Some landlords do hesitate to rent to foreigners because of the police registration requirement — it is extra paperwork for them. Strategies: (1) Use platforms like Ziroom (自如) or Beike (贝壳) — these are professional agencies that handle registration as a standard part of the service, so the landlord is used to it. (2) Ask a Chinese-speaking friend or classmate to help with initial contact. (3) Have your Chinese employer write a letter confirming your employment — this reassures landlords. Once you sign, you MUST register at the local police station within 24 hours of moving in. Bring your passport, lease agreement, and a photo.",
        authorHandle: "Siti_ZJUT22",
        upvotes: 14,
        postedAt: "2024-07-01",
      },
    ],
  },
  {
    id: "qa-11",
    title: "What is a realistic timeline from job application to actually starting work in China?",
    body: "I am starting applications for graduation in June. I want to plan my finances and logistics. From submitting a job application to your first day at a Chinese company, how long does it realistically take? Especially factoring in work permit processing.",
    askerHandle: "MN_civil_student",
    category: "Application Process",
    language: "English",
    tags: ["timeline", "application process", "work permit", "onboarding"],
    upvotes: 21,
    postedAt: "2024-05-15",
    answers: [
      {
        id: "ans-11-1",
        questionId: "qa-11",
        body: "Realistic timeline from application to Day 1: Job applications and interviews: 4-8 weeks. Offer negotiation and signing: 1-2 weeks. Work permit application (company side): 4-6 weeks. Health check and document notarization (your side, can run in parallel): 3-5 weeks. Z visa issuance after permit approval: 1-2 weeks. Total from first application to starting: 3-5 months is common. Plan your finances for at least 4 months of expenses after graduation with no income. Some companies offer a pre-start stipend — ask.",
        authorHandle: "Enkhjargal_B_ZJUT19",
        upvotes: 19,
        postedAt: "2024-05-16",
      },
    ],
  },
  {
    id: "qa-12",
    title: "How do African students get taken seriously in Chinese job interviews?",
    body: "I am from Nigeria and I have faced some awkward moments in interviews where I felt like I was being assessed on my background more than my skills. Any advice on how to navigate this professionally and confidently?",
    askerHandle: "NG_fintech_student",
    category: "Cultural Adaptation",
    language: "English",
    tags: ["African students", "discrimination", "interviews", "Nigeria", "confidence"],
    upvotes: 29,
    postedAt: "2024-10-18",
    answers: [
      {
        id: "ans-12-1",
        questionId: "qa-12",
        body: "I faced this too. My approach: project absolute confidence from the first second. Prepare your Mandarin self-introduction to be flawless — nothing shifts the dynamic faster than opening in strong Chinese. Come in knowing more about the company than most Chinese applicants. Reference specific products, initiatives, or recent news. It is unfair that we have to work harder to prove ourselves, but it is also an opportunity to show we are genuinely exceptional. Target companies with existing international hires — they have already solved this internal bias.",
        authorHandle: "Amara_O_ZJUT20",
        upvotes: 26,
        postedAt: "2024-10-19",
      },
      {
        id: "ans-12-2",
        questionId: "qa-12",
        body: "Also: the fintech and payments sector in China has genuine business interest in Africa. Ant Group, for example, has investments in M-Pesa and other African fintech. Your Nigerian background is a business asset there, not just cultural diversity. Frame it as market knowledge.",
        authorHandle: "Kwame_B_ZJUT20",
        upvotes: 17,
        postedAt: "2024-10-20",
      },
    ],
  },
  {
    id: "qa-13",
    title: "Is it possible to get a job in China as a finance graduate without strong Mandarin?",
    body: "I am graduating with a Finance degree from ZJUT. My Mandarin is HSK 2 — I can handle daily life but not business conversation. Are there roles I can realistically apply to in China where my Mandarin gap would not be disqualifying?",
    askerHandle: "BR_finance_grad",
    category: "Application Process",
    language: "English",
    tags: ["finance", "Mandarin", "language requirements", "MNC", "English roles"],
    upvotes: 18,
    postedAt: "2024-11-08",
    answers: [
      {
        id: "ans-13-1",
        questionId: "qa-13",
        body: "Yes, but your options narrow significantly. MNCs like HSBC, JLL, DHL, Bosch all have finance roles that genuinely operate in English — their international teams, treasury, and reporting functions. Also consider: regional roles at Chinese firms with overseas operations (they need English speakers for market analysis). Avoid domestic Chinese firms for now — the language barrier will limit your impact and growth. Use the next year to push your Mandarin to HSK 4 and open significantly more doors.",
        authorHandle: "Fatima_R_ZJUT21",
        upvotes: 15,
        postedAt: "2024-11-09",
      },
    ],
  },
  {
    id: "qa-14",
    title: "How do I explain gaps in my resume to Chinese employers?",
    body: "I had to return to my home country (Bangladesh) for a year due to a family emergency. I graduated in 2022 and I am applying now in 2024. Chinese job applications ask for detailed timelines. How do I explain a two-year gap honestly and professionally?",
    askerHandle: "BD_job_seeker",
    category: "Application Process",
    language: "English",
    tags: ["resume gap", "employment gap", "Bangladesh", "application"],
    upvotes: 14,
    postedAt: "2024-11-20",
    answers: [
      {
        id: "ans-14-1",
        questionId: "qa-14",
        body: "Be honest and brief. In Chinese professional culture, family is understood as a legitimate priority — do not over-explain or apologize. Write: 'Family responsibility, home country, 2022-2024.' Then immediately follow with anything you did during that period: freelance work, online courses, language study, volunteer work. If you genuinely did nothing job-related, that is fine — state it as family care. In the interview, prepare a 2-sentence explanation and pivot quickly to your enthusiasm for the role. Most Chinese employers will not dwell on it if you do not.",
        authorHandle: "Nadia_K_ZJUT21",
        upvotes: 11,
        postedAt: "2024-11-21",
      },
    ],
  },
  {
    id: "qa-15",
    title: "What mental health resources are available for international students and workers in Hangzhou?",
    body: "I have been struggling with loneliness and cultural adjustment since arriving at ZJUT. I know this is common but I am looking for actual resources — counseling, support groups, anything in English. Does ZJUT have anything? What about after graduation?",
    askerHandle: "TH_incoming_student",
    category: "General",
    language: "English",
    tags: ["mental health", "counseling", "loneliness", "Hangzhou", "support"],
    upvotes: 41,
    postedAt: "2024-09-05",
    answers: [
      {
        id: "ans-15-1",
        questionId: "qa-15",
        body: "First: you are not alone and what you are feeling is extremely common. ZJUT has a student counseling center (心理咨询中心) — ask the International Students Office if they have English-speaking counselors. For online options: BetterHelp and Talkspace work in China with VPN. Expat communities on WeChat often have mental health support groups — search for groups in Hangzhou. Sir Run Run Shaw Hospital (affiliated with Zhejiang University) has an international department with some English-speaking psychiatrists. Do not wait to reach out.",
        authorHandle: "Siti_ZJUT22",
        upvotes: 35,
        postedAt: "2024-09-06",
      },
      {
        id: "ans-15-2",
        questionId: "qa-15",
        body: "After graduation the expat community in Hangzhou is smaller than Shanghai or Beijing but is warm and active. Internations.org Hangzhou chapter, the Hangzhou Expat Meetup WeChat group, and various national community groups (there are Indonesian, Indian, Pakistani, African community chats) are all helpful. Getting involved in these before you need support means you have connections when you do.",
        authorHandle: "Kwame_B_ZJUT20",
        upvotes: 28,
        postedAt: "2024-09-07",
      },
    ],
  },
];

export const reviewQueue: ResumeReviewRequest[] = [
  {
    id: "rr-1",
    filename: "Ahmed_CV_ByteDance.pdf",
    format: "Chinese-style",
    target: "Chinese firm",
    focusAreas: ["Content", "Cultural fit"],
    submittedAt: "2024-11-28",
    status: "waiting",
  },
  {
    id: "rr-2",
    filename: "Priya_Resume_MNC.pdf",
    format: "Western-style",
    target: "MNC",
    focusAreas: ["Format", "Language"],
    submittedAt: "2024-11-27",
    status: "waiting",
  },
  {
    id: "rr-3",
    filename: "Nguyen_Van_CV.pdf",
    format: "Asian-style",
    target: "Chinese firm",
    focusAreas: ["Content", "Format", "Cultural fit"],
    submittedAt: "2024-11-26",
    status: "waiting",
  },
  {
    id: "rr-4",
    filename: "Oluwaseun_Resume.pdf",
    format: "Western-style",
    target: "MNC",
    focusAreas: ["Language", "Content"],
    submittedAt: "2024-11-25",
    status: "reviewed",
  },
  {
    id: "rr-5",
    filename: "Zuhra_Finance_CV.pdf",
    format: "Chinese-style",
    target: "Any",
    focusAreas: ["Cultural fit", "Content"],
    submittedAt: "2024-11-24",
    status: "waiting",
  },
  {
    id: "rr-6",
    filename: "Dmitri_Engineering_Resume.pdf",
    format: "Western-style",
    target: "MNC",
    focusAreas: ["Format"],
    submittedAt: "2024-11-23",
    status: "waiting",
  },
  {
    id: "rr-7",
    filename: "Bianca_Design_Portfolio_CV.pdf",
    format: "Asian-style",
    target: "Startup",
    focusAreas: ["Content", "Format", "Language"],
    submittedAt: "2024-11-22",
    status: "reviewed",
  },
  {
    id: "rr-8",
    filename: "Munkhbayar_CV.pdf",
    format: "Chinese-style",
    target: "Chinese firm",
    focusAreas: ["Cultural fit", "Language", "Content"],
    submittedAt: "2024-11-21",
    status: "waiting",
  },
];
