import type { Student } from "./types";

export const students: Student[] = [
  {
    id: "stu-001",
    name: "Nattapong Saetang",
    initials: "NS",
    nationality: "Thailand",
    nationalityFlag: "🇹🇭",
    year: 3,
    major: "Software Engineering",
    category: "Engineering",
    gpa: 3.72,
    classRanking: "Top 15%",
    hsk: 4,
    englishLevel: "Fluent",
    otherLanguages: ["Thai (Native)"],
    skills: ["TypeScript", "React", "Python", "UI Prototyping", "Mandarin (HSK 4)", "Cross-cultural Research"],
    projects: [
      {
        title: "ZJUT Campus Navigator",
        description: "Built a bilingual mobile map that helps new international students find classrooms, canteens, and bus gates without asking for directions every time.",
        tags: ["React Native", "Maps API", "i18n"],
      },
      {
        title: "Scholarship Deadline Tracker",
        description: "Created a web dashboard that aggregates university notices and reminds students before document submission windows close.",
        tags: ["Next.js", "PostgreSQL", "Automation"],
      },
      {
        title: "Dorm Maintenance Chatbot",
        description: "Prototyped a Mandarin-English chatbot for reporting repairs, with structured handoff messages for campus staff.",
        tags: ["Python", "NLP", "Service Design"],
      },
    ],
    bio: "I like building practical tools for moments when language makes simple tasks feel heavy. My best work sits between product, code, and international student life.",
    headline: "Software engineer focused on cross-cultural student products",
    verified: true,
    lookingFor: "Internship",
    availableFrom: "June 2026",
    preferredLocations: ["Hangzhou", "Shanghai", "Remote"],
    activities: ["International Student Association Tech Lead", "ZJUT Coding Club", "Thai Student Volunteer Group"],
    awards: [
      {
        title: "ZJUT International Student Excellence Award",
        year: 2025,
        description: "Recognized for academic performance and peer support work in the international college.",
      },
      {
        title: "Campus Innovation Sprint Finalist",
        year: 2024,
        description: "Reached the final round with a multilingual student services prototype.",
      },
    ],
    coursesCompleted: 26,
    responseTime: "Within 24 hours",
    lastActive: "2 hours ago",
    profileStrength: 88,
  },
  {
    id: "stu-002",
    name: "Nguyen Thi Minh Linh",
    initials: "NL",
    nationality: "Vietnam",
    nationalityFlag: "🇻🇳",
    year: 4,
    major: "Data Science and Big Data Technology",
    category: "Engineering",
    gpa: 3.86,
    classRanking: "Top 5%",
    hsk: 5,
    englishLevel: "Fluent",
    otherLanguages: ["Vietnamese (Native)"],
    skills: ["Python", "SQL", "Data Visualization", "Machine Learning", "Mandarin (HSK 5)", "Tableau"],
    projects: [
      {
        title: "Export Demand Forecast",
        description: "Modeled monthly demand for Vietnamese coffee exports into East China using customs data, weather signals, and seasonal retail indicators.",
        tags: ["Python", "Time Series", "Pandas"],
      },
      {
        title: "Student Career Pulse Dashboard",
        description: "Designed a dashboard for tracking job-search progress among classmates, highlighting response gaps by industry and language requirement.",
        tags: ["Tableau", "Survey Design", "Analytics"],
      },
      {
        title: "Mandarin Resume Keyword Miner",
        description: "Compared Chinese job descriptions against student resumes and surfaced missing technical keywords in Vietnamese and English.",
        tags: ["NLP", "Mandarin", "Resume Parsing"],
      },
    ],
    bio: "I enjoy turning scattered information into decisions people can act on. I am especially interested in analytics roles that connect China and Southeast Asia.",
    headline: "Data analyst bridging China-Vietnam market insights",
    verified: true,
    lookingFor: "Full-time",
    availableFrom: "July 2026",
    preferredLocations: ["Hangzhou", "Shanghai", "Shenzhen"],
    activities: ["Vietnamese Student Association Treasurer", "Women in Data Study Circle", "ZJUT Badminton Club"],
    awards: [
      {
        title: "Outstanding International Graduate Candidate",
        year: 2026,
        description: "Selected by faculty for consistent research output and peer mentoring.",
      },
      {
        title: "Provincial Data Challenge Second Prize",
        year: 2025,
        description: "Placed second in a student competition on retail demand prediction.",
      },
    ],
    coursesCompleted: 32,
    responseTime: "Within 12 hours",
    lastActive: "45 minutes ago",
    profileStrength: 94,
  },
  {
    id: "stu-003",
    name: "Ayesha Khan",
    initials: "AK",
    nationality: "Pakistan",
    nationalityFlag: "🇵🇰",
    year: 3,
    major: "Mechatronics Engineering",
    category: "Engineering",
    gpa: 3.58,
    classRanking: "Top 20%",
    hsk: 3,
    englishLevel: "Fluent",
    otherLanguages: ["Urdu (Native)", "Punjabi"],
    skills: ["Arduino", "SolidWorks", "PLC Basics", "Python", "Technical Documentation", "Mandarin (HSK 3)"],
    projects: [
      {
        title: "Low-cost Sorting Arm",
        description: "Built a small conveyor and robotic arm that classifies colored parts for a manufacturing lab demonstration.",
        tags: ["Arduino", "Sensors", "SolidWorks"],
      },
      {
        title: "Factory Safety Checklist App",
        description: "Designed a bilingual checklist prototype for student lab teams to record machine setup and safety checks before experiments.",
        tags: ["Figma", "Process Safety", "Mandarin"],
      },
      {
        title: "Motor Fault Study",
        description: "Analyzed vibration readings from small DC motors and documented early warning patterns for misalignment and loose mounting.",
        tags: ["Python", "Signal Analysis", "Maintenance"],
      },
    ],
    bio: "I am happiest when a design leaves the sketchbook and starts moving on a bench. I want to learn from production teams that care about safety and precision.",
    headline: "Mechatronics student building practical automation prototypes",
    verified: true,
    lookingFor: "Both",
    availableFrom: "August 2026",
    preferredLocations: ["Hangzhou", "Ningbo", "Suzhou"],
    activities: ["Robotics Lab Assistant", "International Women in Engineering Group"],
    awards: [
      {
        title: "Mechanical Design Studio Merit Award",
        year: 2025,
        description: "Awarded for a reliable low-cost automation prototype and clear build documentation.",
      },
    ],
    coursesCompleted: 25,
    responseTime: "Within 1 day",
    lastActive: "1 day ago",
    profileStrength: 79,
  },
  {
    id: "stu-004",
    name: "Arjun Mehta",
    initials: "AM",
    nationality: "India",
    nationalityFlag: "🇮🇳",
    year: 2,
    major: "Electrical Engineering and Automation",
    category: "Engineering",
    gpa: 3.41,
    classRanking: "Top 35%",
    hsk: 2,
    englishLevel: "Native",
    otherLanguages: ["Hindi (Native)", "Gujarati"],
    skills: ["Circuit Simulation", "MATLAB", "Embedded C", "Technical Presentations", "Power Systems", "Mandarin (HSK 2)"],
    projects: [
      {
        title: "Dorm Energy Monitor",
        description: "Assembled a prototype meter that estimates room-level electricity use and flags unusual consumption patterns for student housing.",
        tags: ["Embedded C", "Sensors", "Energy"],
      },
      {
        title: "Solar Charging Feasibility Study",
        description: "Compared panel placement options around campus paths and calculated expected output during Hangzhou's seasonal weather shifts.",
        tags: ["MATLAB", "Renewables", "Field Research"],
      },
    ],
    bio: "I am still early in my engineering path, but I learn fast when the work has a visible outcome. Energy systems and hardware testing are where I want to grow.",
    headline: "Electrical engineering student interested in energy systems",
    verified: true,
    lookingFor: "Internship",
    availableFrom: "July 2026",
    preferredLocations: ["Hangzhou", "Guangzhou", "Remote"],
    activities: ["ZJUT Electronics Workshop", "International Student Cricket Team"],
    awards: [
      {
        title: "First-year Academic Progress Recognition",
        year: 2025,
        description: "Recognized for strong improvement across core engineering courses.",
      },
    ],
    coursesCompleted: 18,
    responseTime: "Within 48 hours",
    lastActive: "3 hours ago",
    profileStrength: 67,
  },
  {
    id: "stu-005",
    name: "Putri Aulia Santoso",
    initials: "PS",
    nationality: "Indonesia",
    nationalityFlag: "🇮🇩",
    year: 3,
    major: "International Business",
    category: "Business",
    gpa: 3.64,
    classRanking: "Top 20%",
    hsk: 4,
    englishLevel: "Fluent",
    otherLanguages: ["Indonesian (Native)", "Javanese"],
    skills: ["Market Research", "E-commerce Operations", "Excel Modeling", "Mandarin (HSK 4)", "Social Commerce", "Customer Interviews"],
    projects: [
      {
        title: "Indonesia Cross-border Beauty Study",
        description: "Interviewed Indonesian students and sellers to map trust factors for Chinese beauty brands entering Shopee and TikTok Shop.",
        tags: ["Market Research", "E-commerce", "Southeast Asia"],
      },
      {
        title: "Live Commerce Campaign Plan",
        description: "Planned a bilingual launch calendar for a campus snack brand, including KOL shortlist, scripts, and discount testing.",
        tags: ["Social Commerce", "Campaign Planning", "Mandarin"],
      },
      {
        title: "SME Export Cost Calculator",
        description: "Built an Excel tool for comparing small-batch shipping routes from Zhejiang suppliers to Jakarta resellers.",
        tags: ["Excel", "Logistics", "Pricing"],
      },
    ],
    bio: "I like finding the small customer detail that changes a launch plan. My goal is to help Chinese brands enter Southeast Asia with more local understanding.",
    headline: "International business student focused on Indonesia-China commerce",
    verified: true,
    lookingFor: "Internship",
    availableFrom: "June 2026",
    preferredLocations: ["Hangzhou", "Shanghai", "Jakarta"],
    activities: ["ASEAN Student Business Forum", "Indonesian Culture Night Organizer", "Case Competition Team"],
    awards: [
      {
        title: "International Business Case Competition Finalist",
        year: 2025,
        description: "Presented a Southeast Asia market entry strategy for a Chinese consumer brand.",
      },
    ],
    coursesCompleted: 27,
    responseTime: "Within 12 hours",
    lastActive: "5 hours ago",
    profileStrength: 84,
  },
  {
    id: "stu-006",
    name: "Aigerim Nurlanova",
    initials: "AN",
    nationality: "Kazakhstan",
    nationalityFlag: "🇰🇿",
    year: 4,
    major: "Marketing and E-commerce",
    category: "Business",
    gpa: 3.78,
    classRanking: "Top 10%",
    hsk: 5,
    englishLevel: "Proficient",
    otherLanguages: ["Kazakh (Native)", "Russian"],
    skills: ["Brand Strategy", "Content Analytics", "Mandarin (HSK 5)", "Russian Localization", "CRM Segmentation", "Canva"],
    projects: [
      {
        title: "Central Asia Buyer Persona Map",
        description: "Created persona profiles for young Kazakh consumers buying Chinese electronics through marketplaces and reseller channels.",
        tags: ["Consumer Research", "Localization", "CRM"],
      },
      {
        title: "Bilingual Product Page Audit",
        description: "Reviewed Russian-language listings from Zhejiang suppliers and rewrote product copy to reduce ambiguity around warranty and shipping.",
        tags: ["Russian", "Copywriting", "E-commerce"],
      },
      {
        title: "WeChat Retention Mini-study",
        description: "Analyzed student club WeChat engagement and recommended message timing changes that lifted event signups.",
        tags: ["WeChat", "Analytics", "Retention"],
      },
    ],
    bio: "I am drawn to the space between brand voice and data. I can translate customer feedback across Kazakh, Russian, Chinese, and English contexts.",
    headline: "Marketing analyst for China-Central Asia consumer growth",
    verified: true,
    lookingFor: "Full-time",
    availableFrom: "July 2026",
    preferredLocations: ["Hangzhou", "Shanghai", "Almaty"],
    activities: ["Central Asia Student Network Lead", "ZJUT Marketing Lab", "Peer Mandarin Tutor"],
    awards: [
      {
        title: "Dean's List for International Students",
        year: 2025,
        description: "Recognized for top academic performance in marketing and analytics courses.",
      },
      {
        title: "Best Localization Proposal",
        year: 2024,
        description: "Won a class competition for adapting Chinese product messaging to Central Asian buyers.",
      },
    ],
    coursesCompleted: 31,
    responseTime: "Within 24 hours",
    lastActive: "6 hours ago",
    profileStrength: 91,
  },
  {
    id: "stu-007",
    name: "Chinedu Okafor",
    initials: "CO",
    nationality: "Nigeria",
    nationalityFlag: "🇳🇬",
    year: 3,
    major: "Logistics and Supply Chain Management",
    category: "Business",
    gpa: 3.33,
    classRanking: "Top 40%",
    hsk: 3,
    englishLevel: "Native",
    otherLanguages: ["Igbo", "Pidgin English"],
    skills: ["Supplier Coordination", "Excel", "Inventory Planning", "Incoterms", "Mandarin (HSK 3)", "Negotiation"],
    projects: [
      {
        title: "Hangzhou-Lagos Shipping Comparison",
        description: "Compared air, sea, and hybrid shipping paths for small electronics sellers, including customs timing and working capital impact.",
        tags: ["Logistics", "Excel", "Trade"],
      },
      {
        title: "Warehouse Slotting Exercise",
        description: "Used order frequency data to redesign a classroom warehouse layout and reduce simulated pick time.",
        tags: ["Inventory", "Operations", "Process Design"],
      },
      {
        title: "Supplier Message Templates",
        description: "Created bilingual templates for clarifying MOQ, packaging, and inspection terms with Zhejiang suppliers.",
        tags: ["Mandarin", "Supplier Management", "Trade"],
      },
    ],
    bio: "I ask direct questions and keep details moving. I want work where China-Africa trade becomes less confusing for the people actually placing orders.",
    headline: "Supply chain student focused on China-Africa trade operations",
    verified: true,
    lookingFor: "Both",
    availableFrom: "September 2026",
    preferredLocations: ["Hangzhou", "Yiwu", "Guangzhou"],
    activities: ["African Students Association Events Coordinator", "Trade Simulation Club"],
    awards: [
      {
        title: "Operations Simulation Team Award",
        year: 2025,
        description: "Led supplier communication during a cross-border logistics simulation.",
      },
    ],
    coursesCompleted: 24,
    responseTime: "Within 1 day",
    lastActive: "18 hours ago",
    profileStrength: 72,
  },
  {
    id: "stu-008",
    name: "Bolor-Erdene Ganbold",
    initials: "BG",
    nationality: "Mongolia",
    nationalityFlag: "🇲🇳",
    year: 4,
    major: "Chinese Language and Culture",
    category: "Language",
    gpa: 3.9,
    classRanking: "Top 5%",
    hsk: 6,
    englishLevel: "Proficient",
    otherLanguages: ["Mongolian (Native)", "Russian"],
    skills: ["Mandarin (HSK 6)", "Interpretation", "Business Writing", "Cultural Mediation", "Public Speaking", "Translation QA"],
    projects: [
      {
        title: "Factory Visit Interpreter Guide",
        description: "Prepared bilingual terminology sheets for Mongolian student visitors touring Zhejiang manufacturing sites.",
        tags: ["Interpretation", "Manufacturing", "Terminology"],
      },
      {
        title: "Mongolian Alumni Interview Series",
        description: "Interviewed graduates working in China and translated their career advice into Mandarin and Mongolian for incoming students.",
        tags: ["Translation", "Interviewing", "Content"],
      },
      {
        title: "Business Etiquette Workshop",
        description: "Designed a workshop on meeting etiquette, gifting, and follow-up messages for students attending Chinese employer events.",
        tags: ["Training", "Culture", "Mandarin"],
      },
    ],
    bio: "I love the exact moment when people realize they understand each other. My work is translation, but also trust-building.",
    headline: "Mandarin-Mongolian interpreter for business and campus settings",
    verified: true,
    lookingFor: "Full-time",
    availableFrom: "June 2026",
    preferredLocations: ["Hangzhou", "Beijing", "Ulaanbaatar"],
    activities: ["International Student Host Team", "Mandarin Debate Club", "Mongolian Culture Booth Lead"],
    awards: [
      {
        title: "HSK 6 High Score Recognition",
        year: 2025,
        description: "Recognized by language faculty for outstanding HSK 6 exam performance.",
      },
      {
        title: "Best Student Interpreter",
        year: 2024,
        description: "Selected for interpretation support during international college orientation.",
      },
    ],
    coursesCompleted: 34,
    responseTime: "Within 6 hours",
    lastActive: "1 hour ago",
    profileStrength: 95,
  },
  {
    id: "stu-009",
    name: "Daria Volkova",
    initials: "DV",
    nationality: "Russia",
    nationalityFlag: "🇷🇺",
    year: 3,
    major: "Translation and Intercultural Communication",
    category: "Language",
    gpa: 3.62,
    classRanking: "Top 20%",
    hsk: 5,
    englishLevel: "Fluent",
    otherLanguages: ["Russian (Native)", "German"],
    skills: ["Russian Localization", "Mandarin (HSK 5)", "UX Writing", "Subtitle Editing", "Research Interviews", "Terminology Management"],
    projects: [
      {
        title: "Russian App Onboarding Rewrite",
        description: "Rewrote onboarding copy for a class fintech prototype so Russian-speaking users could complete identity steps without confusion.",
        tags: ["Localization", "UX Writing", "Fintech"],
      },
      {
        title: "Short Video Subtitle Lab",
        description: "Translated and timed Mandarin product videos into Russian, focusing on tone, pacing, and screen-safe line length.",
        tags: ["Subtitles", "Mandarin", "Content"],
      },
      {
        title: "Interview Glossary for HR",
        description: "Built a Mandarin-Russian glossary of common hiring terms for international students preparing for Chinese interviews.",
        tags: ["Terminology", "HR", "Translation"],
      },
    ],
    bio: "I care about words that let people finish a task, not just words that sound pretty. Localization feels strongest when users never notice it.",
    headline: "Russian localization specialist with Mandarin product fluency",
    verified: true,
    lookingFor: "Internship",
    availableFrom: "July 2026",
    preferredLocations: ["Hangzhou", "Shanghai", "Remote"],
    activities: ["ZJUT Translation Workshop", "International Film Subtitle Night"],
    awards: [
      {
        title: "Intercultural Communication Essay Prize",
        year: 2025,
        description: "Awarded for research on tone adaptation in Chinese-to-Russian product messaging.",
      },
    ],
    coursesCompleted: 28,
    responseTime: "Within 24 hours",
    lastActive: "8 hours ago",
    profileStrength: 82,
  },
  {
    id: "stu-010",
    name: "Omar Hassan",
    initials: "OH",
    nationality: "Egypt",
    nationalityFlag: "🇪🇬",
    year: 4,
    major: "Pharmaceutical Sciences",
    category: "Health",
    gpa: 3.69,
    classRanking: "Top 15%",
    hsk: 4,
    englishLevel: "Fluent",
    otherLanguages: ["Arabic (Native)"],
    skills: ["Pharmacology", "Lab Documentation", "Clinical Research Basics", "Mandarin (HSK 4)", "Regulatory Research", "SPSS"],
    projects: [
      {
        title: "Medication Label Comprehension Study",
        description: "Surveyed international students on Chinese OTC medication labels and proposed clearer bilingual safety notes.",
        tags: ["Public Health", "Survey", "Mandarin"],
      },
      {
        title: "Antibiotic Use Literature Review",
        description: "Reviewed recent China and MENA region studies on antibiotic self-medication and summarized prevention themes.",
        tags: ["Research", "Pharmacology", "Evidence Review"],
      },
      {
        title: "Lab SOP Translation Set",
        description: "Translated common laboratory safety procedures into English and Arabic for new international students in health labs.",
        tags: ["Translation", "Lab Safety", "Arabic"],
      },
    ],
    bio: "I want health information to be clear before people are already anxious. My background helps me connect pharmacy knowledge with international patient needs.",
    headline: "Pharmaceutical sciences student interested in patient safety",
    verified: true,
    lookingFor: "Full-time",
    availableFrom: "August 2026",
    preferredLocations: ["Hangzhou", "Shanghai", "Cairo"],
    activities: ["Health Science Reading Group", "International Student First Aid Volunteer", "Arabic Culture Association"],
    awards: [
      {
        title: "Pharmaceutical Literature Review Distinction",
        year: 2025,
        description: "Recognized for a high-scoring review on antibiotic self-medication behavior.",
      },
    ],
    coursesCompleted: 33,
    responseTime: "Within 24 hours",
    lastActive: "12 hours ago",
    profileStrength: 86,
  },
  {
    id: "stu-011",
    name: "Selam Tesfaye",
    initials: "ST",
    nationality: "Ethiopia",
    nationalityFlag: "🇪🇹",
    year: 3,
    major: "Public Health",
    category: "Health",
    gpa: 3.47,
    classRanking: "Top 30%",
    hsk: 3,
    englishLevel: "Fluent",
    otherLanguages: ["Amharic (Native)", "Oromo"],
    skills: ["Community Outreach", "Health Surveys", "Data Cleaning", "Mandarin (HSK 3)", "Workshop Facilitation", "Excel"],
    projects: [
      {
        title: "International Student Sleep Survey",
        description: "Collected and cleaned survey data on sleep, study pressure, and adaptation challenges among international students.",
        tags: ["Survey Design", "Excel", "Student Health"],
      },
      {
        title: "Clinic Visit Phrase Card",
        description: "Created a pocket guide with Mandarin phrases for registration, symptoms, payment, and follow-up instructions.",
        tags: ["Mandarin", "Patient Support", "Design"],
      },
      {
        title: "Healthy Canteen Choices Workshop",
        description: "Led a small workshop on nutrition labels and affordable meal combinations for students new to Chinese campus dining.",
        tags: ["Health Education", "Facilitation", "Nutrition"],
      },
    ],
    bio: "I notice when people are too shy to ask for help. Public health, to me, starts with making support easier to reach.",
    headline: "Public health student focused on student wellbeing access",
    verified: true,
    lookingFor: "Internship",
    availableFrom: "June 2026",
    preferredLocations: ["Hangzhou", "Ningbo", "Addis Ababa"],
    activities: ["International Student Wellness Volunteer", "African Students Association", "Campus Running Group"],
    awards: [
      {
        title: "Community Service Recognition",
        year: 2025,
        description: "Recognized for organizing peer support sessions during exam season.",
      },
    ],
    coursesCompleted: 23,
    responseTime: "Within 48 hours",
    lastActive: "2 days ago",
    profileStrength: 74,
  },
  {
    id: "stu-012",
    name: "Sok Sreyneang",
    initials: "SS",
    nationality: "Cambodia",
    nationalityFlag: "🇰🇭",
    year: 2,
    major: "Digital Media Design",
    category: "Other",
    gpa: 3.52,
    classRanking: "Top 25%",
    hsk: 4,
    englishLevel: "Proficient",
    otherLanguages: ["Khmer (Native)"],
    skills: ["Figma", "Motion Graphics", "User Research", "Mandarin (HSK 4)", "Brand Systems", "Adobe Illustrator"],
    projects: [
      {
        title: "Khmer Student Arrival Kit",
        description: "Designed a visual guide for Cambodian freshmen covering SIM cards, banking, dorm check-in, and campus transport.",
        tags: ["Figma", "Service Design", "Khmer"],
      },
      {
        title: "Reverse Fair Booth Identity",
        description: "Created a flexible poster and badge system for a student-led career showcase where profiles are the main attraction.",
        tags: ["Branding", "Print Design", "Career Fair"],
      },
      {
        title: "Canteen Menu Icon Set",
        description: "Illustrated dietary icons for spicy, halal-friendly, vegetarian, and nut-containing dishes in campus canteens.",
        tags: ["Illustration", "Accessibility", "Food Design"],
      },
    ],
    bio: "I design because I remember what it feels like to arrive somewhere and not understand the signs. Clear visuals can make a new place feel less intimidating.",
    headline: "Digital media designer making campus services easier to read",
    verified: true,
    lookingFor: "Internship",
    availableFrom: "July 2026",
    preferredLocations: ["Hangzhou", "Shanghai", "Phnom Penh"],
    activities: ["Design Volunteer for International College", "Cambodian Student Community", "Campus Photography Walks"],
    awards: [
      {
        title: "Student Visual Communication Showcase Selection",
        year: 2025,
        description: "Selected for a campus exhibition featuring practical design for international student services.",
      },
    ],
    coursesCompleted: 19,
    responseTime: "Within 1 day",
    lastActive: "4 hours ago",
    profileStrength: 76,
  },
];
