import type { Student } from "./types";

export const students: Student[] = [
  {
    id: "stu-001",
    name: "Nattapong Saetang",
    initials: "NS",
    nationality: "Thailand",
    nationalityFlag: "🇹🇭",
    year: 3,
    major: "Software Engineering",
    category: "Engineering",
    gpa: 3.72,
    classRanking: "Top 15%",
    hsk: 4,
    englishLevel: "Fluent",
    otherLanguages: ["Thai (Native)"],
    skills: ["TypeScript", "React", "Python", "UI Prototyping", "Mandarin (HSK 4)", "Cross-cultural Research"],
    projects: [
      {
        title: "ZJUT Campus Navigator",
        description: "Built a bilingual mobile map that helps new international students find classrooms, canteens, and bus gates without asking for directions every time.",
        tags: ["React Native", "Maps API", "i18n"],
      },
      {
        title: "Scholarship Deadline Tracker",
        description: "Created a web dashboard that aggregates university notices and reminds students before document submission windows close.",
        tags: ["Next.js", "PostgreSQL", "Automation"],
      },
      {
        title: "Dorm Maintenance Chatbot",
        description: "Prototyped a Mandarin-English chatbot for reporting repairs, with structured handoff messages for campus staff.",
        tags: ["Python", "NLP", "Service Design"],
      },
    ],
    bio: "I like building practical tools for moments when language makes simple tasks feel heavy. My best work sits between product, code, and international student life.",
    headline: "Software engineer focused on cross-cultural student products",
    verified: true,
    lookingFor: "Internship",
    availableFrom: "June 2026",
    preferredLocations: ["Hangzhou", "Shanghai", "Remote"],
    activities: ["International Student Association Tech Lead", "ZJUT Coding Club", "Thai Student Volunteer Group"],
    awards: [
      {
        title: "ZJUT International Student Excellence Award",
        year: 2025,
        description: "Recognized for academic performance and peer support work in the international college.",
      },
      {
        title: "Campus Innovation Sprint Finalist",
        year: 2024,
        description: "Reached the final round with a multilingual student services prototype.",
      },
    ],
    coursesCompleted: 26,
    responseTime: "Within 24 hours",
    lastActive: "2 hours ago",
    profileStrength: 88,
  },
  {
    id: "stu-002",
    name: "Nguyen Thi Minh Linh",
    initials: "NL",
    nationality: "Vietnam",
    nationalityFlag: "🇻🇳",
    year: 4,
    major: "Data Science and Big Data Technology",
    category: "Engineering",
    gpa: 3.86,
    classRanking: "Top 5%",
    hsk: 5,
    englishLevel: "Fluent",
    otherLanguages: ["Vietnamese (Native)"],
    skills: ["Python", "SQL", "Data Visualization", "Machine Learning", "Mandarin (HSK 5)", "Tableau"],
    projects: [
      {
        title: "Export Demand Forecast",
        description: "Modeled monthly demand for Vietnamese coffee exports into East China using customs data, weather signals, and seasonal retail indicators.",
        tags: ["Python", "Time Series", "Pandas"],
      },
      {
        title: "Student Career Pulse Dashboard",
        description: "Designed a dashboard for tracking job-search progress among classmates, highlighting response gaps by industry and language requirement.",
        tags: ["Tableau", "Survey Design", "Analytics"],
      },
      {
        title: "Mandarin Resume Keyword Miner",
        description: "Compared Chinese job descriptions against student resumes and surfaced missing technical keywords in Vietnamese and English.",
        tags: ["NLP", "Mandarin", "Resume Parsing"],
      },
    ],
    bio: "I enjoy turning scattered information into decisions people can act on. I am especially interested in analytics roles that connect China and Southeast Asia.",
    headline: "Data analyst bridging China-Vietnam market insights",
    verified: true,
    lookingFor: "Full-time",
    availableFrom: "July 2026",
    preferredLocations: ["Hangzhou", "Shanghai", "Shenzhen"],
    activities: ["Vietnamese Student Association Treasurer", "Women in Data Study Circle", "ZJUT Badminton Club"],
    awards: [
      {
        title: "Outstanding International Graduate Candidate",
        year: 2026,
        description: "Selected by faculty for consistent research output and peer mentoring.",
      },
      {
        title: "Provincial Data Challenge Second Prize",
        year: 2025,
        description: "Placed second in a student competition on retail demand prediction.",
      },
    ],
    coursesCompleted: 32,
    responseTime: "Within 12 hours",
    lastActive: "45 minutes ago",
    profileStrength: 94,
  },
  {
    id: "stu-003",
    name: "Ayesha Khan",
    initials: "AK",
    nationality: "Pakistan",
    nationalityFlag: "🇵🇰",
    year: 3,
    major: "Mechatronics Engineering",
    category: "Engineering",
    gpa: 3.58,
    classRanking: "Top 20%",
    hsk: 3,
    englishLevel: "Fluent",
    otherLanguages: ["Urdu (Native)", "Punjabi"],
    skills: ["Arduino", "SolidWorks", "PLC Basics", "Python", "Technical Documentation", "Mandarin (HSK 3)"],
    projects: [
      {
        title: "Low-cost Sorting Arm",
        description: "Built a small conveyor and robotic arm that classifies colored parts for a manufacturing lab demonstration.",
        tags: ["Arduino", "Sensors", "SolidWorks"],
      },
      {
        title: "Factory Safety Checklist App",
        description: "Designed a bilingual checklist prototype for student lab teams to record machine setup and safety checks before experiments.",
        tags: ["Figma", "Process Safety", "Mandarin"],
      },
      {
        title: "Motor Fault Study",
        description: "Analyzed vibration readings from small DC motors and documented early warning patterns for misalignment and loose mounting.",
        tags: ["Python", "Signal Analysis", "Maintenance"],
      },
    ],
    bio: "I am happiest when a design leaves the sketchbook and starts moving on a bench. I want to learn from production teams that care about safety and precision.",
    headline: "Mechatronics student building practical automation prototypes",
    verified: true,
    lookingFor: "Both",
    availableFrom: "August 2026",
    preferredLocations: ["Hangzhou", "Ningbo", "Suzhou"],
    activities: ["Robotics Lab Assistant", "International Women in Engineering Group"],
    awards: [
      {
        title: "Mechanical Design Studio Merit Award",
        year: 2025,
        description: "Awarded for a reliable low-cost automation prototype and clear build documentation.",
      },
    ],
    coursesCompleted: 25,
    responseTime: "Within 1 day",
    lastActive: "1 day ago",
    profileStrength: 79,
  },
  {
    id: "stu-004",
    name: "Arjun Mehta",
    initials: "AM",
    nationality: "India",
    nationalityFlag: "🇮🇳",
    year: 2,
    major: "Electrical Engineering and Automation",
    category: "Engineering",
    gpa: 3.41,
    classRanking: "Top 35%",
    hsk: 2,
    englishLevel: "Native",
    otherLanguages: ["Hindi (Native)", "Gujarati"],
    skills: ["Circuit Simulation", "MATLAB", "Embedded C", "Technical Presentations", "Power Systems", "Mandarin (HSK 2)"],
    projects: [
      {
        title: "Dorm Energy Monitor",
        description: "Assembled a prototype meter that estimates room-level electricity use and flags unusual consumption patterns for student housing.",
        tags: ["Embedded C", "Sensors", "Energy"],
      },
      {
        title: "Solar Charging Feasibility Study",
        description: "Compared panel placement options around campus paths and calculated expected output during Hangzhou's seasonal weather shifts.",
        tags: ["MATLAB", "Renewables", "Field Research"],
      },
    ],
    bio: "I am still early in my engineering path, but I learn fast when the work has a visible outcome. Energy systems and hardware testing are where I want to grow.",
    headline: "Electrical engineering student interested in energy systems",
    verified: true,
    lookingFor: "Internship",
    availableFrom: "July 2026",
    preferredLocations: ["Hangzhou", "Guangzhou", "Remote"],
    activities: ["ZJUT Electronics Workshop", "International Student Cricket Team"],
    awards: [
      {
        title: "First-year Academic Progress Recognition",
        year: 2025,
        description: "Recognized for strong improvement across core engineering courses.",
      },
    ],
    coursesCompleted: 18,
    responseTime: "Within 48 hours",
    lastActive: "3 hours ago",
    profileStrength: 67,
  },
  {
    id: "stu-005",
    name: "Putri Aulia Santoso",
    initials: "PS",
    nationality: "Indonesia",
    nationalityFlag: "🇮🇩",
    year: 3,
    major: "International Business",
    category: "Business",
    gpa: 3.64,
    classRanking: "Top 20%",
    hsk: 4,
    englishLevel: "Fluent",
    otherLanguages: ["Indonesian (Native)", "Javanese"],
    skills: ["Market Research", "E-commerce Operations", "Excel Modeling", "Mandarin (HSK 4)", "Social Commerce", "Customer Interviews"],
    projects: [
      {
        title: "Indonesia Cross-border Beauty Study",
        description: "Interviewed Indonesian students and sellers to map trust factors for Chinese beauty brands entering Shopee and TikTok Shop.",
        tags: ["Market Research", "E-commerce", "Southeast Asia"],
      },
      {
        title: "Live Commerce Campaign Plan",
        description: "Planned a bilingual launch calendar for a campus snack brand, including KOL shortlist, scripts, and discount testing.",
        tags: ["Social Commerce", "Campaign Planning", "Mandarin"],
      },
      {
        title: "SME Export Cost Calculator",
        description: "Built an Excel tool for comparing small-batch shipping routes from Zhejiang suppliers to Jakarta resellers.",
        tags: ["Excel", "Logistics", "Pricing"],
      },
    ],
    bio: "I like finding the small customer detail that changes a launch plan. My goal is to help Chinese brands enter Southeast Asia with more local understanding.",
    headline: "International business student focused on Indonesia-China commerce",
    verified: true,
    lookingFor: "Internship",
    availableFrom: "June 2026",
    preferredLocations: ["Hangzhou", "Shanghai", "Jakarta"],
    activities: ["ASEAN Student Business Forum", "Indonesian Culture Night Organizer", "Case Competition Team"],
    awards: [
      {
        title: "International Business Case Competition Finalist",
        year: 2025,
        description: "Presented a Southeast Asia market entry strategy for a Chinese consumer brand.",
      },
    ],
    coursesCompleted: 27,
    responseTime: "Within 12 hours",
    lastActive: "5 hours ago",
    profileStrength: 84,
  },
  {
    id: "stu-006",
    name: "Aigerim Nurlanova",
    initials: "AN",
    nationality: "Kazakhstan",
    nationalityFlag: "🇰🇿",
    year: 4,
    major: "Marketing and E-commerce",
    category: "Business",
    gpa: 3.78,
    classRanking: "Top 10%",
    hsk: 5,
    englishLevel: "Proficient",
    otherLanguages: ["Kazakh (Native)", "Russian"],
    skills: ["Brand Strategy", "Content Analytics", "Mandarin (HSK 5)", "Russian Localization", "CRM Segmentation", "Canva"],
    projects: [
      {
        title: "Central Asia Buyer Persona Map",
        description: "Created persona profiles for young Kazakh consumers buying Chinese electronics through marketplaces and reseller channels.",
        tags: ["Consumer Research", "Localization", "CRM"],
      },
      {
        title: "Bilingual Product Page Audit",
        description: "Reviewed Russian-language listings from Zhejiang suppliers and rewrote product copy to reduce ambiguity around warranty and shipping.",
        tags: ["Russian", "Copywriting", "E-commerce"],
      },
      {
        title: "WeChat Retention Mini-study",
        description: "Analyzed student club WeChat engagement and recommended message timing changes that lifted event signups.",
        tags: ["WeChat", "Analytics", "Retention"],
      },
    ],
    bio: "I am drawn to the space between brand voice and data. I can translate customer feedback across Kazakh, Russian, Chinese, and English contexts.",
    headline: "Marketing analyst for China-Central Asia consumer growth",
    verified: true,
    lookingFor: "Full-time",
    availableFrom: "July 2026",
    preferredLocations: ["Hangzhou", "Shanghai", "Almaty"],
    activities: ["Central Asia Student Network Lead", "ZJUT Marketing Lab", "Peer Mandarin Tutor"],
    awards: [
      {
        title: "Dean's List for International Students",
        year: 2025,
        description: "Recognized for top academic performance in marketing and analytics courses.",
      },
      {
        title: "Best Localization Proposal",
        year: 2024,
        description: "Won a class competition for adapting Chinese product messaging to Central Asian buyers.",
      },
    ],
    coursesCompleted: 31,
    responseTime: "Within 24 hours",
    lastActive: "6 hours ago",
    profileStrength: 91,
  },
  {
    id: "stu-007",
    name: "Chinedu Okafor",
    initials: "CO",
    nationality: "Nigeria",
    nationalityFlag: "🇳🇬",
    year: 3,
    major: "Logistics and Supply Chain Management",
    category: "Business",
    gpa: 3.33,
    classRanking: "Top 40%",
    hsk: 3,
    englishLevel: "Native",
    otherLanguages: ["Igbo", "Pidgin English"],
    skills: ["Supplier Coordination", "Excel", "Inventory Planning", "Incoterms", "Mandarin (HSK 3)", "Negotiation"],
    projects: [
      {
        title: "Hangzhou-Lagos Shipping Comparison",
        description: "Compared air, sea, and hybrid shipping paths for small electronics sellers, including customs timing and working capital impact.",
        tags: ["Logistics", "Excel", "Trade"],
      },
      {
        title: "Warehouse Slotting Exercise",
        description: "Used order frequency data to redesign a classroom warehouse layout and reduce simulated pick time.",
        tags: ["Inventory", "Operations", "Process Design"],
      },
      {
        title: "Supplier Message Templates",
        description: "Created bilingual templates for clarifying MOQ, packaging, and inspection terms with Zhejiang suppliers.",
        tags: ["Mandarin", "Supplier Management", "Trade"],
      },
    ],
    bio: "I ask direct questions and keep details moving. I want work where China-Africa trade becomes less confusing for the people actually placing orders.",
    headline: "Supply chain student focused on China-Africa trade operations",
    verified: true,
    lookingFor: "Both",
    availableFrom: "September 2026",
    preferredLocations: ["Hangzhou", "Yiwu", "Guangzhou"],
    activities: ["African Students Association Events Coordinator", "Trade Simulation Club"],
    awards: [
      {
        title: "Operations Simulation Team Award",
        year: 2025,
        description: "Led supplier communication during a cross-border logistics simulation.",
      },
    ],
    coursesCompleted: 24,
    responseTime: "Within 1 day",
    lastActive: "18 hours ago",
    profileStrength: 72,
  },
  {
    id: "stu-008",
    name: "Bolor-Erdene Ganbold",
    initials: "BG",
    nationality: "Mongolia",
    nationalityFlag: "🇲🇳",
    year: 4,
    major: "Chinese Language and Culture",
    category: "Language",
    gpa: 3.9,
    classRanking: "Top 5%",
    hsk: 6,
    englishLevel: "Proficient",
    otherLanguages: ["Mongolian (Native)", "Russian"],
    skills: ["Mandarin (HSK 6)", "Interpretation", "Business Writing", "Cultural Mediation", "Public Speaking", "Translation QA"],
    projects: [
      {
        title: "Factory Visit Interpreter Guide",
        description: "Prepared bilingual terminology sheets for Mongolian student visitors touring Zhejiang manufacturing sites.",
        tags: ["Interpretation", "Manufacturing", "Terminology"],
      },
      {
        title: "Mongolian Alumni Interview Series",
        description: "Interviewed graduates working in China and translated their career advice into Mandarin and Mongolian for incoming students.",
        tags: ["Translation", "Interviewing", "Content"],
      },
      {
        title: "Business Etiquette Workshop",
        description: "Designed a workshop on meeting etiquette, gifting, and follow-up messages for students attending Chinese employer events.",
        tags: ["Training", "Culture", "Mandarin"],
      },
    ],
    bio: "I love the exact moment when people realize they understand each other. My work is translation, but also trust-building.",
    headline: "Mandarin-Mongolian interpreter for business and campus settings",
    verified: true,
    lookingFor: "Full-time",
    availableFrom: "June 2026",
    preferredLocations: ["Hangzhou", "Beijing", "Ulaanbaatar"],
    activities: ["International Student Host Team", "Mandarin Debate Club", "Mongolian Culture Booth Lead"],
    awards: [
      {
        title: "HSK 6 High Score Recognition",
        year: 2025,
        description: "Recognized by language faculty for outstanding HSK 6 exam performance.",
      },
      {
        title: "Best Student Interpreter",
        year: 2024,
        description: "Selected for interpretation support during international college orientation.",
      },
    ],
    coursesCompleted: 34,
    responseTime: "Within 6 hours",
    lastActive: "1 hour ago",
    profileStrength: 95,
  },
  {
    id: "stu-009",
    name: "Daria Volkova",
    initials: "DV",
    nationality: "Russia",
    nationalityFlag: "🇷🇺",
    year: 3,
    major: "Translation and Intercultural Communication",
    category: "Language",
    gpa: 3.62,
    classRanking: "Top 20%",
    hsk: 5,
    englishLevel: "Fluent",
    otherLanguages: ["Russian (Native)", "German"],
    skills: ["Russian Localization", "Mandarin (HSK 5)", "UX Writing", "Subtitle Editing", "Research Interviews", "Terminology Management"],
    projects: [
      {
        title: "Russian App Onboarding Rewrite",
        description: "Rewrote onboarding copy for a class fintech prototype so Russian-speaking users could complete identity steps without confusion.",
        tags: ["Localization", "UX Writing", "Fintech"],
      },
      {
        title: "Short Video Subtitle Lab",
        description: "Translated and timed Mandarin product videos into Russian, focusing on tone, pacing, and screen-safe line length.",
        tags: ["Subtitles", "Mandarin", "Content"],
      },
      {
        title: "Interview Glossary for HR",
        description: "Built a Mandarin-Russian glossary of common hiring terms for international students preparing for Chinese interviews.",
        tags: ["Terminology", "HR", "Translation"],
      },
    ],
    bio: "I care about words that let people finish a task, not just words that sound pretty. Localization feels strongest when users never notice it.",
    headline: "Russian localization specialist with Mandarin product fluency",
    verified: true,
    lookingFor: "Internship",
    availableFrom: "July 2026",
    preferredLocations: ["Hangzhou", "Shanghai", "Remote"],
    activities: ["ZJUT Translation Workshop", "International Film Subtitle Night"],
    awards: [
      {
        title: "Intercultural Communication Essay Prize",
        year: 2025,
        description: "Awarded for research on tone adaptation in Chinese-to-Russian product messaging.",
      },
    ],
    coursesCompleted: 28,
    responseTime: "Within 24 hours",
    lastActive: "8 hours ago",
    profileStrength: 82,
  },
  {
    id: "stu-010",
    name: "Omar Hassan",
    initials: "OH",
    nationality: "Egypt",
    nationalityFlag: "🇪🇬",
    year: 4,
    major: "Pharmaceutical Sciences",
    category: "Health",
    gpa: 3.69,
    classRanking: "Top 15%",
    hsk: 4,
    englishLevel: "Fluent",
    otherLanguages: ["Arabic (Native)"],
    skills: ["Pharmacology", "Lab Documentation", "Clinical Research Basics", "Mandarin (HSK 4)", "Regulatory Research", "SPSS"],
    projects: [
      {
        title: "Medication Label Comprehension Study",
        description: "Surveyed international students on Chinese OTC medication labels and proposed clearer bilingual safety notes.",
        tags: ["Public Health", "Survey", "Mandarin"],
      },
      {
        title: "Antibiotic Use Literature Review",
        description: "Reviewed recent China and MENA region studies on antibiotic self-medication and summarized prevention themes.",
        tags: ["Research", "Pharmacology", "Evidence Review"],
      },
      {
        title: "Lab SOP Translation Set",
        description: "Translated common laboratory safety procedures into English and Arabic for new international students in health labs.",
        tags: ["Translation", "Lab Safety", "Arabic"],
      },
    ],
    bio: "I want health information to be clear before people are already anxious. My background helps me connect pharmacy knowledge with international patient needs.",
    headline: "Pharmaceutical sciences student interested in patient safety",
    verified: true,
    lookingFor: "Full-time",
    availableFrom: "August 2026",
    preferredLocations: ["Hangzhou", "Shanghai", "Cairo"],
    activities: ["Health Science Reading Group", "International Student First Aid Volunteer", "Arabic Culture Association"],
    awards: [
      {
        title: "Pharmaceutical Literature Review Distinction",
        year: 2025,
        description: "Recognized for a high-scoring review on antibiotic self-medication behavior.",
      },
    ],
    coursesCompleted: 33,
    responseTime: "Within 24 hours",
    lastActive: "12 hours ago",
    profileStrength: 86,
  },
  {
    id: "stu-011",
    name: "Selam Tesfaye",
    initials: "ST",
    nationality: "Ethiopia",
    nationalityFlag: "🇪🇹",
    year: 3,
    major: "Public Health",
    category: "Health",
    gpa: 3.47,
    classRanking: "Top 30%",
    hsk: 3,
    englishLevel: "Fluent",
    otherLanguages: ["Amharic (Native)", "Oromo"],
    skills: ["Community Outreach", "Health Surveys", "Data Cleaning", "Mandarin (HSK 3)", "Workshop Facilitation", "Excel"],
    projects: [
      {
        title: "International Student Sleep Survey",
        description: "Collected and cleaned survey data on sleep, study pressure, and adaptation challenges among international students.",
        tags: ["Survey Design", "Excel", "Student Health"],
      },
      {
        title: "Clinic Visit Phrase Card",
        description: "Created a pocket guide with Mandarin phrases for registration, symptoms, payment, and follow-up instructions.",
        tags: ["Mandarin", "Patient Support", "Design"],
      },
      {
        title: "Healthy Canteen Choices Workshop",
        description: "Led a small workshop on nutrition labels and affordable meal combinations for students new to Chinese campus dining.",
        tags: ["Health Education", "Facilitation", "Nutrition"],
      },
    ],
    bio: "I notice when people are too shy to ask for help. Public health, to me, starts with making support easier to reach.",
    headline: "Public health student focused on student wellbeing access",
    verified: true,
    lookingFor: "Internship",
    availableFrom: "June 2026",
    preferredLocations: ["Hangzhou", "Ningbo", "Addis Ababa"],
    activities: ["International Student Wellness Volunteer", "African Students Association", "Campus Running Group"],
    awards: [
      {
        title: "Community Service Recognition",
        year: 2025,
        description: "Recognized for organizing peer support sessions during exam season.",
      },
    ],
    coursesCompleted: 23,
    responseTime: "Within 48 hours",
    lastActive: "2 days ago",
    profileStrength: 74,
  },
  {
    id: "stu-012",
    name: "Sok Sreyneang",
    initials: "SS",
    nationality: "Cambodia",
    nationalityFlag: "🇰🇭",
    year: 2,
    major: "Digital Media Design",
    category: "Other",
    gpa: 3.52,
    classRanking: "Top 25%",
    hsk: 4,
    englishLevel: "Proficient",
    otherLanguages: ["Khmer (Native)"],
    skills: ["Figma", "Motion Graphics", "User Research", "Mandarin (HSK 4)", "Brand Systems", "Adobe Illustrator"],
    projects: [
      {
        title: "Khmer Student Arrival Kit",
        description: "Designed a visual guide for Cambodian freshmen covering SIM cards, banking, dorm check-in, and campus transport.",
        tags: ["Figma", "Service Design", "Khmer"],
      },
      {
        title: "Reverse Fair Booth Identity",
        description: "Created a flexible poster and badge system for a student-led career showcase where profiles are the main attraction.",
        tags: ["Branding", "Print Design", "Career Fair"],
      },
      {
        title: "Canteen Menu Icon Set",
        description: "Illustrated dietary icons for spicy, halal-friendly, vegetarian, and nut-containing dishes in campus canteens.",
        tags: ["Illustration", "Accessibility", "Food Design"],
      },
    ],
    bio: "I design because I remember what it feels like to arrive somewhere and not understand the signs. Clear visuals can make a new place feel less intimidating.",
    headline: "Digital media designer making campus services easier to read",
    verified: true,
    lookingFor: "Internship",
    availableFrom: "July 2026",
    preferredLocations: ["Hangzhou", "Shanghai", "Phnom Penh"],
    activities: ["Design Volunteer for International College", "Cambodian Student Community", "Campus Photography Walks"],
    awards: [
      {
        title: "Student Visual Communication Showcase Selection",
        year: 2025,
        description: "Selected for a campus exhibition featuring practical design for international student services.",
      },
    ],
    coursesCompleted: 19,
    responseTime: "Within 1 day",
    lastActive: "4 hours ago",
    profileStrength: 76,
  },
  {
    id: "stu-013",
    name: "Nur Aisyah Rahman",
    initials: "NR",
    nationality: "Malaysia",
    nationalityFlag: "🇲🇾",
    year: 3,
    major: "Computer Science and Technology",
    category: "Engineering",
    gpa: 3.74,
    classRanking: "Top 12%",
    hsk: 4,
    englishLevel: "Fluent",
    otherLanguages: ["Malay (Native)"],
    skills: ["Java", "Spring Boot", "SQL", "React", "Mandarin (HSK 4)", "API Integration"],
    projects: [
      { title: "Halal Canteen Finder", description: "Built a searchable campus meal guide for Muslim students with filters for location, price, and dietary confidence.", tags: ["Java", "SQL", "Campus Services"] },
      { title: "Internship Application Tracker", description: "Designed a small workflow app that helps classmates track documents, deadlines, and employer replies.", tags: ["React", "Forms", "Productivity"] },
    ],
    bio: "I enjoy backend work that turns messy student life into something structured and dependable. I want to build tools people trust every day.",
    headline: "Full-stack developer building practical campus systems",
    verified: true,
    lookingFor: "Internship",
    availableFrom: "June 2026",
    preferredLocations: ["Hangzhou", "Kuala Lumpur", "Remote"],
    activities: ["Malaysian Student Association", "Backend Study Group"],
    awards: [{ title: "Database Systems Project Distinction", year: 2025, description: "Recognized for a reliable schema and clear API documentation in a team project." }],
    coursesCompleted: 27,
    responseTime: "Within 12 hours",
    lastActive: "30 minutes ago",
    profileStrength: 90,
  },
  {
    id: "stu-014",
    name: "Farhan Ahmed",
    initials: "FA",
    nationality: "Bangladesh",
    nationalityFlag: "🇧🇩",
    year: 4,
    major: "Civil Engineering",
    category: "Engineering",
    gpa: 3.52,
    classRanking: "Top 25%",
    hsk: 3,
    englishLevel: "Fluent",
    otherLanguages: ["Bengali (Native)"],
    skills: ["AutoCAD", "Structural Analysis", "Excel Modeling", "Site Documentation", "Mandarin (HSK 3)", "Safety Reporting"],
    projects: [
      { title: "Dormitory Evacuation Study", description: "Mapped emergency routes in student housing and proposed bilingual signage improvements for international residents.", tags: ["Safety", "AutoCAD", "Field Study"] },
      { title: "Low-cost Rainwater Plan", description: "Estimated rainwater capture potential for a small campus garden using local rainfall patterns and storage constraints.", tags: ["Sustainability", "Excel", "Civil Design"] },
    ],
    bio: "I like engineering work that makes shared spaces safer and easier to manage. My goal is to learn from teams that care about documentation as much as design.",
    headline: "Civil engineering student focused on safe campus infrastructure",
    verified: true,
    lookingFor: "Full-time",
    availableFrom: "July 2026",
    preferredLocations: ["Hangzhou", "Ningbo", "Dhaka"],
    activities: ["Civil Engineering Studio", "International Student Safety Volunteer"],
    awards: [{ title: "Applied Engineering Report Award", year: 2025, description: "Awarded for a clear risk assessment and practical signage proposal." }],
    coursesCompleted: 34,
    responseTime: "Within 1 day",
    lastActive: "7 hours ago",
    profileStrength: 80,
  },
  {
    id: "stu-015",
    name: "Prabin Shrestha",
    initials: "PS",
    nationality: "Nepal",
    nationalityFlag: "🇳🇵",
    year: 3,
    major: "Artificial Intelligence",
    category: "Engineering",
    gpa: 3.66,
    classRanking: "Top 18%",
    hsk: 4,
    englishLevel: "Proficient",
    otherLanguages: ["Nepali (Native)", "Hindi"],
    skills: ["Python", "Computer Vision", "Pandas", "Model Evaluation", "Mandarin (HSK 4)", "Data Annotation"],
    projects: [
      { title: "Canteen Queue Estimator", description: "Tested a lightweight computer vision model that estimates canteen line length from fixed camera snapshots.", tags: ["Python", "CV", "Model Testing"] },
      { title: "Bilingual Dataset Review", description: "Helped label Mandarin-English support messages and measured annotation consistency across student reviewers.", tags: ["Annotation", "QA", "NLP"] },
      { title: "Weather Impact Notebook", description: "Analyzed how rainy weeks affect campus bike usage and documented patterns for service planning.", tags: ["Pandas", "Visualization", "Mobility"] },
    ],
    bio: "I am interested in AI that is small enough to explain and useful enough to deploy. Clear evaluation is the part I care about most.",
    headline: "AI student focused on practical model evaluation",
    verified: true,
    lookingFor: "Internship",
    availableFrom: "August 2026",
    preferredLocations: ["Hangzhou", "Shanghai", "Kathmandu"],
    activities: ["AI Reading Group", "International Hiking Club"],
    awards: [{ title: "Machine Learning Lab Recognition", year: 2025, description: "Recognized for careful experiment tracking and readable notebooks." }],
    coursesCompleted: 26,
    responseTime: "Within 24 hours",
    lastActive: "2 hours ago",
    profileStrength: 85,
  },
  {
    id: "stu-016",
    name: "Kavindi Perera",
    initials: "KP",
    nationality: "Sri Lanka",
    nationalityFlag: "🇱🇰",
    year: 4,
    major: "Mechanical Engineering",
    category: "Engineering",
    gpa: 3.61,
    classRanking: "Top 20%",
    hsk: 3,
    englishLevel: "Fluent",
    otherLanguages: ["Sinhala (Native)"],
    skills: ["SolidWorks", "Thermal Systems", "MATLAB", "Technical Drawing", "Mandarin (HSK 3)", "Manufacturing Basics"],
    projects: [
      { title: "Portable Cooling Box", description: "Modeled a compact cooling box for medicine transport and compared insulation options under summer conditions.", tags: ["Thermal", "SolidWorks", "Testing"] },
      { title: "Workshop Tool Audit", description: "Created a bilingual inventory and maintenance checklist for shared tools in a mechanical lab.", tags: ["Documentation", "Safety", "Mandarin"] },
    ],
    bio: "I like mechanical design when it solves a real constraint. I work carefully, document decisions, and enjoy improving prototypes after testing.",
    headline: "Mechanical engineer interested in thermal product design",
    verified: true,
    lookingFor: "Full-time",
    availableFrom: "July 2026",
    preferredLocations: ["Hangzhou", "Suzhou", "Colombo"],
    activities: ["Mechanical Design Studio", "Women in Engineering Circle"],
    awards: [{ title: "Prototype Review Merit", year: 2025, description: "Selected for strong test notes and practical iteration on a cooling prototype." }],
    coursesCompleted: 35,
    responseTime: "Within 24 hours",
    lastActive: "9 hours ago",
    profileStrength: 83,
  },
  {
    id: "stu-017",
    name: "Somchai Vongdala",
    initials: "SV",
    nationality: "Laos",
    nationalityFlag: "🇱🇦",
    year: 2,
    major: "Software Engineering",
    category: "Engineering",
    gpa: 3.38,
    classRanking: "Top 40%",
    hsk: 3,
    englishLevel: "Intermediate",
    otherLanguages: ["Lao (Native)", "Thai"],
    skills: ["JavaScript", "Vue", "Node.js", "Git", "Mandarin (HSK 3)", "UI Testing"],
    projects: [
      { title: "Student Club Event Board", description: "Built a simple event board where international clubs can post bilingual activity details and deadlines.", tags: ["Vue", "Node.js", "Events"] },
      { title: "Dorm Issue Photo Log", description: "Prototyped a mobile-first form for students to submit maintenance photos with structured location data.", tags: ["Forms", "UX", "Campus Services"] },
    ],
    bio: "I am still building my confidence, but I learn quickly by shipping small features. I want an internship where code review helps me grow.",
    headline: "Junior web developer learning through campus product work",
    verified: true,
    lookingFor: "Internship",
    availableFrom: "September 2026",
    preferredLocations: ["Hangzhou", "Vientiane", "Remote"],
    activities: ["ASEAN Student Tech Circle", "Frontend Practice Group"],
    awards: [{ title: "Frontend Fundamentals Progress Award", year: 2025, description: "Recognized for steady improvement and helpful peer demos." }],
    coursesCompleted: 17,
    responseTime: "Within 48 hours",
    lastActive: "1 day ago",
    profileStrength: 69,
  },
  {
    id: "stu-018",
    name: "Emre Yilmaz",
    initials: "EY",
    nationality: "Turkey",
    nationalityFlag: "🇹🇷",
    year: 3,
    major: "Industrial Engineering",
    category: "Engineering",
    gpa: 3.55,
    classRanking: "Top 25%",
    hsk: 2,
    englishLevel: "Fluent",
    otherLanguages: ["Turkish (Native)"],
    skills: ["Operations Research", "Excel Modeling", "Python", "Process Mapping", "Simulation", "Technical Presentations"],
    projects: [
      { title: "Canteen Service Simulation", description: "Modeled lunch-hour service flow and tested queue changes that could reduce waiting time for students.", tags: ["Simulation", "Operations", "Excel"] },
      { title: "Warehouse Pick Path Study", description: "Compared aisle layouts for a classroom warehouse exercise and documented tradeoffs for batch picking.", tags: ["Process Design", "Python", "Logistics"] },
    ],
    bio: "I enjoy making systems visible with numbers and diagrams. Operations work fits how I think: measure, simplify, then improve.",
    headline: "Industrial engineering student focused on service operations",
    verified: true,
    lookingFor: "Both",
    availableFrom: "August 2026",
    preferredLocations: ["Hangzhou", "Shanghai", "Istanbul"],
    activities: ["Operations Research Club", "International Football Team"],
    awards: [{ title: "Process Improvement Case Finalist", year: 2025, description: "Reached the final with a simulation-backed service redesign." }],
    coursesCompleted: 24,
    responseTime: "Within 1 day",
    lastActive: "6 hours ago",
    profileStrength: 78,
  },
  {
    id: "stu-019",
    name: "Thiri Aung",
    initials: "TA",
    nationality: "Myanmar",
    nationalityFlag: "🇲🇲",
    year: 3,
    major: "International Trade",
    category: "Business",
    gpa: 3.57,
    classRanking: "Top 25%",
    hsk: 4,
    englishLevel: "Proficient",
    otherLanguages: ["Burmese (Native)"],
    skills: ["Trade Documentation", "Supplier Research", "Excel", "Mandarin (HSK 4)", "Market Entry", "Customer Interviews"],
    projects: [
      { title: "Myanmar Grocery Import Map", description: "Mapped small-batch grocery import paths from Zhejiang suppliers to Yangon retailers and compared documentation needs.", tags: ["Trade", "Research", "Excel"] },
      { title: "Supplier Trust Checklist", description: "Created a bilingual checklist for student sellers evaluating MOQ, sample policy, and payment terms.", tags: ["Supplier Research", "Mandarin", "Risk"] },
    ],
    bio: "I like business work that reduces uncertainty for small sellers. My strength is asking practical questions until the next step is clear.",
    headline: "International trade student connecting Zhejiang and Myanmar markets",
    verified: true,
    lookingFor: "Internship",
    availableFrom: "June 2026",
    preferredLocations: ["Hangzhou", "Yiwu", "Yangon"],
    activities: ["ASEAN Business Forum", "Myanmar Student Community"],
    awards: [{ title: "Cross-border Trade Case Award", year: 2025, description: "Recognized for a practical supplier verification framework." }],
    coursesCompleted: 25,
    responseTime: "Within 24 hours",
    lastActive: "4 hours ago",
    profileStrength: 81,
  },
  {
    id: "stu-020",
    name: "Ama Nkrumah",
    initials: "AN",
    nationality: "Ghana",
    nationalityFlag: "🇬🇭",
    year: 4,
    major: "Marketing",
    category: "Business",
    gpa: 3.71,
    classRanking: "Top 15%",
    hsk: 3,
    englishLevel: "Native",
    otherLanguages: ["Twi"],
    skills: ["Brand Strategy", "Consumer Research", "Social Media Analytics", "Excel", "Campaign Planning", "Public Speaking"],
    projects: [
      { title: "China-Ghana Beauty Launch Plan", description: "Built a launch plan for a Zhejiang skincare brand entering Accra through campus ambassadors and social commerce.", tags: ["Marketing", "Ghana", "Campaigns"] },
      { title: "International Student Brand Survey", description: "Interviewed classmates about trust signals in Chinese brands and translated findings into positioning recommendations.", tags: ["Research", "Brand", "Survey"] },
    ],
    bio: "I turn customer conversations into clear positioning. I am especially interested in African market growth for Chinese consumer brands.",
    headline: "Marketing strategist for China-Africa consumer growth",
    verified: true,
    lookingFor: "Full-time",
    availableFrom: "July 2026",
    preferredLocations: ["Hangzhou", "Shanghai", "Accra"],
    activities: ["African Students Association Marketing Lead", "Case Competition Team"],
    awards: [{ title: "Best Market Entry Presentation", year: 2025, description: "Won a class pitch for a Ghana-focused consumer launch plan." }],
    coursesCompleted: 31,
    responseTime: "Within 12 hours",
    lastActive: "1 hour ago",
    profileStrength: 92,
  },
  {
    id: "stu-021",
    name: "Brian Otieno",
    initials: "BO",
    nationality: "Kenya",
    nationalityFlag: "🇰🇪",
    year: 3,
    major: "E-commerce",
    category: "Business",
    gpa: 3.44,
    classRanking: "Top 35%",
    hsk: 3,
    englishLevel: "Native",
    otherLanguages: ["Swahili"],
    skills: ["E-commerce Operations", "Marketplace Research", "Excel", "Copywriting", "Supplier Coordination", "Pricing"],
    projects: [
      { title: "Kenya Electronics Reseller Study", description: "Compared small electronics listings across Kenyan marketplaces and identified common gaps in product content.", tags: ["E-commerce", "Research", "Pricing"] },
      { title: "Product Page Rewrite Sprint", description: "Rewrote product descriptions for a class marketplace prototype to improve trust, warranty clarity, and shipping expectations.", tags: ["Copywriting", "Marketplace", "UX"] },
    ],
    bio: "I care about the details that make online buyers trust a seller. E-commerce feels strongest when operations and copy support each other.",
    headline: "E-commerce operator focused on East Africa marketplace growth",
    verified: true,
    lookingFor: "Internship",
    availableFrom: "August 2026",
    preferredLocations: ["Hangzhou", "Guangzhou", "Nairobi"],
    activities: ["Cross-border E-commerce Club", "African Student Business Circle"],
    awards: [{ title: "Marketplace Operations Merit", year: 2025, description: "Recognized for a strong analysis of product content and seller trust gaps." }],
    coursesCompleted: 23,
    responseTime: "Within 1 day",
    lastActive: "11 hours ago",
    profileStrength: 75,
  },
  {
    id: "stu-022",
    name: "Dilnoza Karimova",
    initials: "DK",
    nationality: "Uzbekistan",
    nationalityFlag: "🇺🇿",
    year: 4,
    major: "Logistics Management",
    category: "Business",
    gpa: 3.8,
    classRanking: "Top 10%",
    hsk: 5,
    englishLevel: "Fluent",
    otherLanguages: ["Uzbek (Native)", "Russian"],
    skills: ["Supply Chain Planning", "Russian Localization", "Excel Modeling", "Mandarin (HSK 5)", "Incoterms", "Vendor Coordination"],
    projects: [
      { title: "Yiwu-Tashkent Freight Planner", description: "Compared freight routes, customs timing, and consolidation costs for small sellers moving goods to Central Asia.", tags: ["Logistics", "Central Asia", "Excel"] },
      { title: "Russian Supplier Message Kit", description: "Created templates for clarifying packaging, inspection, and delivery terms with Chinese suppliers.", tags: ["Russian", "Supplier Management", "Trade"] },
      { title: "Inventory Buffer Calculator", description: "Built a spreadsheet model for estimating reorder points under variable shipping lead times.", tags: ["Inventory", "Modeling", "Excel"] },
    ],
    bio: "I like logistics because every detail has a cost. My strongest work connects supplier communication with realistic planning.",
    headline: "Supply chain planner for China-Central Asia trade",
    verified: true,
    lookingFor: "Full-time",
    availableFrom: "June 2026",
    preferredLocations: ["Hangzhou", "Yiwu", "Tashkent"],
    activities: ["Central Asia Student Network", "Logistics Simulation Team"],
    awards: [{ title: "Supply Chain Analytics Distinction", year: 2025, description: "Recognized for a detailed lead-time model and clear assumptions." }],
    coursesCompleted: 33,
    responseTime: "Within 6 hours",
    lastActive: "20 minutes ago",
    profileStrength: 94,
  },
  {
    id: "stu-023",
    name: "Lucas Oliveira",
    initials: "LO",
    nationality: "Brazil",
    nationalityFlag: "🇧🇷",
    year: 3,
    major: "International Business",
    category: "Business",
    gpa: 3.49,
    classRanking: "Top 30%",
    hsk: 3,
    englishLevel: "Fluent",
    otherLanguages: ["Portuguese (Native)", "Spanish"],
    skills: ["Market Research", "Portuguese Localization", "Excel", "Customer Interviews", "Trade Shows", "Mandarin (HSK 3)"],
    projects: [
      { title: "Brazilian Buyer Persona Study", description: "Interviewed Brazilian students and sellers about Chinese electronics brands and mapped common trust concerns.", tags: ["Research", "Brazil", "Localization"] },
      { title: "Portuguese Product Copy Audit", description: "Reviewed translated product listings and rewrote unclear warranty and return policy sections.", tags: ["Portuguese", "E-commerce", "Copywriting"] },
    ],
    bio: "I help teams understand how product details land in another culture. I am interested in Latin America growth for Chinese exporters.",
    headline: "Business student localizing Chinese products for Brazil",
    verified: true,
    lookingFor: "Both",
    availableFrom: "September 2026",
    preferredLocations: ["Hangzhou", "Shanghai", "São Paulo"],
    activities: ["Latin America Student Circle", "International Trade Club"],
    awards: [{ title: "Localization Case Selection", year: 2025, description: "Selected for a class showcase on Portuguese product messaging." }],
    coursesCompleted: 24,
    responseTime: "Within 24 hours",
    lastActive: "3 hours ago",
    profileStrength: 79,
  },
  {
    id: "stu-024",
    name: "Youssef El Amrani",
    initials: "YE",
    nationality: "Morocco",
    nationalityFlag: "🇲🇦",
    year: 4,
    major: "Biomedical Engineering",
    category: "Health",
    gpa: 3.73,
    classRanking: "Top 15%",
    hsk: 4,
    englishLevel: "Fluent",
    otherLanguages: ["Arabic (Native)", "French"],
    skills: ["Biomedical Sensors", "Lab Documentation", "MATLAB", "Regulatory Research", "Mandarin (HSK 4)", "French Translation"],
    projects: [
      { title: "Wearable Pulse Sensor Review", description: "Compared low-cost pulse sensor readings and documented limitations for student health monitoring scenarios.", tags: ["Sensors", "MATLAB", "Health Tech"] },
      { title: "Device Label Translation Study", description: "Reviewed Chinese medical device labels and proposed clearer French and English safety wording.", tags: ["Translation", "Regulatory", "Safety"] },
    ],
    bio: "I want medical technology to be understandable before it reaches patients. My work combines device knowledge, documentation, and language.",
    headline: "Biomedical engineering student bridging devices and documentation",
    verified: true,
    lookingFor: "Full-time",
    availableFrom: "July 2026",
    preferredLocations: ["Hangzhou", "Shanghai", "Casablanca"],
    activities: ["Biomedical Lab Assistant", "Arabic-French Student Group"],
    awards: [{ title: "Biomedical Design Report Award", year: 2025, description: "Recognized for careful test notes and safety documentation." }],
    coursesCompleted: 32,
    responseTime: "Within 24 hours",
    lastActive: "5 hours ago",
    profileStrength: 87,
  },
  {
    id: "stu-025",
    name: "Naledi Mokoena",
    initials: "NM",
    nationality: "South Africa",
    nationalityFlag: "🇿🇦",
    year: 3,
    major: "Health Management",
    category: "Health",
    gpa: 3.46,
    classRanking: "Top 30%",
    hsk: 2,
    englishLevel: "Native",
    otherLanguages: ["Zulu", "Sesotho"],
    skills: ["Health Surveys", "Program Coordination", "Excel", "Workshop Facilitation", "Patient Communication", "Data Cleaning"],
    projects: [
      { title: "Clinic Navigation Map", description: "Designed a step-by-step guide for international students visiting a Chinese campus clinic for the first time.", tags: ["Patient Support", "Service Design", "Health"] },
      { title: "Stress Support Survey", description: "Collected and cleaned anonymous survey data on international student stress and help-seeking barriers.", tags: ["Survey", "Excel", "Wellbeing"] },
    ],
    bio: "I notice where people get lost in health systems. I want to help teams design services that feel easier to enter.",
    headline: "Health management student focused on patient access",
    verified: true,
    lookingFor: "Internship",
    availableFrom: "June 2026",
    preferredLocations: ["Hangzhou", "Ningbo", "Johannesburg"],
    activities: ["Student Wellness Volunteer", "African Students Association"],
    awards: [{ title: "Community Health Service Recognition", year: 2025, description: "Recognized for peer support and clinic navigation work." }],
    coursesCompleted: 22,
    responseTime: "Within 1 day",
    lastActive: "2 days ago",
    profileStrength: 73,
  },
  {
    id: "stu-026",
    name: "Mehrangez Safarova",
    initials: "MS",
    nationality: "Tajikistan",
    nationalityFlag: "🇹🇯",
    year: 4,
    major: "Public Health",
    category: "Health",
    gpa: 3.67,
    classRanking: "Top 18%",
    hsk: 5,
    englishLevel: "Proficient",
    otherLanguages: ["Tajik (Native)", "Russian"],
    skills: ["Community Health", "Russian Translation", "SPSS", "Mandarin (HSK 5)", "Evidence Review", "Workshop Facilitation"],
    projects: [
      { title: "Vaccination Information Review", description: "Compared multilingual public health notices and identified language gaps for international student audiences.", tags: ["Public Health", "Translation", "Research"] },
      { title: "Healthy Dorm Workshop", description: "Designed a workshop on ventilation, hygiene, and shared-space habits for new international dorm residents.", tags: ["Workshop", "Student Health", "Mandarin"] },
    ],
    bio: "Public health starts with communication people can actually use. I am interested in multilingual education and prevention work.",
    headline: "Public health student building multilingual prevention materials",
    verified: true,
    lookingFor: "Full-time",
    availableFrom: "August 2026",
    preferredLocations: ["Hangzhou", "Beijing", "Dushanbe"],
    activities: ["Health Education Volunteer", "Central Asia Student Network"],
    awards: [{ title: "Public Health Communication Merit", year: 2025, description: "Recognized for clear multilingual prevention materials." }],
    coursesCompleted: 30,
    responseTime: "Within 12 hours",
    lastActive: "8 hours ago",
    profileStrength: 86,
  },
  {
    id: "stu-027",
    name: "Aizada Bektemir",
    initials: "AB",
    nationality: "Kyrgyzstan",
    nationalityFlag: "🇰🇬",
    year: 3,
    major: "Translation and Intercultural Communication",
    category: "Language",
    gpa: 3.84,
    classRanking: "Top 8%",
    hsk: 6,
    englishLevel: "Fluent",
    otherLanguages: ["Kyrgyz (Native)", "Russian"],
    skills: ["Mandarin (HSK 6)", "Russian Localization", "Interpretation", "Terminology Management", "Business Writing", "Cultural Mediation"],
    projects: [
      { title: "Factory Tour Terminology Pack", description: "Prepared Mandarin-Russian-Kyrgyz glossaries for student visits to Zhejiang manufacturing companies.", tags: ["Interpretation", "Manufacturing", "Terminology"] },
      { title: "Interview Phrasebook", description: "Built a practical Mandarin guide for international students preparing for recruiter conversations.", tags: ["Mandarin", "Career", "Writing"] },
    ],
    bio: "I like language work that helps a meeting move forward. Interpretation is not only accuracy; it is helping both sides feel safe asking questions.",
    headline: "Mandarin-Russian interpreter for business conversations",
    verified: true,
    lookingFor: "Full-time",
    availableFrom: "June 2026",
    preferredLocations: ["Hangzhou", "Shanghai", "Bishkek"],
    activities: ["Mandarin Debate Club", "Central Asia Culture Booth"],
    awards: [{ title: "Advanced Mandarin Communication Award", year: 2025, description: "Recognized for strong interpretation performance in campus events." }],
    coursesCompleted: 29,
    responseTime: "Within 6 hours",
    lastActive: "35 minutes ago",
    profileStrength: 95,
  },
  {
    id: "stu-028",
    name: "Olena Kovalenko",
    initials: "OK",
    nationality: "Ukraine",
    nationalityFlag: "🇺🇦",
    year: 4,
    major: "Chinese Language and Business Communication",
    category: "Language",
    gpa: 3.76,
    classRanking: "Top 12%",
    hsk: 5,
    englishLevel: "Fluent",
    otherLanguages: ["Ukrainian (Native)", "Russian"],
    skills: ["Mandarin (HSK 5)", "UX Writing", "Russian Localization", "Interviewing", "Subtitle Editing", "Business Communication"],
    projects: [
      { title: "SaaS Onboarding Localization", description: "Localized a class SaaS onboarding flow into Russian and Ukrainian with emphasis on trust and form clarity.", tags: ["Localization", "UX Writing", "SaaS"] },
      { title: "Employer Interview Series", description: "Interviewed international alumni about language barriers and translated the findings into Mandarin summaries.", tags: ["Interviewing", "Mandarin", "Research"] },
    ],
    bio: "I care about product language that lowers anxiety. Good localization should make the next click feel obvious.",
    headline: "Localization specialist for Mandarin, Russian, and Ukrainian products",
    verified: true,
    lookingFor: "Both",
    availableFrom: "July 2026",
    preferredLocations: ["Hangzhou", "Remote", "Kyiv"],
    activities: ["Translation Workshop", "International Film Subtitle Night"],
    awards: [{ title: "Business Chinese Presentation Prize", year: 2025, description: "Awarded for a clear bilingual product presentation." }],
    coursesCompleted: 31,
    responseTime: "Within 24 hours",
    lastActive: "10 hours ago",
    profileStrength: 88,
  },
  {
    id: "stu-029",
    name: "Valeria Hernandez",
    initials: "VH",
    nationality: "Mexico",
    nationalityFlag: "🇲🇽",
    year: 3,
    major: "Applied Linguistics",
    category: "Language",
    gpa: 3.59,
    classRanking: "Top 22%",
    hsk: 4,
    englishLevel: "Fluent",
    otherLanguages: ["Spanish (Native)"],
    skills: ["Spanish Localization", "Mandarin (HSK 4)", "Content Strategy", "User Interviews", "Translation QA", "Public Speaking"],
    projects: [
      { title: "Spanish Help Center Rewrite", description: "Reworked support articles for a class logistics app so Spanish-speaking users could complete shipment steps confidently.", tags: ["Spanish", "UX Writing", "Support"] },
      { title: "Latin America Student Needs Study", description: "Interviewed Spanish-speaking students about career search barriers and summarized patterns for platform design.", tags: ["Research", "Interviews", "Career"] },
    ],
    bio: "I like helping products sound human in another language. My strongest work combines interviews, writing, and careful QA.",
    headline: "Spanish localization writer with Mandarin product context",
    verified: true,
    lookingFor: "Internship",
    availableFrom: "August 2026",
    preferredLocations: ["Hangzhou", "Shanghai", "Mexico City"],
    activities: ["Latin America Student Circle", "Public Speaking Club"],
    awards: [{ title: "Applied Linguistics Portfolio Selection", year: 2025, description: "Selected for practical localization work with user interview evidence." }],
    coursesCompleted: 24,
    responseTime: "Within 1 day",
    lastActive: "14 hours ago",
    profileStrength: 77,
  },
  {
    id: "stu-030",
    name: "Camila Rojas",
    initials: "CR",
    nationality: "Peru",
    nationalityFlag: "🇵🇪",
    year: 2,
    major: "Environmental Design",
    category: "Other",
    gpa: 3.43,
    classRanking: "Top 35%",
    hsk: 3,
    englishLevel: "Proficient",
    otherLanguages: ["Spanish (Native)"],
    skills: ["Figma", "Service Design", "Sustainability Research", "Mandarin (HSK 3)", "Illustration", "Workshop Facilitation"],
    projects: [
      { title: "Low-waste Orientation Kit", description: "Designed a reusable orientation kit for international freshmen that reduces printed handouts and improves wayfinding.", tags: ["Sustainability", "Service Design", "Figma"] },
      { title: "Campus Recycling Icon Audit", description: "Reviewed recycling signage around dorm areas and proposed clearer multilingual icons for common waste categories.", tags: ["Icons", "Research", "Campus"] },
    ],
    bio: "I design systems that make sustainable choices easier to notice. Visual clarity matters most when people are new to a place.",
    headline: "Environmental designer improving campus service experiences",
    verified: true,
    lookingFor: "Internship",
    availableFrom: "July 2026",
    preferredLocations: ["Hangzhou", "Shanghai", "Lima"],
    activities: ["Sustainability Volunteer Team", "Design for Good Studio"],
    awards: [{ title: "Campus Sustainability Concept Award", year: 2025, description: "Recognized for a practical low-waste orientation concept." }],
    coursesCompleted: 18,
    responseTime: "Within 48 hours",
    lastActive: "5 hours ago",
    profileStrength: 71,
  },
];
