import type { Notification } from "./types";

export const notifications: Notification[] = [
  {
    id: "not-001",
    type: "message",
    recipientType: "student",
    recipientId: "stu-001",
    actorId: "emp-001",
    text: "Alibaba Cloud sent details for your Friday product debugging exercise.",
    timestamp: "12 minutes ago",
    isoTimestamp: "2026-05-29T20:48:00+08:00",
    read: false,
    link: "/student/messages/conv-001",
  },
  {
    id: "not-002",
    type: "profile_view",
    recipientType: "student",
    recipientId: "stu-003",
    actorId: "emp-002",
    text: "BYD International viewed your sorting arm project notes.",
    timestamp: "24 minutes ago",
    isoTimestamp: "2026-05-29T20:36:00+08:00",
    read: false,
    link: "/student/activity",
  },
  {
    id: "not-003",
    type: "message",
    recipientType: "student",
    recipientId: "stu-008",
    actorId: "emp-007",
    text: "Lingxi AI sent a localization QA trial task.",
    timestamp: "38 minutes ago",
    isoTimestamp: "2026-05-29T20:22:00+08:00",
    read: false,
    link: "/student/messages/conv-003",
  },
  {
    id: "not-004",
    type: "system",
    recipientType: "employer",
    recipientId: "emp-008",
    actorId: "stu-003",
    text: "Ayesha Khan confirmed your technical interview for Wednesday 10:00.",
    timestamp: "45 minutes ago",
    isoTimestamp: "2026-05-29T20:15:00+08:00",
    read: false,
    link: "/employer/messages/conv-008",
  },
  {
    id: "not-005",
    type: "shortlist",
    recipientType: "student",
    recipientId: "stu-001",
    actorId: "emp-004",
    text: "Bosch China saved your profile to their automation shortlist.",
    timestamp: "58 minutes ago",
    isoTimestamp: "2026-05-29T20:02:00+08:00",
    read: false,
    link: "/student/matches",
  },
  {
    id: "not-006",
    type: "profile_view",
    recipientType: "student",
    recipientId: "stu-005",
    actorId: "emp-003",
    text: "SHEIN reviewed your Indonesia cross-border beauty study.",
    timestamp: "3 hours ago",
    isoTimestamp: "2026-05-29T18:00:00+08:00",
    read: true,
    link: "/student/activity",
  },
  {
    id: "not-007",
    type: "message",
    recipientType: "employer",
    recipientId: "emp-003",
    actorId: "stu-005",
    text: "Putri Aulia Santoso replied with her live commerce campaign plan.",
    timestamp: "5 hours ago",
    isoTimestamp: "2026-05-29T16:00:00+08:00",
    read: false,
    link: "/employer/messages/conv-004",
  },
  {
    id: "not-008",
    type: "feedback",
    recipientType: "student",
    recipientId: "stu-001",
    actorId: "emp-005",
    text: "Siemens China left feedback on your QR booth presentation.",
    timestamp: "7 hours ago",
    isoTimestamp: "2026-05-29T14:00:00+08:00",
    read: true,
    link: "/student/feedback",
  },
  {
    id: "not-009",
    type: "system",
    recipientType: "employer",
    recipientId: "emp-001",
    text: "Six new Engineering profiles now match your cloud support internship filters.",
    timestamp: "10 hours ago",
    isoTimestamp: "2026-05-29T11:00:00+08:00",
    read: true,
    link: "/employer/browse?category=Engineering",
  },
  {
    id: "not-010",
    type: "shortlist",
    recipientType: "student",
    recipientId: "stu-006",
    actorId: "emp-006",
    text: "Pinduoduo saved your Central Asia market research profile.",
    timestamp: "18 hours ago",
    isoTimestamp: "2026-05-29T03:00:00+08:00",
    read: true,
    link: "/student/matches",
  },
  {
    id: "not-011",
    type: "event_reminder",
    recipientType: "student",
    recipientId: "stu-001",
    text: "Reminder: update your QR badge before Spring Career Fair booth check-in.",
    timestamp: "23 hours ago",
    isoTimestamp: "2026-05-28T22:00:00+08:00",
    read: true,
    link: "/student/events/evt-001",
  },
  {
    id: "not-012",
    type: "message",
    recipientType: "employer",
    recipientId: "emp-005",
    actorId: "stu-010",
    text: "Omar Hassan replied to your healthcare documentation interview brief.",
    timestamp: "2 days ago",
    isoTimestamp: "2026-05-27T15:30:00+08:00",
    read: true,
    link: "/employer/messages/conv-009",
  },
  {
    id: "not-013",
    type: "profile_view",
    recipientType: "student",
    recipientId: "stu-004",
    actorId: "emp-004",
    text: "Bosch China viewed your dorm energy monitor project.",
    timestamp: "2 days ago",
    isoTimestamp: "2026-05-27T09:45:00+08:00",
    read: true,
    link: "/student/activity",
  },
  {
    id: "not-014",
    type: "system",
    recipientType: "employer",
    recipientId: "emp-002",
    text: "Your BYD International booth package for evt-001 is ready for review.",
    timestamp: "3 days ago",
    isoTimestamp: "2026-05-26T17:10:00+08:00",
    read: true,
    link: "/employer/events/evt-001",
  },
  {
    id: "not-015",
    type: "feedback",
    recipientType: "student",
    recipientId: "stu-001",
    actorId: "emp-004",
    text: "Bosch China shared feedback on your TypeScript portfolio walkthrough.",
    timestamp: "4 days ago",
    isoTimestamp: "2026-05-25T13:20:00+08:00",
    read: true,
    link: "/student/feedback",
  },
  {
    id: "not-016",
    type: "system",
    recipientType: "employer",
    recipientId: "emp-007",
    text: "Lingxi AI has three new high-fit Language profiles to review.",
    timestamp: "5 days ago",
    isoTimestamp: "2026-05-24T10:00:00+08:00",
    read: true,
    link: "/employer/browse?category=Language",
  },
  {
    id: "not-017",
    type: "event_reminder",
    recipientType: "student",
    recipientId: "stu-012",
    text: "Your Digital Media booth materials are due one week before evt-001.",
    timestamp: "6 days ago",
    isoTimestamp: "2026-05-23T12:15:00+08:00",
    read: true,
    link: "/student/events/evt-001",
  },
  {
    id: "not-018",
    type: "profile_view",
    recipientType: "employer",
    recipientId: "emp-006",
    actorId: "stu-006",
    text: "Aigerim Nurlanova updated her Russian localization portfolio after your view.",
    timestamp: "7 days ago",
    isoTimestamp: "2026-05-22T09:30:00+08:00",
    read: true,
    link: "/employer/shortlist",
  },
];
