import type { ActivityEvent } from "./types";

export const activityFeed: ActivityEvent[] = [
  {
    id: "act-001",
    userId: "stu-001",
    userType: "student",
    type: "message_received",
    text: "Alibaba Cloud sent details for your product debugging exercise.",
    timestamp: "12 minutes ago",
    isoTimestamp: "2026-05-29T20:48:00+08:00",
  },
  {
    id: "act-002",
    userId: "emp-003",
    userType: "employer",
    type: "message_received",
    text: "Putri Aulia Santoso shared her live commerce campaign plan with SHEIN.",
    timestamp: "5 hours ago",
    isoTimestamp: "2026-05-29T16:00:00+08:00",
  },
  {
    id: "act-003",
    userId: "stu-003",
    userType: "student",
    type: "profile_view",
    text: "BYD International viewed your low-cost sorting arm project.",
    timestamp: "8 hours ago",
    isoTimestamp: "2026-05-29T13:00:00+08:00",
  },
  {
    id: "act-004",
    userId: "emp-008",
    userType: "employer",
    type: "interview_scheduled",
    text: "Cathay Robotics scheduled a technical interview with Ayesha Khan.",
    timestamp: "1 day ago",
    isoTimestamp: "2026-05-28T17:40:00+08:00",
  },
  {
    id: "act-005",
    userId: "stu-001",
    userType: "student",
    type: "feedback_received",
    text: "Siemens China left feedback on your multilingual support workflow.",
    timestamp: "2 days ago",
    isoTimestamp: "2026-05-27T14:30:00+08:00",
  },
  {
    id: "act-006",
    userId: "emp-001",
    userType: "employer",
    type: "profile_save",
    text: "Alibaba Cloud saved Nattapong Saetang to the cloud support shortlist.",
    timestamp: "3 days ago",
    isoTimestamp: "2026-05-26T10:20:00+08:00",
  },
  {
    id: "act-007",
    userId: "stu-004",
    userType: "student",
    type: "profile_view",
    text: "Bosch China viewed your dorm energy monitor project.",
    timestamp: "3 days ago",
    isoTimestamp: "2026-05-26T09:10:00+08:00",
  },
  {
    id: "act-008",
    userId: "stu-005",
    userType: "student",
    type: "message_sent",
    text: "You sent SHEIN your Indonesia campaign planning portfolio.",
    timestamp: "4 days ago",
    isoTimestamp: "2026-05-25T16:18:00+08:00",
  },
  {
    id: "act-009",
    userId: "emp-005",
    userType: "employer",
    type: "feedback_given",
    text: "Siemens China gave Omar Hassan interview preparation feedback.",
    timestamp: "5 days ago",
    isoTimestamp: "2026-05-24T15:56:00+08:00",
  },
  {
    id: "act-010",
    userId: "stu-006",
    userType: "student",
    type: "profile_save",
    text: "Pinduoduo saved your Central Asia buyer persona profile.",
    timestamp: "6 days ago",
    isoTimestamp: "2026-05-23T11:25:00+08:00",
  },
  {
    id: "act-011",
    userId: "emp-007",
    userType: "employer",
    type: "message_sent",
    text: "Lingxi AI sent a Mandarin-Mongolian QA task to Bolor-Erdene Ganbold.",
    timestamp: "7 days ago",
    isoTimestamp: "2026-05-22T17:45:00+08:00",
  },
  {
    id: "act-012",
    userId: "stu-008",
    userType: "student",
    type: "message_received",
    text: "Lingxi AI asked you to review support replies for tone and terminology.",
    timestamp: "7 days ago",
    isoTimestamp: "2026-05-22T17:45:00+08:00",
  },
  {
    id: "act-013",
    userId: "stu-010",
    userType: "student",
    type: "interview_scheduled",
    text: "Siemens China scheduled your healthcare documentation interview.",
    timestamp: "9 days ago",
    isoTimestamp: "2026-05-20T13:08:00+08:00",
  },
  {
    id: "act-014",
    userId: "emp-004",
    userType: "employer",
    type: "profile_save",
    text: "Bosch China saved Arjun Mehta for an energy systems internship review.",
    timestamp: "11 days ago",
    isoTimestamp: "2026-05-18T15:42:00+08:00",
  },
  {
    id: "act-015",
    userId: "stu-012",
    userType: "student",
    type: "slot_booked",
    text: "You booked a Digital Media booth slot for Spring Career Fair 2026.",
    timestamp: "13 days ago",
    isoTimestamp: "2026-05-16T10:25:00+08:00",
  },
];
