import type { Conversation } from "./types";

export const conversations: Conversation[] = [
  {
    id: "conv-001",
    participantStudentId: "stu-001",
    participantEmployerId: "emp-001",
    lastMessageAt: "2026-05-29T20:42:00+08:00",
    unreadCount: 2,
    archived: false,
    messages: [
      {
        id: "msg-001-001",
        senderType: "employer",
        text: "Hi Nattapong, I saw your booth presentation at the spring event. Your dorm maintenance chatbot and campus navigator caught our cloud solutions team's attention.",
        sentAt: "2026-05-27T09:16:00+08:00",
        read: true,
      },
      {
        id: "msg-001-002",
        senderType: "student",
        text: "Hi, thank you for reaching out. I would be happy to discuss both projects. The chatbot was built to turn mixed Mandarin-English repair requests into structured tickets for campus staff.",
        sentAt: "2026-05-27T09:48:00+08:00",
        read: true,
      },
      {
        id: "msg-001-003",
        senderType: "employer",
        text: "That structured handoff is exactly the part we liked. Alibaba Cloud has an internship opening on a multilingual customer support tooling team. I attached the role brief here.",
        sentAt: "2026-05-27T10:21:00+08:00",
        read: true,
      },
      {
        id: "msg-001-004",
        senderType: "student",
        text: "I have shared my portfolio link with a short demo video. The current prototype uses intent labels, Mandarin keyword matching, and a fallback form when confidence is low.",
        sentAt: "2026-05-27T11:04:00+08:00",
        read: true,
      },
      {
        id: "msg-001-005",
        senderType: "employer",
        text: "Could you tell me how you evaluated the chatbot? We are less concerned about model size and more interested in how you tested language failure cases.",
        sentAt: "2026-05-27T15:37:00+08:00",
        read: true,
      },
      {
        id: "msg-001-006",
        senderType: "student",
        text: "I tested it with 42 sample repair reports from Thai, Vietnamese, and Arabic-speaking classmates. The hardest cases were mixed room numbers, informal Mandarin, and photos with very short captions.",
        sentAt: "2026-05-27T16:10:00+08:00",
        read: true,
      },
      {
        id: "msg-001-007",
        senderType: "employer",
        text: "Great answer. The team also noticed your TypeScript and React work on the scholarship tracker. Would you be comfortable doing a small product debugging exercise?",
        sentAt: "2026-05-28T09:02:00+08:00",
        read: true,
      },
      {
        id: "msg-001-008",
        senderType: "student",
        text: "Yes. I prefer exercises that include user context, because I can explain tradeoffs better that way. I am available Friday afternoon or Monday morning.",
        sentAt: "2026-05-28T09:35:00+08:00",
        read: true,
      },
      {
        id: "msg-001-009",
        senderType: "employer",
        text: "Friday 15:30 works. The exercise will be a 45-minute live review of a bilingual support dashboard. No algorithm puzzle, just product thinking and code discussion.",
        sentAt: "2026-05-28T14:18:00+08:00",
        read: true,
      },
      {
        id: "msg-001-010",
        senderType: "student",
        text: "Confirmed for Friday 15:30. I will prepare the chatbot notes and the campus navigator architecture diagram in case they are useful.",
        sentAt: "2026-05-28T14:44:00+08:00",
        read: true,
      },
      {
        id: "msg-001-011",
        senderType: "employer",
        text: "Perfect. I sent the calendar invitation and included the internship description again. Please bring one example of a product decision you changed after user feedback.",
        sentAt: "2026-05-29T20:18:00+08:00",
        read: false,
      },
      {
        id: "msg-001-012",
        senderType: "employer",
        text: "One more note: the hiring manager is especially interested in cross-language edge cases, so your dorm chatbot testing notes will be valuable.",
        sentAt: "2026-05-29T20:42:00+08:00",
        read: false,
      },
    ],
  },
  {
    id: "conv-002",
    participantStudentId: "stu-003",
    participantEmployerId: "emp-002",
    lastMessageAt: "2026-05-29T20:03:00+08:00",
    unreadCount: 1,
    archived: false,
    messages: [
      {
        id: "msg-002-001",
        senderType: "employer",
        text: "Hi Ayesha, your low-cost sorting arm demo was a strong fit for our overseas service training team at BYD International.",
        sentAt: "2026-05-29T18:12:00+08:00",
        read: true,
      },
      {
        id: "msg-002-002",
        senderType: "student",
        text: "Thank you. I built it to make the sensing and motion control visible for students who are new to automation.",
        sentAt: "2026-05-29T18:44:00+08:00",
        read: true,
      },
      {
        id: "msg-002-003",
        senderType: "employer",
        text: "That teaching mindset is useful for us. Could you share your SolidWorks files or a short build note? We are considering interns for technical documentation and lab setup.",
        sentAt: "2026-05-29T19:11:00+08:00",
        read: true,
      },
      {
        id: "msg-002-004",
        senderType: "student",
        text: "I can share both. I have a PDF build log and the assembly screenshots ready, and I can explain the sensor calibration choices.",
        sentAt: "2026-05-29T19:48:00+08:00",
        read: true,
      },
      {
        id: "msg-002-005",
        senderType: "employer",
        text: "Great. Please send the build log here when convenient. If it looks aligned, we can invite you for a technical interview next week.",
        sentAt: "2026-05-29T20:03:00+08:00",
        read: false,
      },
    ],
  },
  {
    id: "conv-003",
    participantStudentId: "stu-008",
    participantEmployerId: "emp-007",
    lastMessageAt: "2026-05-29T19:37:00+08:00",
    unreadCount: 1,
    archived: false,
    messages: [
      {
        id: "msg-003-001",
        senderType: "employer",
        text: "Hello Bolor-Erdene, Lingxi AI is testing customer support assistants for Central Asian exporters. Your interpreter guide stood out to us.",
        sentAt: "2026-05-29T17:20:00+08:00",
        read: true,
      },
      {
        id: "msg-003-002",
        senderType: "student",
        text: "Hello, thank you. I am especially interested in terminology quality and how AI tools handle polite business language.",
        sentAt: "2026-05-29T17:58:00+08:00",
        read: true,
      },
      {
        id: "msg-003-003",
        senderType: "employer",
        text: "Exactly our problem. Would you be open to a part-time localization QA trial? The first task is reviewing Mandarin-Mongolian support replies for tone and accuracy.",
        sentAt: "2026-05-29T18:43:00+08:00",
        read: true,
      },
      {
        id: "msg-003-004",
        senderType: "student",
        text: "Yes, I would like to try. Please send the task format and expected review depth so I can estimate the time honestly.",
        sentAt: "2026-05-29T19:10:00+08:00",
        read: true,
      },
      {
        id: "msg-003-005",
        senderType: "employer",
        text: "I attached a sample set of 20 replies. Please mark severe meaning errors, tone risks, and unclear terminology. No need to rewrite every sentence.",
        sentAt: "2026-05-29T19:37:00+08:00",
        read: false,
      },
    ],
  },
  {
    id: "conv-004",
    participantStudentId: "stu-005",
    participantEmployerId: "emp-003",
    lastMessageAt: "2026-05-28T16:25:00+08:00",
    unreadCount: 0,
    archived: false,
    messages: [
      {
        id: "msg-004-001",
        senderType: "employer",
        text: "Hi Putri, SHEIN's Southeast Asia growth team liked your Indonesia cross-border beauty study. The customer trust section was very practical.",
        sentAt: "2026-05-27T13:05:00+08:00",
        read: true,
      },
      {
        id: "msg-004-002",
        senderType: "student",
        text: "Thank you. I interviewed both student buyers and small resellers because the trust problem looks different in each group.",
        sentAt: "2026-05-27T13:42:00+08:00",
        read: true,
      },
      {
        id: "msg-004-003",
        senderType: "employer",
        text: "Would you be interested in a campaign operations internship focused on product page localization and creator briefs for Indonesia?",
        sentAt: "2026-05-27T15:09:00+08:00",
        read: true,
      },
      {
        id: "msg-004-004",
        senderType: "student",
        text: "Yes. I would like to know how much of the role is data review versus content coordination. I can share my live commerce campaign plan too.",
        sentAt: "2026-05-28T09:21:00+08:00",
        read: true,
      },
      {
        id: "msg-004-005",
        senderType: "employer",
        text: "It is about 60% content operations and 40% data review. Please send the campaign plan; we will use it to decide the interview focus.",
        sentAt: "2026-05-28T16:25:00+08:00",
        read: true,
      },
    ],
  },
  {
    id: "conv-005",
    participantStudentId: "stu-004",
    participantEmployerId: "emp-004",
    lastMessageAt: "2026-05-26T18:14:00+08:00",
    unreadCount: 0,
    archived: false,
    messages: [
      {
        id: "msg-005-001",
        senderType: "employer",
        text: "Hi Arjun, Bosch China reviewed your dorm energy monitor. We are looking for interns who can document test setups clearly.",
        sentAt: "2026-05-25T10:12:00+08:00",
        read: true,
      },
      {
        id: "msg-005-002",
        senderType: "student",
        text: "Thank you for reviewing it. The prototype is simple, but I documented the sensor placement and calibration assumptions carefully.",
        sentAt: "2026-05-25T11:30:00+08:00",
        read: true,
      },
      {
        id: "msg-005-003",
        senderType: "employer",
        text: "That is what we noticed. Could you explain what you would improve if you had access to industrial-grade measurement equipment?",
        sentAt: "2026-05-25T16:02:00+08:00",
        read: true,
      },
      {
        id: "msg-005-004",
        senderType: "student",
        text: "I would improve isolation, sampling reliability, and compare readings against a certified meter. I would also separate user-facing estimates from engineering logs.",
        sentAt: "2026-05-26T08:47:00+08:00",
        read: true,
      },
      {
        id: "msg-005-005",
        senderType: "employer",
        text: "Good answer. I sent your profile to our Suzhou training coordinator and will update you after their review.",
        sentAt: "2026-05-26T18:14:00+08:00",
        read: true,
      },
    ],
  },
  {
    id: "conv-006",
    participantStudentId: "stu-010",
    participantEmployerId: "emp-005",
    lastMessageAt: "2026-05-24T15:56:00+08:00",
    unreadCount: 0,
    archived: false,
    messages: [
      {
        id: "msg-006-001",
        senderType: "employer",
        text: "Hi Omar, Siemens China is reviewing student profiles for healthcare technology support roles. Your medication label comprehension study was relevant.",
        sentAt: "2026-05-23T10:08:00+08:00",
        read: true,
      },
      {
        id: "msg-006-002",
        senderType: "student",
        text: "Thank you. I focused on labels because international students often understand the medicine name but miss warnings or dosage details.",
        sentAt: "2026-05-23T11:02:00+08:00",
        read: true,
      },
      {
        id: "msg-006-003",
        senderType: "employer",
        text: "Would you be open to a role that combines regulatory research, customer education, and documentation for clinical teams?",
        sentAt: "2026-05-23T16:20:00+08:00",
        read: true,
      },
      {
        id: "msg-006-004",
        senderType: "student",
        text: "Yes. I am comfortable with research and documentation, and I would like to learn more about medical device workflows in China.",
        sentAt: "2026-05-24T09:12:00+08:00",
        read: true,
      },
      {
        id: "msg-006-005",
        senderType: "employer",
        text: "I shared our internship description. Please review the section on hospital training materials and tell us whether it matches your interests.",
        sentAt: "2026-05-24T15:56:00+08:00",
        read: true,
      },
    ],
  },
  {
    id: "conv-007",
    participantStudentId: "stu-006",
    participantEmployerId: "emp-006",
    lastMessageAt: "2026-05-22T17:35:00+08:00",
    unreadCount: 0,
    archived: false,
    messages: [
      {
        id: "msg-007-001",
        senderType: "employer",
        text: "Hi Aigerim, Pinduoduo's cross-border team liked your Central Asia buyer persona map, especially the warranty trust notes.",
        sentAt: "2026-05-21T14:12:00+08:00",
        read: true,
      },
      {
        id: "msg-007-002",
        senderType: "student",
        text: "Thank you. Warranty clarity came up repeatedly in interviews with Kazakh buyers, even more than discount size.",
        sentAt: "2026-05-21T15:26:00+08:00",
        read: true,
      },
      {
        id: "msg-007-003",
        senderType: "employer",
        text: "That insight is useful. Would you consider a full-time analyst track focused on Russian-language product quality and buyer segmentation?",
        sentAt: "2026-05-22T09:40:00+08:00",
        read: true,
      },
      {
        id: "msg-007-004",
        senderType: "student",
        text: "Yes, that matches my interests. I can share a bilingual product page audit and a short CRM segmentation exercise.",
        sentAt: "2026-05-22T11:03:00+08:00",
        read: true,
      },
      {
        id: "msg-007-005",
        senderType: "employer",
        text: "Please send both. We will review them with the Central Asia operations lead early next week.",
        sentAt: "2026-05-22T17:35:00+08:00",
        read: true,
      },
    ],
  },
  {
    id: "conv-008",
    participantStudentId: "stu-003",
    participantEmployerId: "emp-008",
    lastMessageAt: "2026-05-20T10:30:00+08:00",
    unreadCount: 0,
    archived: false,
    messages: [
      {
        id: "msg-008-001",
        senderType: "employer",
        text: "Hi Ayesha, Cathay Robotics is hiring field testing interns. Your sorting arm project and motor fault study are close to our warehouse robotics work.",
        sentAt: "2026-05-17T09:18:00+08:00",
        read: true,
      },
      {
        id: "msg-008-002",
        senderType: "student",
        text: "Thank you. I am interested in testing and documentation because small hardware issues become expensive when teams ignore them.",
        sentAt: "2026-05-17T10:02:00+08:00",
        read: true,
      },
      {
        id: "msg-008-003",
        senderType: "employer",
        text: "Exactly. Our interns help reproduce field issues, write test notes, and communicate with mechanical and software engineers.",
        sentAt: "2026-05-17T14:11:00+08:00",
        read: true,
      },
      {
        id: "msg-008-004",
        senderType: "student",
        text: "That sounds aligned. I have experience writing build logs and safety checklists, and I am comfortable asking engineers for clarification.",
        sentAt: "2026-05-17T15:03:00+08:00",
        read: true,
      },
      {
        id: "msg-008-005",
        senderType: "employer",
        text: "Could you share one example of a test that failed and what you changed afterward?",
        sentAt: "2026-05-18T09:25:00+08:00",
        read: true,
      },
      {
        id: "msg-008-006",
        senderType: "student",
        text: "In the sorting arm, the color sensor failed under bright lab light. I added a shade, recalibrated thresholds, and documented the lighting condition as part of setup.",
        sentAt: "2026-05-18T10:12:00+08:00",
        read: true,
      },
      {
        id: "msg-008-007",
        senderType: "employer",
        text: "Good. We would like to schedule a 30-minute technical interview with our Ningbo testing lead.",
        sentAt: "2026-05-18T17:40:00+08:00",
        read: true,
      },
      {
        id: "msg-008-008",
        senderType: "student",
        text: "I am available Tuesday after 14:00 or Wednesday morning. I can bring the build log and motor vibration notes.",
        sentAt: "2026-05-19T08:31:00+08:00",
        read: true,
      },
      {
        id: "msg-008-009",
        senderType: "employer",
        text: "Wednesday 10:00 works. I sent the invite and attached a short description of the testing scenario we will discuss.",
        sentAt: "2026-05-19T16:19:00+08:00",
        read: true,
      },
      {
        id: "msg-008-010",
        senderType: "student",
        text: "Confirmed for Wednesday 10:00. Thank you, I will review the scenario and prepare questions about field conditions.",
        sentAt: "2026-05-20T10:30:00+08:00",
        read: true,
      },
    ],
  },
  {
    id: "conv-009",
    participantStudentId: "stu-010",
    participantEmployerId: "emp-005",
    lastMessageAt: "2026-05-18T13:08:00+08:00",
    unreadCount: 0,
    archived: false,
    messages: [
      {
        id: "msg-009-001",
        senderType: "employer",
        text: "Omar, following our earlier discussion, our healthcare documentation manager would like to meet you for an interview.",
        sentAt: "2026-05-15T09:42:00+08:00",
        read: true,
      },
      {
        id: "msg-009-002",
        senderType: "student",
        text: "Thank you. I would be glad to meet them. Should I prepare anything specific from my medication label study?",
        sentAt: "2026-05-15T10:18:00+08:00",
        read: true,
      },
      {
        id: "msg-009-003",
        senderType: "employer",
        text: "Please prepare the survey method, the main misunderstanding patterns, and how you would rewrite one warning label.",
        sentAt: "2026-05-15T15:06:00+08:00",
        read: true,
      },
      {
        id: "msg-009-004",
        senderType: "student",
        text: "Understood. I will bring one example for dosage timing and one for allergy warnings, because those caused the most confusion.",
        sentAt: "2026-05-16T09:12:00+08:00",
        read: true,
      },
      {
        id: "msg-009-005",
        senderType: "employer",
        text: "Good plan. Are you available Monday at 13:30 for a video interview?",
        sentAt: "2026-05-16T14:48:00+08:00",
        read: true,
      },
      {
        id: "msg-009-006",
        senderType: "student",
        text: "Yes, Monday 13:30 works for me.",
        sentAt: "2026-05-16T16:05:00+08:00",
        read: true,
      },
      {
        id: "msg-009-007",
        senderType: "employer",
        text: "The calendar invite is sent. The interview will include one English explanation task and one Mandarin reading task.",
        sentAt: "2026-05-17T11:20:00+08:00",
        read: true,
      },
      {
        id: "msg-009-008",
        senderType: "student",
        text: "Thank you for explaining the format. I will prepare in both languages.",
        sentAt: "2026-05-17T12:01:00+08:00",
        read: true,
      },
      {
        id: "msg-009-009",
        senderType: "employer",
        text: "Excellent. We look forward to speaking with you.",
        sentAt: "2026-05-18T13:08:00+08:00",
        read: true,
      },
    ],
  },
  {
    id: "conv-010",
    participantStudentId: "stu-009",
    participantEmployerId: "emp-003",
    lastMessageAt: "2026-05-10T16:40:00+08:00",
    unreadCount: 0,
    archived: true,
    messages: [
      {
        id: "msg-010-001",
        senderType: "employer",
        text: "Hi Daria, SHEIN reviewed your Russian onboarding rewrite. We may have a short subtitle localization project next month.",
        sentAt: "2026-05-09T10:15:00+08:00",
        read: true,
      },
      {
        id: "msg-010-002",
        senderType: "student",
        text: "Thank you. I am interested in short-form product video localization and can share subtitle samples if helpful.",
        sentAt: "2026-05-09T11:02:00+08:00",
        read: true,
      },
      {
        id: "msg-010-003",
        senderType: "employer",
        text: "Please do. The project is not open yet, but we are building a candidate list.",
        sentAt: "2026-05-09T16:45:00+08:00",
        read: true,
      },
      {
        id: "msg-010-004",
        senderType: "student",
        text: "I shared a portfolio link with three Mandarin-to-Russian subtitle examples and notes on line length decisions.",
        sentAt: "2026-05-10T09:18:00+08:00",
        read: true,
      },
      {
        id: "msg-010-005",
        senderType: "employer",
        text: "Received, thank you. We will archive this thread for now and reopen it when the project budget is confirmed.",
        sentAt: "2026-05-10T16:40:00+08:00",
        read: true,
      },
    ],
  },
];
