import type { EmployerFeedback } from "./types";

export const employerFeedback: EmployerFeedback[] = [
  {
    id: "fb-001",
    employerId: "emp-001",
    studentId: "stu-001",
    text: "Strong technical portfolio. The multilingual chatbot project showed practical cross-cultural product thinking, especially the fallback flow for unclear Mandarin-English repair requests.",
    rating: 5,
    timestamp: "2 hours ago",
    isoTimestamp: "2026-05-29T19:00:00+08:00",
    visibleToStudent: true,
  },
  {
    id: "fb-002",
    employerId: "emp-004",
    studentId: "stu-001",
    text: "Good explanation of TypeScript and React tradeoffs in the campus navigator. He connected technical choices to the needs of new international students instead of only describing code.",
    rating: 5,
    timestamp: "1 day ago",
    isoTimestamp: "2026-05-28T15:45:00+08:00",
    visibleToStudent: true,
  },
  {
    id: "fb-003",
    employerId: "emp-005",
    studentId: "stu-001",
    text: "Clear communication and thoughtful service design instincts. The scholarship tracker showed he can turn messy university notices into structured user actions.",
    rating: 4,
    timestamp: "2 days ago",
    isoTimestamp: "2026-05-27T14:30:00+08:00",
    visibleToStudent: true,
  },
  {
    id: "fb-004",
    employerId: "emp-007",
    studentId: "stu-001",
    text: "His Mandarin is not yet advanced enough for unsupervised client calls, but he understands multilingual support failure cases well. Strong candidate for QA and product testing tasks.",
    rating: 4,
    timestamp: "3 days ago",
    isoTimestamp: "2026-05-26T16:10:00+08:00",
    visibleToStudent: true,
  },
  {
    id: "fb-005",
    employerId: "emp-002",
    studentId: "stu-001",
    text: "Good energy at the booth and polished demo flow. He should prepare one concise explanation of how his chatbot could support technical documentation teams.",
    rating: 4,
    timestamp: "5 days ago",
    isoTimestamp: "2026-05-24T11:25:00+08:00",
    visibleToStudent: true,
  },
  {
    id: "fb-006",
    employerId: "emp-006",
    studentId: "stu-001",
    text: "Internal note: promising product sense, but current portfolio is more campus-service oriented than commerce operations. Consider only if the role includes user tooling or localization workflows.",
    rating: 3,
    timestamp: "6 days ago",
    isoTimestamp: "2026-05-23T09:40:00+08:00",
    visibleToStudent: false,
  },
];
