export type JobPosting = {
  id: string;
  employerId: string;
  title: string;
  category: "Business" | "Engineering" | "Health" | "Language" | "Other";
  type: "Internship" | "Full-time" | "Both";
  location: string;
  remote: "On-site" | "Hybrid" | "Remote-friendly";
  description: string;
  responsibilities: string[];
  requirements: string[];
  niceToHave: string[];
  languages: string[];
  perks: string[];
  salaryRange?: string;
  duration?: string;
  startDate: string;
  postedAt: string;
  isoPostedAt: string;
  status: "active" | "closed";
  applicantCount: number;
};

export const jobPostings: JobPosting[] = [
  {
    id: "job-001",
    employerId: "emp-001",
    title: "Cloud Engineering Intern, International Support Tools",
    category: "Engineering",
    type: "Internship",
    location: "Hangzhou",
    remote: "Hybrid",
    description:
      "Join a cloud support tooling team that builds internal dashboards for international customers and partner teams. You will help test bilingual workflows, review customer pain points, and improve small product features with engineers.",
    responsibilities: ["Test cloud support workflows in English and Mandarin", "Document product issues with reproducible steps", "Build small TypeScript utilities for internal dashboards", "Summarize international user feedback for product managers"],
    requirements: ["Software or data major", "TypeScript or Python project experience", "Comfortable reading technical English", "Able to explain tradeoffs clearly"],
    niceToHave: ["Mandarin HSK 4+", "Experience with support chatbots", "React dashboard work"],
    languages: ["English fluent", "Mandarin HSK 4+"],
    perks: ["Cloud mentor pairing", "Internal product demos", "Hybrid schedule"],
    salaryRange: "¥6,000-8,000/month",
    duration: "3-6 months",
    startDate: "June 2026",
    postedAt: "2 days ago",
    isoPostedAt: "2026-05-27T09:00:00+08:00",
    status: "active",
    applicantCount: 18,
  },
  {
    id: "job-002",
    employerId: "emp-001",
    title: "Solutions Analyst, APAC International Team",
    category: "Business",
    type: "Internship",
    location: "Hangzhou",
    remote: "Hybrid",
    description:
      "Support solution architects with research, documentation, and customer-facing preparation for APAC accounts. This role suits graduates who can connect technical product details with business context.",
    responsibilities: ["Prepare account briefs for APAC customer meetings", "Translate customer needs into solution notes", "Coordinate product documentation updates", "Track follow-up actions across sales and technical teams"],
    requirements: ["Business, engineering, or data background", "Strong English writing", "Comfortable with cloud concepts", "Organized project follow-up habits"],
    niceToHave: ["Southeast Asia market knowledge", "Mandarin HSK 5+", "Dashboard reporting experience"],
    languages: ["English fluent", "Mandarin HSK 5 preferred"],
    perks: ["International account exposure", "Cloud training path", "Career mentor"],
    salaryRange: "¥14,000-18,000/month",
    startDate: "July 2026",
    postedAt: "4 days ago",
    isoPostedAt: "2026-05-25T10:30:00+08:00",
    status: "active",
    applicantCount: 12,
  },
  {
    id: "job-003",
    employerId: "emp-001",
    title: "Localization QA Intern, AI Support Products",
    category: "Language",
    type: "Internship",
    location: "Hangzhou",
    remote: "Remote-friendly",
    description:
      "Review multilingual AI support replies for accuracy, tone, and task completion. You will work with product managers to flag confusing language and propose clearer user-facing responses.",
    responsibilities: ["Review AI replies in English and regional languages", "Label tone, accuracy, and escalation issues", "Write concise QA notes for product teams", "Compare rewritten replies against user intent"],
    requirements: ["Strong English plus one additional language", "Careful reading and annotation habits", "Interest in AI support tools"],
    niceToHave: ["Mandarin HSK 4+", "Translation or UX writing portfolio"],
    languages: ["English fluent", "Mandarin helpful", "Regional language preferred"],
    perks: ["Remote-friendly QA blocks", "AI product exposure", "Portfolio-friendly projects"],
    salaryRange: "¥4,500-6,500/month",
    duration: "3 months",
    startDate: "June 2026",
    postedAt: "5 days ago",
    isoPostedAt: "2026-05-24T15:00:00+08:00",
    status: "active",
    applicantCount: 21,
  },
  {
    id: "job-004",
    employerId: "emp-002",
    title: "EV Technical Documentation Intern",
    category: "Engineering",
    type: "Internship",
    location: "Shenzhen",
    remote: "On-site",
    description:
      "Support overseas service teams by turning engineering notes into clear training and maintenance materials. You will work with product specialists and translate technical details into practical documentation.",
    responsibilities: ["Draft English training notes for service engineers", "Review diagrams for clarity and consistency", "Collect questions from overseas teams", "Support hands-on lab demonstrations"],
    requirements: ["Engineering major", "Strong technical writing", "Comfortable with diagrams and procedures", "English fluent"],
    niceToHave: ["EV or battery interest", "Mandarin HSK 4+", "SolidWorks or CAD familiarity"],
    languages: ["English fluent", "Mandarin HSK 4 preferred"],
    perks: ["EV industry exposure", "Training lab access", "Mentor from international service team"],
    salaryRange: "¥5,500-7,500/month",
    duration: "3-6 months",
    startDate: "July 2026",
    postedAt: "1 day ago",
    isoPostedAt: "2026-05-28T11:00:00+08:00",
    status: "active",
    applicantCount: 16,
  },
  {
    id: "job-005",
    employerId: "emp-002",
    title: "Overseas Market Research Trainee",
    category: "Business",
    type: "Full-time",
    location: "Shenzhen",
    remote: "Hybrid",
    description:
      "Help BYD International understand regional EV adoption barriers, customer expectations, and distributor needs. The role combines market research, competitor tracking, and practical reporting.",
    responsibilities: ["Prepare regional EV market briefs", "Track policy and competitor updates", "Interview international students and local contacts", "Support distributor meeting preparation"],
    requirements: ["Business or engineering-commercial background", "Strong research writing", "Comfortable with Excel", "Interest in mobility markets"],
    niceToHave: ["Southeast Asia, MENA, or Central Asia knowledge", "Mandarin HSK 5+", "Survey design experience"],
    languages: ["English fluent", "Mandarin HSK 4+", "Regional language valued"],
    perks: ["International mobility projects", "Market research training", "Cross-functional exposure"],
    salaryRange: "¥12,000-16,000/month",
    startDate: "August 2026",
    postedAt: "3 days ago",
    isoPostedAt: "2026-05-26T13:20:00+08:00",
    status: "active",
    applicantCount: 10,
  },
  {
    id: "job-006",
    employerId: "emp-003",
    title: "Southeast Asia Campaign Operations Intern",
    category: "Business",
    type: "Internship",
    location: "Guangzhou",
    remote: "Hybrid",
    description:
      "Support campaign planning for Southeast Asian markets by reviewing product pages, creator briefs, and customer response data. You will help make launches feel local instead of copied across markets.",
    responsibilities: ["Review localized campaign materials", "Prepare creator briefing notes", "Track product page feedback", "Summarize customer trust signals"],
    requirements: ["Business, marketing, or e-commerce background", "Strong English", "Comfortable with spreadsheets", "Interest in social commerce"],
    niceToHave: ["Indonesian, Thai, or Vietnamese language", "TikTok Shop or Shopee familiarity", "Canva or Figma basics"],
    languages: ["English fluent", "Regional language preferred"],
    perks: ["Live campaign exposure", "Creator operations training", "Hybrid schedule"],
    salaryRange: "¥5,000-7,000/month",
    duration: "4-6 months",
    startDate: "June 2026",
    postedAt: "2 days ago",
    isoPostedAt: "2026-05-27T14:45:00+08:00",
    status: "active",
    applicantCount: 24,
  },
  {
    id: "job-007",
    employerId: "emp-003",
    title: "Product Content Localization Associate",
    category: "Language",
    type: "Full-time",
    location: "Guangzhou",
    remote: "Hybrid",
    description:
      "Improve product content quality for international shoppers by reviewing translation, tone, size guidance, and policy explanations. The role sits between content operations, merchandising, and regional marketing.",
    responsibilities: ["Audit product pages for clarity", "Rewrite high-impact content blocks", "Create localization notes for vendors", "Track recurring content quality issues"],
    requirements: ["Excellent English writing", "One additional market language", "Localization or content portfolio", "Detail-oriented review habits"],
    niceToHave: ["Russian or Indonesian localization", "UX writing experience", "Fashion e-commerce knowledge"],
    languages: ["English fluent", "Mandarin helpful", "Regional language required"],
    perks: ["Global content projects", "Localization playbook ownership", "Team learning sessions"],
    salaryRange: "¥11,000-15,000/month",
    duration: "3-6 months",
    startDate: "July 2026",
    postedAt: "6 days ago",
    isoPostedAt: "2026-05-23T09:15:00+08:00",
    status: "active",
    applicantCount: 19,
  },
  {
    id: "job-008",
    employerId: "emp-004",
    title: "R&D Intern, IoT Hardware Testing",
    category: "Engineering",
    type: "Internship",
    location: "Suzhou",
    remote: "On-site",
    description:
      "Join Bosch China's engineering team to support sensor testing, setup documentation, and data review for IoT hardware prototypes. The role rewards careful lab habits and clear reporting.",
    responsibilities: ["Prepare test setups for sensor modules", "Record test conditions and anomalies", "Review data with engineers", "Update bilingual test notes"],
    requirements: ["Electrical, automation, or mechatronics background", "Basic circuit or sensor knowledge", "Careful documentation", "English technical reading"],
    niceToHave: ["MATLAB or Python", "Mandarin HSK 4+", "Previous lab assistant work"],
    languages: ["English proficient", "Mandarin HSK 4 preferred"],
    perks: ["Engineering lab access", "Structured mentor check-ins", "Industrial testing exposure"],
    salaryRange: "¥5,500-7,000/month",
    duration: "3-6 months",
    startDate: "July 2026",
    postedAt: "1 week ago",
    isoPostedAt: "2026-05-22T10:00:00+08:00",
    status: "active",
    applicantCount: 15,
  },
  {
    id: "job-009",
    employerId: "emp-004",
    title: "Engineering Trainee, Automotive Systems",
    category: "Engineering",
    type: "Full-time",
    location: "Suzhou",
    remote: "On-site",
    description:
      "Rotate through testing, quality, and systems teams supporting automotive technology programs. This role is for graduates who can learn structured engineering processes and communicate reliably.",
    responsibilities: ["Support quality and testing documentation", "Coordinate issue follow-up across teams", "Analyze simple test datasets", "Prepare progress reports for mentors"],
    requirements: ["Engineering degree", "Strong English documentation", "Data analysis basics", "Interest in automotive systems"],
    niceToHave: ["PLC or automation experience", "Mandarin HSK 5+", "Internship in manufacturing"],
    languages: ["English fluent", "Mandarin HSK 4+"],
    perks: ["Rotational trainee path", "Manufacturing site exposure", "Long-term career track"],
    salaryRange: "¥13,000-17,000/month",
    startDate: "August 2026",
    postedAt: "8 days ago",
    isoPostedAt: "2026-05-21T16:30:00+08:00",
    status: "active",
    applicantCount: 11,
  },
  {
    id: "job-010",
    employerId: "emp-005",
    title: "Healthcare Documentation Intern",
    category: "Health",
    type: "Internship",
    location: "Shanghai",
    remote: "Hybrid",
    description:
      "Support Siemens China's healthcare documentation team by reviewing training materials, safety notes, and user-facing explanations. The role is ideal for students who care about clarity in clinical settings.",
    responsibilities: ["Review training material drafts", "Summarize clinical user questions", "Check terminology consistency", "Prepare bilingual reference notes"],
    requirements: ["Health, pharmacy, biomedical, or documentation background", "Strong English", "Careful reading habits", "Interest in healthcare technology"],
    niceToHave: ["Mandarin HSK 4+", "Regulatory research experience", "SPSS or survey work"],
    languages: ["English fluent", "Mandarin HSK 4 preferred"],
    perks: ["Healthcare technology exposure", "Documentation mentor", "Hybrid work blocks"],
    salaryRange: "¥5,000-7,000/month",
    duration: "3 months",
    startDate: "June 2026",
    postedAt: "3 days ago",
    isoPostedAt: "2026-05-26T09:00:00+08:00",
    status: "active",
    applicantCount: 13,
  },
  {
    id: "job-011",
    employerId: "emp-005",
    title: "Smart Infrastructure Project Coordinator",
    category: "Business",
    type: "Full-time",
    location: "Shanghai",
    remote: "Hybrid",
    description:
      "Coordinate internal project updates for smart infrastructure teams working with international stakeholders. You will support meeting preparation, timeline tracking, and cross-team communication.",
    responsibilities: ["Prepare project status summaries", "Track action items after meetings", "Coordinate documentation updates", "Support customer presentation preparation"],
    requirements: ["Business or engineering management background", "Excellent English writing", "Structured follow-up habits", "Comfortable with technical teams"],
    niceToHave: ["Mandarin HSK 5+", "Power BI or dashboard experience", "Infrastructure interest"],
    languages: ["English fluent", "Mandarin HSK 5 preferred"],
    perks: ["Global project exposure", "Hybrid schedule", "Professional certification support"],
    salaryRange: "¥13,000-17,000/month",
    startDate: "July 2026",
    postedAt: "9 days ago",
    isoPostedAt: "2026-05-20T11:00:00+08:00",
    status: "active",
    applicantCount: 9,
  },
  {
    id: "job-012",
    employerId: "emp-006",
    title: "Cross-border Product Analyst",
    category: "Business",
    type: "Full-time",
    location: "Shanghai",
    remote: "Hybrid",
    description:
      "Analyze buyer behavior, product content quality, and regional trust signals for cross-border marketplace teams. The role fits students who understand both data and local customer context.",
    responsibilities: ["Build weekly market insight notes", "Audit product pages for customer trust gaps", "Segment buyer feedback by region", "Support campaign performance reviews"],
    requirements: ["Market research or analytics background", "Excel or SQL comfort", "Strong English writing", "Regional market knowledge"],
    niceToHave: ["Russian, Indonesian, or Vietnamese language", "CRM segmentation", "Marketplace operations experience"],
    languages: ["English fluent", "Mandarin HSK 4+", "Regional language valued"],
    perks: ["Fast-moving marketplace projects", "Data mentor", "Regional ownership opportunities"],
    salaryRange: "¥12,000-16,000/month",
    startDate: "August 2026",
    postedAt: "5 days ago",
    isoPostedAt: "2026-05-24T10:45:00+08:00",
    status: "active",
    applicantCount: 17,
  },
  {
    id: "job-013",
    employerId: "emp-006",
    title: "International Operations Intern",
    category: "Business",
    type: "Internship",
    location: "Shanghai",
    remote: "Hybrid",
    description:
      "Support daily operations for international product categories by reviewing seller questions, tracking content issues, and preparing small market reports. You will learn how marketplace operations move quickly without losing detail.",
    responsibilities: ["Track seller issue patterns", "Review localized listing quality", "Prepare market notes", "Support operations meeting follow-up"],
    requirements: ["Business or language background", "Comfortable with spreadsheets", "Clear English writing", "Interest in e-commerce operations"],
    niceToHave: ["Mandarin HSK 4+", "Experience with online marketplaces", "Russian or Central Asia knowledge"],
    languages: ["English proficient", "Mandarin helpful", "Regional language preferred"],
    perks: ["Operations training", "Hybrid work", "Exposure to marketplace growth teams"],
    salaryRange: "¥4,500-6,500/month",
    duration: "3-6 months",
    startDate: "June 2026",
    postedAt: "6 days ago",
    isoPostedAt: "2026-05-23T14:20:00+08:00",
    status: "active",
    applicantCount: 22,
  },
  {
    id: "job-014",
    employerId: "emp-007",
    title: "AI Engineering Intern",
    category: "Engineering",
    type: "Internship",
    location: "Hangzhou",
    remote: "Remote-friendly",
    description:
      "Help Lingxi AI evaluate multilingual support assistants for exporters and cross-border sellers. You will work on prompt tests, failure cases, and lightweight Python evaluation scripts.",
    responsibilities: ["Create multilingual test cases", "Run and document prompt evaluations", "Write small Python scripts for QA checks", "Summarize failure patterns for product managers"],
    requirements: ["Python basics", "Interest in NLP or AI products", "Strong English", "Careful testing mindset"],
    niceToHave: ["Mandarin HSK 4+", "Experience with chatbots", "One regional language"],
    languages: ["English fluent", "Mandarin helpful", "Regional language valued"],
    perks: ["Startup learning speed", "Remote-friendly work", "Direct product impact"],
    salaryRange: "¥4,000-6,000/month",
    duration: "3 months",
    startDate: "June 2026",
    postedAt: "2 days ago",
    isoPostedAt: "2026-05-27T13:10:00+08:00",
    status: "active",
    applicantCount: 26,
  },
  {
    id: "job-015",
    employerId: "emp-007",
    title: "Localization QA Specialist",
    category: "Language",
    type: "Both",
    location: "Hangzhou",
    remote: "Remote-friendly",
    description:
      "Review AI-generated support messages for meaning, tone, and cultural risk across Mandarin, English, and regional languages. This role can begin as an internship and convert to full-time.",
    responsibilities: ["Annotate support replies for quality risks", "Create terminology notes", "Review escalation decisions", "Suggest safer phrasing for sensitive cases"],
    requirements: ["Excellent language judgment", "Translation or interpretation experience", "Comfortable giving structured feedback"],
    niceToHave: ["Mongolian, Russian, Arabic, or Indonesian", "UX writing", "AI QA experience"],
    languages: ["English fluent", "Mandarin HSK 5 preferred", "Regional language required"],
    perks: ["Conversion path", "Flexible working blocks", "Portfolio-ready QA projects"],
    salaryRange: "¥5,000-9,000/month",
    duration: "3 months then conversion review",
    startDate: "July 2026",
    postedAt: "1 day ago",
    isoPostedAt: "2026-05-28T09:30:00+08:00",
    status: "active",
    applicantCount: 14,
  },
  {
    id: "job-016",
    employerId: "emp-007",
    title: "Business Development, Emerging Markets",
    category: "Business",
    type: "Full-time",
    location: "Hangzhou",
    remote: "Hybrid",
    description:
      "Help Lingxi AI identify exporter pain points and early customer opportunities in emerging markets. You will speak with small sellers, summarize needs, and support founder-led sales conversations.",
    responsibilities: ["Research exporter segments", "Prepare outreach lists", "Join discovery calls", "Summarize buyer and seller pain points"],
    requirements: ["Business research background", "Clear spoken English", "Comfortable with ambiguity", "Interest in AI products"],
    niceToHave: ["Mandarin HSK 4+", "MENA, Africa, or Southeast Asia knowledge", "Startup internship experience"],
    languages: ["English fluent", "Mandarin helpful", "Regional language valued"],
    perks: ["Founder mentorship", "Customer discovery ownership", "Hybrid schedule"],
    salaryRange: "¥10,000-14,000/month",
    startDate: "August 2026",
    postedAt: "4 days ago",
    isoPostedAt: "2026-05-25T16:00:00+08:00",
    status: "active",
    applicantCount: 8,
  },
  {
    id: "job-017",
    employerId: "emp-008",
    title: "Robotics Field Testing Intern",
    category: "Engineering",
    type: "Internship",
    location: "Ningbo",
    remote: "On-site",
    description:
      "Support warehouse robotics testing by reproducing field issues, collecting notes, and communicating findings to mechanical and software engineers. This role values patience, curiosity, and clear documentation.",
    responsibilities: ["Run structured field tests", "Record issue reproduction steps", "Collect photos and timing notes", "Discuss findings with engineering mentors"],
    requirements: ["Engineering major", "Hands-on lab or robotics project", "Clear technical writing", "Comfortable working on-site"],
    niceToHave: ["SolidWorks", "PLC basics", "Python data review"],
    languages: ["English proficient", "Mandarin helpful"],
    perks: ["Robotics site exposure", "Testing mentor", "Housing support during field weeks"],
    salaryRange: "¥5,000-7,000/month",
    duration: "3-6 months",
    startDate: "June 2026",
    postedAt: "2 days ago",
    isoPostedAt: "2026-05-27T10:40:00+08:00",
    status: "active",
    applicantCount: 13,
  },
  {
    id: "job-018",
    employerId: "emp-008",
    title: "Warehouse Automation Documentation Associate",
    category: "Engineering",
    type: "Both",
    location: "Ningbo",
    remote: "Hybrid",
    description:
      "Create training notes, setup guides, and troubleshooting references for warehouse automation deployments. The role can begin as an internship and move into a full-time documentation track.",
    responsibilities: ["Write deployment setup guides", "Interview engineers about recurring issues", "Turn test notes into customer-facing documents", "Maintain terminology consistency"],
    requirements: ["Engineering or technical communication background", "Strong English writing", "Comfort with diagrams", "Detail-focused review habits"],
    niceToHave: ["Mandarin HSK 4+", "Robotics project experience", "Figma or diagramming tools"],
    languages: ["English fluent", "Mandarin HSK 4 preferred"],
    perks: ["Conversion review", "Product documentation ownership", "Hybrid schedule"],
    salaryRange: "¥6,000-11,000/month",
    duration: "4 months then conversion review",
    startDate: "July 2026",
    postedAt: "5 days ago",
    isoPostedAt: "2026-05-24T12:00:00+08:00",
    status: "active",
    applicantCount: 9,
  },
  {
    id: "job-019",
    employerId: "emp-008",
    title: "Operations Research Intern",
    category: "Business",
    type: "Internship",
    location: "Ningbo",
    remote: "Hybrid",
    description:
      "Support warehouse layout and process studies for automation customers. You will analyze picking paths, compare process options, and prepare practical recommendations.",
    responsibilities: ["Clean operations datasets", "Map simple warehouse flows", "Compare process alternatives", "Prepare customer-facing summary slides"],
    requirements: ["Logistics, operations, or data background", "Excel modeling", "Clear English writing", "Interest in automation"],
    niceToHave: ["Python or SQL", "Warehouse simulation coursework", "Mandarin HSK 4+"],
    languages: ["English proficient", "Mandarin helpful"],
    perks: ["Customer operations exposure", "Hybrid analysis blocks", "Mentor feedback on reports"],
    salaryRange: "¥4,500-6,500/month",
    duration: "3 months",
    startDate: "June 2026",
    postedAt: "1 week ago",
    isoPostedAt: "2026-05-22T13:25:00+08:00",
    status: "active",
    applicantCount: 12,
  },
  {
    id: "job-020",
    employerId: "emp-005",
    title: "Healthcare Market Research Assistant",
    category: "Health",
    type: "Internship",
    location: "Shanghai",
    remote: "Remote-friendly",
    description:
      "Support research on how international users understand healthcare technology, labels, and training materials. You will help turn survey responses and literature notes into useful product insights.",
    responsibilities: ["Clean survey data", "Summarize healthcare communication patterns", "Review English training text", "Prepare simple charts for project leads"],
    requirements: ["Public health, pharmacy, or research background", "Excel or SPSS basics", "Strong English reading", "Careful handling of sensitive topics"],
    niceToHave: ["Mandarin HSK 3+", "Literature review experience", "Arabic, Amharic, or other regional language"],
    languages: ["English fluent", "Mandarin helpful", "Regional language valued"],
    perks: ["Remote-friendly research blocks", "Health-tech exposure", "Faculty-friendly schedule"],
    salaryRange: "¥4,000-6,000/month",
    duration: "3 months",
    startDate: "June 2026",
    postedAt: "10 days ago",
    isoPostedAt: "2026-05-19T10:00:00+08:00",
    status: "closed",
    applicantCount: 27,
  },
];
